
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 25 2026 11:20:59 IST (Jun 25 2026 05:50:59 UTC)

// Verification Directory fv/count8 

module count8(clk, rst, u_d, counter, SE, scan_in, scan_out);
  input clk, rst, u_d, SE, scan_in;
  output [7:0] counter;
  output scan_out;
  wire clk, rst, u_d, SE, scan_in;
  wire [7:0] counter;
  wire scan_out;
  wire [7:0] counter_u_d;
  wire n_0, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_13, n_15, n_22, n_24, n_27, n_28, n_29;
  wire n_30, n_31, n_33, n_34, n_36, n_42, n_43, n_44;
  wire n_49, n_51, n_52, n_54, n_55, n_56, n_57, n_71;
  wire n_79, n_85, n_93, n_94, n_99, n_110, n_160, n_167;
  wire n_168, n_169, n_170, n_175, n_176, n_180, n_181, n_182;
  wire n_185, n_187, n_203, n_204, n_208, n_209, n_210, n_211;
  wire n_212, n_220, n_221, n_222, n_232, n_234, n_235, n_236;
  assign scan_out = counter[7];
  SDFFRHQX1 \counter_u_d_reg[7] (.RN (n_57), .CK (clk), .D (n_56), .SI
       (counter[6]), .SE (SE), .Q (counter[7]));
  SDFFRHQX2 \counter_u_d_reg[6] (.RN (n_57), .CK (clk), .D (n_55), .SI
       (counter[5]), .SE (SE), .Q (counter[6]));
  SDFFRHQX4 \counter_u_d_reg[4] (.RN (n_57), .CK (clk), .D (n_52), .SI
       (counter[3]), .SE (SE), .Q (counter_u_d[4]));
  SDFFRHQX4 \counter_u_d_reg[5] (.RN (n_57), .CK (clk), .D (n_54), .SI
       (counter[4]), .SE (SE), .Q (counter_u_d[5]));
  NAND3X1 g4895__2398(.A (n_204), .B (n_176), .C (n_211), .Y (n_56));
  SDFFRHQX4 \counter_u_d_reg[2] (.RN (n_57), .CK (clk), .D (n_222), .SI
       (n_234), .SE (SE), .Q (counter_u_d[2]));
  SDFFRHQX4 \counter_u_d_reg[1] (.RN (n_57), .CK (clk), .D (n_182), .SI
       (counter[0]), .SE (SE), .Q (counter_u_d[1]));
  MXI2X1 g4898__5107(.A (counter[6]), .B (n_0), .S0 (n_49), .Y (n_55));
  MXI2X1 g4899__6260(.A (counter[5]), .B (n_99), .S0 (n_44), .Y (n_54));
  MXI2X1 g4892__8428(.A (counter[4]), .B (n_110), .S0 (n_42), .Y
       (n_52));
  MXI2X1 g4893__5526(.A (counter[3]), .B (n_79), .S0 (n_31), .Y (n_51));
  AOI31X1 g4908__3680(.A0 (n_9), .A1 (n_11), .A2 (n_15), .B0 (n_170),
       .Y (n_49));
  AOI31X1 g4912__5122(.A0 (n_43), .A1 (n_7), .A2 (n_13), .B0 (n_27), .Y
       (n_44));
  AOI31X2 g4901__8246(.A0 (n_79), .A1 (n_30), .A2 (n_29), .B0 (n_28),
       .Y (n_42));
  AOI21X1 g4900__4733(.A0 (n_30), .A1 (n_29), .B0 (n_22), .Y (n_31));
  NOR3X1 g4910__6161(.A (n_71), .B (n_24), .C (n_185), .Y (n_28));
  SDFFRHQX4 \counter_u_d_reg[0] (.RN (n_57), .CK (clk), .D (n_85), .SI
       (scan_in), .SE (SE), .Q (counter_u_d[0]));
  NOR3X1 g4915__9315(.A (n_24), .B (n_168), .C (n_167), .Y (n_27));
  NOR2XL g4909__2883(.A (n_5), .B (n_185), .Y (n_22));
  NOR2X1 g4921__7410(.A (n_94), .B (n_6), .Y (n_34));
  NOR2X2 g4920__6417(.A (n_4), .B (n_8), .Y (n_33));
  NOR3X1 g4919__5107(.A (counter_u_d[4]), .B (u_d), .C
       (counter_u_d[2]), .Y (n_15));
  NOR3X1 g4923__4319(.A (counter[6]), .B (counter_u_d[5]), .C
       (counter_u_d[0]), .Y (n_36));
  NOR2XL g4935__8428(.A (counter_u_d[0]), .B (counter_u_d[2]), .Y
       (n_13));
  NOR2XL g4928__6783(.A (counter_u_d[0]), .B (counter_u_d[5]), .Y
       (n_11));
  NAND2XL g4929__3680(.A (counter[7]), .B (u_d), .Y (n_10));
  NOR2XL g4930__1617(.A (counter_u_d[1]), .B (counter_u_d[3]), .Y
       (n_9));
  NAND2X1 g4924__2802(.A (counter_u_d[1]), .B (counter_u_d[2]), .Y
       (n_8));
  NOR2X1 g4934__1705(.A (counter_u_d[3]), .B (u_d), .Y (n_7));
  NOR2X2 g4932__8246(.A (counter_u_d[4]), .B (counter_u_d[1]), .Y
       (n_43));
  NAND2X1 g4926__7098(.A (counter[6]), .B (counter_u_d[5]), .Y (n_6));
  NAND2XL g4937__6131(.A (u_d), .B (counter_u_d[2]), .Y (n_5));
  NAND2X1 g4925__1881(.A (counter_u_d[3]), .B (counter_u_d[4]), .Y
       (n_4));
  NAND2X2 g4938__7482(.A (u_d), .B (counter_u_d[3]), .Y (n_24));
  NOR2X1 g4939__6161(.A (u_d), .B (counter_u_d[2]), .Y (n_30));
  NOR2X1 g4943__9315(.A (counter_u_d[1]), .B (counter_u_d[0]), .Y
       (n_29));
  INVXL g4948(.A (rst), .Y (n_57));
  INVXL g4944(.A (counter[6]), .Y (n_0));
  SDFFRHQX4 \counter_u_d_reg[3] (.RN (n_57), .CK (clk), .D (n_51), .SI
       (counter[2]), .SE (SE), .Q (counter_u_d[3]));
  CLKINVX1 fopt4967(.A (n_71), .Y (counter[2]));
  INVX1 fopt4(.A (counter_u_d[2]), .Y (n_71));
  CLKINVX1 fopt4972(.A (n_79), .Y (counter[3]));
  INVX1 fopt5(.A (counter_u_d[3]), .Y (n_79));
  INVX1 fopt4974(.A (counter[0]), .Y (n_85));
  INVXL fopt4975(.A (n_94), .Y (counter[0]));
  CLKINVX2 fopt6(.A (n_94), .Y (n_93));
  CLKINVX2 fopt7(.A (counter_u_d[0]), .Y (n_94));
  INVXL fopt4982(.A (counter[5]), .Y (n_99));
  CLKBUFX2 fopt4983(.A (counter_u_d[5]), .Y (counter[5]));
  INVXL fopt3(.A (counter[4]), .Y (n_110));
  CLKBUFX2 fopt4987(.A (counter_u_d[4]), .Y (counter[4]));
  NOR2XL g44(.A (counter_u_d[2]), .B (counter_u_d[3]), .Y (n_160));
  NOR3X1 g56(.A (n_167), .B (n_168), .C (n_169), .Y (n_170));
  NAND2X2 g58(.A (counter_u_d[4]), .B (counter_u_d[1]), .Y (n_167));
  NAND2X2 g59(.A (counter_u_d[2]), .B (counter_u_d[0]), .Y (n_168));
  NAND3X2 g57(.A (u_d), .B (counter_u_d[5]), .C (counter_u_d[3]), .Y
       (n_169));
  NAND3X1 g18(.A (n_175), .B (n_34), .C (n_33), .Y (n_176));
  NOR2XL g19(.A (counter[7]), .B (n_212), .Y (n_175));
  MXI2X1 g4903__5033(.A (n_212), .B (u_d), .S0 (n_181), .Y (n_182));
  NAND2X1 g1(.A (n_235), .B (n_180), .Y (n_181));
  NAND2XL g2(.A (n_232), .B (n_94), .Y (n_180));
  NOR2XL g5039(.A (n_185), .B (n_212), .Y (n_187));
  NAND2X2 g61(.A (counter_u_d[1]), .B (counter_u_d[0]), .Y (n_185));
  NAND3XL g46(.A (n_203), .B (n_36), .C (n_43), .Y (n_204));
  NOR4X1 g47(.A (counter[7]), .B (u_d), .C (counter_u_d[3]), .D
       (counter_u_d[2]), .Y (n_203));
  AOI21X1 g102(.A0 (n_208), .A1 (n_209), .B0 (n_210), .Y (n_211));
  NOR2BX1 g105(.AN (counter[7]), .B (u_d), .Y (n_208));
  NAND3X1 g104(.A (n_160), .B (n_43), .C (n_36), .Y (n_209));
  AOI21X1 g103(.A0 (n_34), .A1 (n_33), .B0 (n_10), .Y (n_210));
  INVX1 g106(.A (u_d), .Y (n_212));
  MXI2X1 g5057(.A (counter[2]), .B (n_220), .S0 (n_221), .Y (n_222));
  INVX1 g5059(.A (counter[2]), .Y (n_220));
  NOR2X2 g5060(.A (n_236), .B (n_187), .Y (n_221));
  CLKINVX3 g5063(.A (n_232), .Y (counter[1]));
  CLKINVX2 fopt5064(.A (counter_u_d[1]), .Y (n_232));
  BUFX2 g5065(.A (counter[1]), .Y (n_234));
  NAND2X2 g5066(.A (counter[1]), .B (n_93), .Y (n_235));
  NOR3X2 g5067(.A (u_d), .B (counter[1]), .C (n_93), .Y (n_236));
endmodule

