
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 19 2026 09:17:22 IST (Jun 19 2026 03:47:22 UTC)

// Verification Directory fv/count8 

module count8(clk, rst, u_d, counter);
  input clk, rst, u_d;
  output [7:0] counter;
  wire clk, rst, u_d;
  wire [7:0] counter;
  wire [7:0] counter_u_d;
  wire n_3, n_4, n_5, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_26, n_27, n_29, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_46, n_47, n_48;
  wire n_49, n_54, n_61, n_67, n_70, n_71, n_72;
  DFFRHQX1 \counter_u_d_reg[7] (.RN (n_49), .CK (clk), .D (n_48), .Q
       (counter[7]));
  DFFRHQX1 \counter_u_d_reg[6] (.RN (n_49), .CK (clk), .D (n_47), .Q
       (counter[6]));
  NAND2XL g4796__2398(.A (n_42), .B (n_43), .Y (n_48));
  DFFRHQX2 \counter_u_d_reg[4] (.RN (n_49), .CK (clk), .D (n_46), .Q
       (counter[4]));
  DFFRHQX1 \counter_u_d_reg[5] (.RN (n_49), .CK (clk), .D (n_70), .Q
       (counter[5]));
  MXI2X1 g4798__5107(.A (n_40), .B (n_39), .S0 (counter[6]), .Y (n_47));
  MXI2XL g4793__6260(.A (counter[4]), .B (n_67), .S0 (n_29), .Y (n_46));
  MXI2XL g4794__8428(.A (counter[3]), .B (n_54), .S0 (n_31), .Y (n_44));
  AOI31X1 g4800__5526(.A0 (counter[7]), .A1 (u_d), .A2 (n_24), .B0
       (n_38), .Y (n_43));
  AOI33X1 g4801__6783(.A0 (n_3), .A1 (n_37), .A2 (n_36), .B0 (u_d), .B1
       (n_35), .B2 (n_23), .Y (n_42));
  MXI2XL g4795__3680(.A (counter[2]), .B (n_61), .S0 (n_22), .Y (n_41));
  DFFRHQX4 \counter_u_d_reg[1] (.RN (n_49), .CK (clk), .D (n_71), .Q
       (counter[1]));
  CLKINVX1 g4806(.A (n_39), .Y (n_40));
  AOI211X1 g4808__1617(.A0 (n_37), .A1 (n_36), .B0 (u_d), .C0 (n_35),
       .Y (n_38));
  OAI31X1 g4809__2802(.A0 (n_32), .A1 (n_16), .A2 (n_33), .B0 (n_21),
       .Y (n_34));
  OAI32X2 g4807__1705(.A0 (n_33), .A1 (n_32), .A2 (n_12), .B0 (n_20),
       .B1 (n_15), .Y (n_39));
  AOI32X1 g4802__5122(.A0 (u_d), .A1 (counter[2]), .A2 (n_72), .B0
       (n_27), .B1 (n_26), .Y (n_31));
  AOI32X1 g4804__7098(.A0 (n_54), .A1 (n_27), .A2 (n_26), .B0 (n_18),
       .B1 (n_72), .Y (n_29));
  INVXL g4811(.A (n_23), .Y (n_24));
  MXI2XL g4805__6131(.A (n_26), .B (n_72), .S0 (u_d), .Y (n_22));
  NOR2X1 g4812__1881(.A (n_11), .B (n_10), .Y (n_23));
  NAND3X1 g4813__5115(.A (n_4), .B (n_19), .C (n_14), .Y (n_21));
  NAND2X1 g4814__7482(.A (n_5), .B (n_19), .Y (n_20));
  NOR2XL g4815__4733(.A (n_16), .B (n_61), .Y (n_18));
  NAND2XL g4816__6161(.A (n_14), .B (n_61), .Y (n_15));
  MXI2XL g4821__9315(.A (counter[0]), .B (n_9), .S0 (counter[1]), .Y
       (n_13));
  AND2X1 g4820__9945(.A (n_8), .B (n_7), .Y (n_36));
  NAND3X1 g4817__2883(.A (u_d), .B (counter_u_d[3]), .C (counter[5]),
       .Y (n_12));
  NAND4X1 g4818__2346(.A (counter_u_d[3]), .B (counter[1]), .C
       (counter[4]), .D (counter_u_d[2]), .Y (n_11));
  NAND3X1 g4819__1666(.A (counter[6]), .B (counter[5]), .C
       (counter[0]), .Y (n_10));
  NOR3X1 g4822__7410(.A (counter[6]), .B (counter[5]), .C (counter[0]),
       .Y (n_37));
  DFFRHQX4 \counter_u_d_reg[0] (.RN (n_49), .CK (clk), .D (n_9), .Q
       (counter[0]));
  NOR2X1 g4824__6417(.A (counter_u_d[3]), .B (counter[4]), .Y (n_8));
  NOR2X1 g4823__5477(.A (counter[1]), .B (counter_u_d[2]), .Y (n_7));
  NOR2XL g4825__5107(.A (counter[0]), .B (counter[5]), .Y (n_5));
  NOR2XL g4834__6260(.A (counter_u_d[2]), .B (u_d), .Y (n_27));
  NOR2X1 g4828__4319(.A (counter[1]), .B (counter[4]), .Y (n_19));
  NOR2XL g4830__8428(.A (counter[0]), .B (counter_u_d[2]), .Y (n_4));
  NOR2XL g4826__5526(.A (counter[7]), .B (u_d), .Y (n_3));
  NOR2X1 g4833__6783(.A (u_d), .B (counter_u_d[3]), .Y (n_14));
  NAND2XL g4832__3680(.A (counter_u_d[3]), .B (u_d), .Y (n_16));
  NAND2X1 g4827__1617(.A (counter[1]), .B (counter[4]), .Y (n_33));
  NAND2X1 g4831__2802(.A (counter[0]), .B (counter_u_d[2]), .Y (n_32));
  NOR2X1 g4836__1705(.A (counter[0]), .B (counter[1]), .Y (n_26));
  CLKINVX1 g4843(.A (counter[0]), .Y (n_9));
  CLKINVX1 g4837(.A (counter[7]), .Y (n_35));
  INVXL g4839(.A (rst), .Y (n_49));
  DFFRX2 \counter_u_d_reg[2] (.RN (n_49), .CK (clk), .D (n_41), .Q
       (counter_u_d[2]), .QN (n_61));
  CLKINVX1 fopt2(.A (counter[3]), .Y (n_54));
  CLKBUFX2 fopt3(.A (counter_u_d[3]), .Y (counter[3]));
  DFFRHQX4 \counter_u_d_reg[3] (.RN (n_49), .CK (clk), .D (n_44), .Q
       (counter_u_d[3]));
  INVX1 fopt4864(.A (n_61), .Y (counter[2]));
  CLKINVX1 fopt4867(.A (counter[4]), .Y (n_67));
  XOR2XL g2(.A (counter[5]), .B (n_34), .Y (n_70));
  XOR2XL g4868(.A (u_d), .B (n_13), .Y (n_71));
  AND2X1 g4869(.A (counter[0]), .B (counter[1]), .Y (n_72));
endmodule

