/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Wed Jun 24 13:10:57 2026
#  Design:            booth
#  Command:           saveNetlist booth_physical_netlist.v
###############################################################
*/
module booth (
	clk, 
	load, 
	reset, 
	M, 
	Q, 
	P);
   input clk;
   input load;
   input reset;
   input [3:0] M;
   input [3:0] Q;
   output [7:0] P;

   // Internal wires
   wire FE_RN_2;
   wire FE_RN_58_0;
   wire FE_OCPN13_P_0;
   wire FE_RN_57_0;
   wire FE_OCPN12_Count_0;
   wire FE_RN_56_0;
   wire FE_RN_55_0;
   wire FE_OCPN6_n_229;
   wire FE_RN_54_0;
   wire FE_RN_53_0;
   wire FE_RN_52_0;
   wire FE_OCPN5_n;
   wire FE_OCPN11_n_404;
   wire FE_OCPN10_P_5;
   wire FE_RN_51_0;
   wire FE_RN_50_0;
   wire FE_RN_49_0;
   wire FE_RN_48_0;
   wire FE_RN_47_0;
   wire FE_RN_45_0;
   wire FE_RN_44_0;
   wire FE_RN_43_0;
   wire FE_RN_42_0;
   wire FE_RN_41_0;
   wire FE_RN_39_0;
   wire FE_RN_38_0;
   wire FE_RN_36_0;
   wire FE_RN_35_0;
   wire FE_OCPN4_P_4;
   wire FE_RN_31_0;
   wire FE_OCPN3_P_5;
   wire FE_OCPN2_P_5;
   wire FE_RN_30_0;
   wire FE_RN_29_0;
   wire FE_RN_28_0;
   wire FE_RN_27_0;
   wire FE_RN_25_0;
   wire FE_RN_24_0;
   wire FE_RN_22_0;
   wire FE_RN_21_0;
   wire FE_RN_20_0;
   wire FE_RN_19_0;
   wire FE_RN_16_0;
   wire FE_OCPN1_P_6;
   wire FE_RN_15_0;
   wire FE_RN_14_0;
   wire FE_RN_13_0;
   wire FE_RN_12_0;
   wire FE_RN_8_0;
   wire FE_RN_7_0;
   wire FE_RN_6_0;
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_RN_3_0;
   wire FE_RN_1;
   wire FE_OCPN0_n_255;
   wire FE_RN_2_0;
   wire FE_RN_1_0;
   wire FE_DBTN1_load;
   wire FE_DBTN0_reset;
   wire [2:0] Count;
   wire [3:0] M_temp;
   wire Q_minus_one;
   wire n_1;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_14;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_30;
   wire n_34;
   wire n_36;
   wire n_37;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_44;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_56;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_75;
   wire n_76;
   wire n_79;
   wire n_85;
   wire n_86;
   wire n_90;
   wire n_92;
   wire n_96;
   wire n_124;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_199;
   wire n_200;
   wire n_214;
   wire n_227;
   wire n_229;
   wire n_231;
   wire n_232;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_255;
   wire n_257;
   wire n_262;
   wire n_275;
   wire n_276;
   wire n_278;
   wire n_307;
   wire n_308;
   wire n_309;
   wire n_311;
   wire n_313;
   wire n_314;
   wire n_316;
   wire n_317;
   wire n_318;
   wire n_322;
   wire n_323;
   wire n_326;
   wire n_327;
   wire n_328;
   wire n_329;
   wire n_331;
   wire n_332;
   wire n_333;
   wire n_334;
   wire n_335;
   wire n_336;
   wire n_337;
   wire n_338;
   wire n_352;
   wire n_355;
   wire n_356;
   wire n_358;
   wire n_359;
   wire n_388;
   wire n_390;
   wire n_391;
   wire n_392;
   wire n_393;
   wire n_403;
   wire n_404;
   wire n_405;
   wire n_407;
   wire n_446;

   assign P[6] = P[7] ;

   NOR2X2 g10467__4733_dup (.A(n_214),
	.B(n_10),
	.Y(FE_RN_2));
   NAND3X2 FE_RC_104_0 (.A(P[5]),
	.B(n_235),
	.C(n_236),
	.Y(n_237));
   CLKINVX1 FE_RC_103_0 (.A(n_238),
	.Y(FE_RN_58_0));
   AOI31X1 FE_RC_102_0 (.A0(n_235),
	.A1(n_236),
	.A2(P[5]),
	.B0(FE_RN_58_0),
	.Y(n_239));
   BUFX2 FE_OCPC13_P_0 (.A(P[0]),
	.Y(FE_OCPN13_P_0));
   NOR2X4 FE_RC_101_0 (.A(load),
	.B(reset),
	.Y(FE_RN_57_0));
   NOR2BX2 FE_RC_100_0 (.AN(FE_RN_57_0),
	.B(FE_OCPN6_n_229),
	.Y(n_337));
   CLKBUFX2 FE_OCPC12_Count_0 (.A(Count[0]),
	.Y(FE_OCPN12_Count_0));
   NOR2XL FE_RC_99_0 (.A(load),
	.B(reset),
	.Y(FE_RN_55_0));
   CLKINVX1 FE_RC_98_0 (.A(n_276),
	.Y(FE_RN_56_0));
   AOI22X1 FE_RC_97_0 (.A0(n_262),
	.A1(Q[3]),
	.B0(FE_RN_56_0),
	.B1(FE_RN_55_0),
	.Y(n_278));
   CLKBUFX3 FE_OCPC11_n_229 (.A(n_229),
	.Y(FE_OCPN6_n_229));
   CLKINVX1 FE_RC_96_0 (.A(FE_RN_2),
	.Y(FE_RN_52_0));
   CLKINVX1 FE_RC_95_0 (.A(n_21),
	.Y(FE_RN_53_0));
   NAND2X2 FE_RC_94_0 (.A(FE_RN_52_0),
	.B(FE_RN_53_0),
	.Y(n_50));
   CLKINVX1 FE_RC_93_0 (.A(n_36),
	.Y(FE_RN_54_0));
   NOR3BX1 FE_RC_92_0 (.AN(FE_RN_54_0),
	.B(FE_RN_2),
	.C(n_21),
	.Y(n_37));
   CLKBUFX3 FE_OCPC10_temp_2 (.A(M_temp[2]),
	.Y(FE_OCPN5_n));
   CLKBUFX2 FE_OCPC11_n_404 (.A(n_404),
	.Y(FE_OCPN11_n_404));
   CLKBUFX2 FE_OCPC10_P_5 (.A(P[5]),
	.Y(FE_OCPN10_P_5));
   CLKBUFX6 FE_RC_91_0 (.A(FE_OCPN1_P_6),
	.Y(P[7]));
   NAND3X6 FE_RC_90_0 (.A(load),
	.B(Q[1]),
	.C(FE_DBTN0_reset),
	.Y(FE_RN_51_0));
   CLKINVX1 FE_RC_89_0 (.A(FE_RN_51_0),
	.Y(FE_RN_50_0));
   NOR2X1 FE_RC_88_0 (.A(FE_RN_50_0),
	.B(n_193),
	.Y(n_194));
   NAND2X1 FE_RC_87_0 (.A(n_92),
	.B(n_68),
	.Y(FE_RN_47_0));
   NAND2X2 FE_RC_86_0 (.A(n_70),
	.B(n_69),
	.Y(FE_RN_49_0));
   OAI211X2 FE_RC_85_0 (.A0(n_69),
	.A1(n_70),
	.B0(n_92),
	.C0(FE_RN_49_0),
	.Y(FE_RN_5_0));
   AOI22X2 FE_RC_84_0 (.A0(FE_RN_39_0),
	.A1(n_58),
	.B0(FE_RN_35_0),
	.B1(FE_RN_36_0),
	.Y(FE_RN_48_0));
   OAI21X2 FE_RC_83_0 (.A0(FE_RN_38_0),
	.A1(FE_RN_48_0),
	.B0(FE_RN_31_0),
	.Y(FE_RN_30_0));
   CLKINVX1 FE_RC_82_0 (.A(n_124),
	.Y(FE_RN_45_0));
   NAND3X1 FE_RC_79_0 (.A(n_327),
	.B(FE_RN_45_0),
	.C(FE_RN_47_0),
	.Y(n_329));
   AOI21X1 FE_RC_78_0 (.A0(n_358),
	.A1(n_237),
	.B0(FE_RN_41_0),
	.Y(FE_RN_42_0));
   INVX2 FE_RC_77_0 (.A(FE_OCPN5_n),
	.Y(n_9));
   CLKINVX1 FE_RC_76_0 (.A(M_temp[2]),
	.Y(FE_RN_43_0));
   NOR2X1 FE_RC_75_0 (.A(FE_RN_43_0),
	.B(FE_OCPN1_P_6),
	.Y(n_22));
   NAND2X2 FE_RC_74_0 (.A(M_temp[2]),
	.B(FE_OCPN1_P_6),
	.Y(FE_RN_44_0));
   OAI21X4 FE_RC_73_0 (.A0(M_temp[2]),
	.A1(FE_OCPN1_P_6),
	.B0(FE_RN_44_0),
	.Y(n_58));
   NAND2X2 FE_RC_72_0 (.A(n_241),
	.B(FE_RN_8_0),
	.Y(FE_RN_41_0));
   NAND2X1 FE_RC_70_0 (.A(FE_RN_42_0),
	.B(FE_RN_24_0),
	.Y(n_242));
   CLKAND2X2 FE_RC_68_0 (.A(n_327),
	.B(n_42),
	.Y(FE_RN_1_0));
   NOR2X2 FE_RC_67_0 (.A(n_21),
	.B(FE_RN_4_0),
	.Y(n_56));
   NOR2X1 FE_RC_66_0 (.A(n_21),
	.B(FE_RN_4_0),
	.Y(FE_RN_39_0));
   CLKINVX1 FE_RC_63_0 (.A(n_58),
	.Y(FE_RN_35_0));
   CLKINVX2 FE_RC_62_0 (.A(n_56),
	.Y(FE_RN_36_0));
   CLKINVX1 FE_RC_60_0 (.A(n_235),
	.Y(FE_RN_38_0));
   BUFX3 FE_OCPC9_P_4 (.A(FE_OCPN4_P_4),
	.Y(P[4]));
   CLKINVX2 FE_OCPC8_P_4 (.A(FE_OCPN4_P_4),
	.Y(FE_RN_16_0));
   CLKINVX1 FE_RC_54_0 (.A(FE_RN_25_0),
	.Y(FE_RN_31_0));
   INVX1 FE_OCPC7_P_5 (.A(n_214),
	.Y(FE_OCPN3_P_5));
   INVX1 FE_OCPC6_P_5 (.A(n_214),
	.Y(FE_OCPN2_P_5));
   BUFX3 FE_OCPC5_P_5 (.A(n_214),
	.Y(P[5]));
   NAND3BX1 FE_RC_50_0 (.AN(n_358),
	.B(n_327),
	.C(FE_RN_30_0),
	.Y(n_328));
   CLKINVX1 FE_RC_49_0 (.A(Q_minus_one),
	.Y(FE_RN_27_0));
   AND2X1 FE_RC_48_0 (.A(n_76),
	.B(FE_RN_27_0),
	.Y(FE_RN_28_0));
   NAND2X1 FE_RC_47_0 (.A(n_75),
	.B(FE_RN_28_0),
	.Y(FE_RN_29_0));
   OAI21X1 FE_RC_46_0 (.A0(n_75),
	.A1(FE_RN_22_0),
	.B0(FE_RN_29_0),
	.Y(FE_RN_19_0));
   CLKINVX1 FE_RC_45_0 (.A(n_96),
	.Y(FE_RN_25_0));
   NAND2X1 FE_RC_41_0 (.A(n_239),
	.B(n_52),
	.Y(FE_RN_24_0));
   CLKINVX1 FE_RC_39_0 (.A(n_76),
	.Y(FE_RN_21_0));
   NAND2BX1 FE_RC_38_0 (.AN(Q_minus_one),
	.B(FE_RN_21_0),
	.Y(FE_RN_22_0));
   CLKINVX1 FE_RC_33_0 (.A(n_96),
	.Y(FE_RN_20_0));
   OAI21X1 FE_RC_32_0 (.A0(FE_RN_20_0),
	.A1(FE_RN_19_0),
	.B0(FE_RN_1_0),
	.Y(FE_RN_2_0));
   AOI21X2 FE_RC_30_0 (.A0(M_temp[0]),
	.A1(FE_RN_16_0),
	.B0(n_20),
	.Y(FE_RN_4_0));
   NAND2X1 FE_RC_28_0 (.A(P[6]),
	.B(FE_OCPN5_n),
	.Y(FE_RN_12_0));
   INVXL FE_RC_27_0 (.A(M_temp[2]),
	.Y(FE_RN_13_0));
   INVXL FE_RC_26_0 (.A(FE_OCPN1_P_6),
	.Y(FE_RN_14_0));
   OAI2BB1X1 FE_RC_25_0 (.A0N(FE_RN_14_0),
	.A1N(FE_RN_13_0),
	.B0(n_39),
	.Y(FE_RN_15_0));
   NAND2X2 FE_RC_24_0 (.A(FE_RN_12_0),
	.B(FE_RN_15_0),
	.Y(n_69));
   NAND2X1 FE_RC_21_0 (.A(Q_minus_one),
	.B(n_238),
	.Y(FE_RN_8_0));
   NAND2XL FE_RC_16_0 (.A(n_92),
	.B(n_235),
	.Y(FE_RN_6_0));
   AND2X1 FE_RC_15_0 (.A(FE_RN_6_0),
	.B(n_388),
	.Y(FE_RN_7_0));
   AOI21X1 FE_RC_14_0 (.A0(FE_RN_7_0),
	.A1(FE_RN_5_0),
	.B0(n_390),
	.Y(n_391));
   OAI22X2 FE_RC_11_0 (.A0(n_10),
	.A1(FE_OCPN3_P_5),
	.B0(n_36),
	.B1(n_8),
	.Y(n_39));
   CLKINVX2 FE_RC_9_0 (.A(FE_OCPN1_P_6),
	.Y(n_200));
   AND2XL FE_RC_7_0 (.A(n_323),
	.B(n_322),
	.Y(FE_RN_3_0));
   NAND3XL FE_RC_6_0 (.A(FE_RN_3_0),
	.B(n_328),
	.C(n_329),
	.Y(n_326));
   NAND2BX1 g2_dup (.AN(n_200),
	.B(n_9),
	.Y(FE_RN_1));
   BUFX6 FE_OCPC3_n_255 (.A(n_255),
	.Y(FE_OCPN0_n_255));
   NAND2XL FE_RC_2_0 (.A(n_391),
	.B(FE_RN_2_0),
	.Y(n_392));
   CLKINVX3 FE_OFC2_Q_minus_one (.A(Q_minus_one),
	.Y(n_235));
   CLKINVX2 FE_OFC1_P_0 (.A(P[0]),
	.Y(n_355));
   CLKINVX2 FE_OFC0_n_255 (.A(n_255),
	.Y(n_229));
   CLKINVX4 FE_DBTC1_load (.A(load),
	.Y(FE_DBTN1_load));
   CLKINVX20 FE_DBTC0_reset (.A(reset),
	.Y(FE_DBTN0_reset));
   DFFHQX4 \A_reg[2]  (.CK(clk),
	.D(n_392),
	.Q(FE_OCPN1_P_6));
   DFFQX4 \A_reg[1]  (.CK(clk),
	.D(n_326),
	.Q(n_214));
   DFFHQX4 \A_reg[0]  (.CK(clk),
	.D(n_246),
	.Q(FE_OCPN4_P_4));
   DFFHQX1 \P_reg[1]  (.CK(clk),
	.D(n_90),
	.Q(P[1]));
   DFFHQX1 \P_reg[2]  (.CK(clk),
	.D(n_85),
	.Q(P[2]));
   DFFQX4 \P_reg[3]  (.CK(clk),
	.D(n_86),
	.Q(P[3]));
   DFFHQX4 \Count_reg[1]  (.CK(clk),
	.D(n_79),
	.Q(Count[1]));
   DFFQX4 \P_reg[0]  (.CK(clk),
	.D(n_356),
	.Q(P[0]));
   OAI21X1 g10379__7098 (.A0(n_393),
	.A1(n_338),
	.B0(n_194),
	.Y(n_90));
   OAI21X1 g10383__5115 (.A0(n_60),
	.A1(n_338),
	.B0(n_278),
	.Y(n_86));
   OAI21X1 g10382__7482 (.A0(n_352),
	.A1(n_338),
	.B0(n_311),
	.Y(n_85));
   MDFFHQX4 \Count_reg[0]  (.CK(clk),
	.D0(n_337),
	.D1(n_262),
	.Q(Count[0]),
	.S0(FE_OCPN12_Count_0));
   DFFQX4 Q_minus_one_reg (.CK(clk),
	.D(n_275),
	.Q(Q_minus_one));
   OAI21X1 g10384__9945 (.A0(n_6),
	.A1(n_199),
	.B0(n_318),
	.Y(n_79));
   NAND2X1 g10405__6417 (.A(Q_minus_one),
	.B(n_59),
	.Y(n_68));
   AOI22XL g10421__4319 (.A0(n_51),
	.A1(n_359),
	.B0(P[4]),
	.B1(n_34),
	.Y(n_60));
   OAI21X1 g10420__8428 (.A0(n_58),
	.A1(n_39),
	.B0(n_40),
	.Y(n_59));
   OAI21X2 g10424__6783 (.A0(n_22),
	.A1(n_56),
	.B0(FE_RN_1),
	.Y(n_75));
   AOI21X1 g10435__2802 (.A0(n_36),
	.A1(n_50),
	.B0(n_37),
	.Y(n_53));
   OAI21X1 g10434__1705 (.A0(n_51),
	.A1(n_50),
	.B0(n_41),
	.Y(n_52));
   DFFHQX1 \M_temp_reg[3]  (.CK(clk),
	.D(n_30),
	.Q(M_temp[3]));
   DFFHQX4 \M_temp_reg[2]  (.CK(clk),
	.D(n_26),
	.Q(M_temp[2]));
   DFFHQX4 \M_temp_reg[0]  (.CK(clk),
	.D(n_28),
	.Q(M_temp[0]));
   DFFQX4 \M_temp_reg[1]  (.CK(clk),
	.D(n_27),
	.Q(M_temp[1]));
   NOR2BX1 g10415__5115 (.AN(P[1]),
	.B(n_229),
	.Y(n_44));
   INVXL g10413 (.A(n_358),
	.Y(n_42));
   DFFHQX4 \Count_reg[2]  (.CK(clk),
	.D(n_407),
	.Q(Count[2]));
   NAND2X1 g10436__4733 (.A(n_51),
	.B(n_50),
	.Y(n_41));
   NAND2XL g10432__6161 (.A(n_39),
	.B(n_58),
	.Y(n_40));
   NAND2XL g10437__2883 (.A(M_temp[0]),
	.B(n_359),
	.Y(n_34));
   OAI21X1 g10442__6417 (.A0(n_4),
	.A1(n_199),
	.B0(n_333),
	.Y(n_30));
   OAI21X1 g10441__5477 (.A0(n_1),
	.A1(n_199),
	.B0(n_331),
	.Y(n_28));
   OAI21X1 g10440__2398 (.A0(n_5),
	.A1(n_199),
	.B0(n_334),
	.Y(n_27));
   OAI21X1 g10443__5107 (.A0(n_3),
	.A1(n_199),
	.B0(n_336),
	.Y(n_26));
   CLKINVX1 g10449 (.A(n_76),
	.Y(n_70));
   AOI21XL g10450__5122 (.A0(Count[1]),
	.A1(Count[0]),
	.B0(n_404),
	.Y(n_14));
   MXI2X1 g10454__6131 (.A(n_200),
	.B(FE_OCPN1_P_6),
	.S0(M_temp[3]),
	.Y(n_76));
   NAND2X2 g10468__7482 (.A(P[6]),
	.B(n_235),
	.Y(n_92));
   NOR2X2 g10467__4733 (.A(n_214),
	.B(n_10),
	.Y(n_20));
   NOR2X2 g10465__9315 (.A(M_temp[1]),
	.B(FE_OCPN2_P_5),
	.Y(n_21));
   NOR2X2 g10456__2883 (.A(n_214),
	.B(M_temp[1]),
	.Y(n_8));
   NAND2X1 g10458__7410 (.A(P[6]),
	.B(Q_minus_one),
	.Y(n_96));
   NAND2X4 g10460__5477 (.A(FE_OCPN4_P_4),
	.B(M_temp[0]),
	.Y(n_36));
   NOR2BX2 g10461__2398 (.AN(M_temp[0]),
	.B(P[4]),
	.Y(n_51));
   INVXL g10481 (.A(Count[1]),
	.Y(n_6));
   CLKINVX1 g10480 (.A(M[1]),
	.Y(n_5));
   CLKINVX1 g10478 (.A(M[3]),
	.Y(n_4));
   CLKINVX1 g10477 (.A(M[2]),
	.Y(n_3));
   CLKINVX1 g10479 (.A(M[0]),
	.Y(n_1));
   CLKINVX4 g10483 (.A(M_temp[1]),
	.Y(n_10));
   CLKINVX3 fopt10502 (.A(n_236),
	.Y(n_124));
   NOR3X1 g124 (.A(reset),
	.B(load),
	.C(n_192),
	.Y(n_193));
   NAND2BX1 g126 (.AN(FE_OCPN0_n_255),
	.B(P[1]),
	.Y(n_192));
   NAND2X4 g131 (.A(load),
	.B(FE_DBTN0_reset),
	.Y(n_199));
   NAND3XL g529 (.A(n_232),
	.B(n_242),
	.C(n_245),
	.Y(n_246));
   NAND2XL g535 (.A(n_227),
	.B(n_231),
	.Y(n_232));
   NOR2BX1 g548 (.AN(P[4]),
	.B(reset),
	.Y(n_227));
   CLKINVX1 g537 (.A(n_446),
	.Y(n_231));
   CLKAND2X6 g536 (.A(n_355),
	.B(n_255),
	.Y(n_236));
   NAND2X1 g541 (.A(P[5]),
	.B(Q_minus_one),
	.Y(n_238));
   NOR2X8 g545 (.A(load),
	.B(reset),
	.Y(n_241));
   NAND2XL g533 (.A(n_243),
	.B(n_388),
	.Y(n_245));
   NOR2XL g547 (.A(n_235),
	.B(n_53),
	.Y(n_243));
   CLKINVX1 g544 (.A(n_241),
	.Y(n_247));
   NAND2BX1 g10570 (.AN(FE_OCPN0_n_255),
	.B(P[2]),
	.Y(n_257));
   NAND2X4 g133 (.A(n_403),
	.B(n_404),
	.Y(n_255));
   NOR2X4 g10572 (.A(reset),
	.B(FE_DBTN1_load),
	.Y(n_262));
   OAI32X1 g48 (.A0(n_235),
	.A1(reset),
	.A2(n_446),
	.B0(n_358),
	.B1(n_247),
	.Y(n_275));
   NAND2BX1 g191 (.AN(FE_OCPN0_n_255),
	.B(P[3]),
	.Y(n_276));
   OAI21X1 g154 (.A0(n_309),
	.A1(n_307),
	.B0(FE_DBTN0_reset),
	.Y(n_311));
   NOR2X1 g156 (.A(n_257),
	.B(load),
	.Y(n_307));
   NOR2X1 g155 (.A(n_308),
	.B(FE_DBTN1_load),
	.Y(n_309));
   INVX3 g157 (.A(Q[2]),
	.Y(n_308));
   NAND2X1 g18 (.A(FE_DBTN1_load),
	.B(n_313),
	.Y(n_314));
   NOR2X2 g19 (.A(FE_OCPN0_n_255),
	.B(reset),
	.Y(n_313));
   NAND2XL g24 (.A(FE_DBTN0_reset),
	.B(n_317),
	.Y(n_318));
   NOR2BX1 g25 (.AN(n_316),
	.B(load),
	.Y(n_317));
   NOR2XL g26 (.A(n_14),
	.B(n_229),
	.Y(n_316));
   NAND3X1 g119 (.A(n_229),
	.B(FE_OCPN10_P_5),
	.C(FE_DBTN0_reset),
	.Y(n_322));
   NAND3X1 g118 (.A(P[5]),
	.B(load),
	.C(FE_DBTN0_reset),
	.Y(n_323));
   NOR2X6 g10589 (.A(load),
	.B(reset),
	.Y(n_327));
   NAND2XL g10448__10592 (.A(M_temp[0]),
	.B(n_327),
	.Y(n_331));
   NAND2XL g10447__10593 (.A(M_temp[3]),
	.B(n_332),
	.Y(n_333));
   NOR2X8 g546_dup (.A(load),
	.B(reset),
	.Y(n_332));
   NAND2XL g10446__10594 (.A(M_temp[1]),
	.B(n_332),
	.Y(n_334));
   AOI22X2 g10399__10595 (.A0(n_332),
	.A1(n_44),
	.B0(Q[0]),
	.B1(n_262),
	.Y(n_335));
   NAND2XL g10445__10596 (.A(FE_OCPN5_n),
	.B(n_332),
	.Y(n_336));
   CLKINVX2 g35 (.A(n_337),
	.Y(n_338));
   INVXL fopt10604 (.A(P[3]),
	.Y(n_352));
   OAI21X1 g10387__10606 (.A0(n_355),
	.A1(n_314),
	.B0(n_335),
	.Y(n_356));
   NAND2X2 g10417__10608 (.A(FE_OCPN13_P_0),
	.B(FE_OCPN0_n_255),
	.Y(n_358));
   AOI22XL g10451__10610 (.A0(n_355),
	.A1(n_235),
	.B0(FE_OCPN13_P_0),
	.B1(Q_minus_one),
	.Y(n_359));
   NOR3X6 g10633 (.A(load),
	.B(reset),
	.C(n_124),
	.Y(n_388));
   NOR3BX2 g10637 (.AN(P[6]),
	.B(reset),
	.C(n_446),
	.Y(n_390));
   INVXL fopt10638 (.A(P[2]),
	.Y(n_393));
   CLKINVX3 g10642 (.A(Count[2]),
	.Y(n_403));
   OAI211X1 g10643 (.A0(n_403),
	.A1(FE_OCPN11_n_404),
	.B0(FE_DBTN0_reset),
	.C0(n_405),
	.Y(n_407));
   NOR2X6 g10644 (.A(Count[1]),
	.B(Count[0]),
	.Y(n_404));
   NAND2X1 g10645 (.A(Count[2]),
	.B(load),
	.Y(n_405));
   NOR2X4 g10419__10514_dup10674 (.A(n_229),
	.B(load),
	.Y(n_446));
endmodule

