create_clock -name clk -period 0.5 -waveform {0 0.25} [get_ports "clk"]
set_clock_transition -rise 0.05 [get_clocks "clk"]
set_clock_transition -fall 0.05 [get_clocks "clk"]
set_clock_uncertainty 0.005 [get_ports "clk"]
set_input_delay -max 0.2 [get_ports "rst"] -clock [get_clocks "clk"]
set_input_delay -max 0.2 [get_ports "clk"] -clock [get_clocks "clk"]
set_input_delay -max 0.2 [get_ports "din"] -clock [get_clocks "clk"]
set_output_delay -max 0.2 [get_ports "dout_1001"] -clock [get_clocks "clk"]
set_output_delay -max 0.2 [get_ports "dout_1100"] -clock [get_clocks "clk"]
set_output_delay -max 0.2 [get_ports "dout_1101"] -clock [get_clocks "clk"]
