
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 22 2026 11:06:25 IST (Jun 22 2026 05:36:25 UTC)

// Verification Directory fv/mealy 

module mealy(clk, rst, din, dout_1001, dout_1100, dout_1101);
  input clk, rst, din;
  output dout_1001, dout_1100, dout_1101;
  wire clk, rst, din;
  wire dout_1001, dout_1100, dout_1101;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_3, n_4, n_5;
  wire n_7, n_8, n_9, n_11, n_12, n_13, n_14, n_15;
  wire n_24, n_26, n_27, n_28, n_31, n_32, n_34, n_36;
  wire n_37, n_38;
  DFFRHQX1 dout_1101_reg(.RN (n_15), .CK (clk), .D (n_12), .Q
       (dout_1101));
  AOI21X1 g708__2398(.A0 (n_27), .A1 (n_3), .B0 (n_7), .Y (n_14));
  OAI21XL g710__5107(.A0 (n_4), .A1 (n_1), .B0 (n_5), .Y (n_13));
  DFFRHQX4 \state_reg[1] (.RN (n_15), .CK (clk), .D (n_11), .Q
       (state[1]));
  AOI21X1 g709__6260(.A0 (n_32), .A1 (n_0), .B0 (n_24), .Y (n_12));
  NOR3X1 g711__4319(.A (state[2]), .B (n_37), .C (n_32), .Y (n_11));
  NOR3X2 g712__8428(.A (din), .B (n_36), .C (n_27), .Y (n_9));
  NOR4X1 g713__5526(.A (n_7), .B (state[0]), .C (state[1]), .D (n_28),
       .Y (n_8));
  NAND4X1 g714__6783(.A (state[1]), .B (din), .C (state[0]), .D (n_26),
       .Y (n_5));
  NAND2XL g715__3680(.A (n_7), .B (n_31), .Y (n_4));
  NAND2X1 g717__1617(.A (n_32), .B (n_34), .Y (n_3));
  NAND2XL g718__2802(.A (state[2]), .B (n_38), .Y (n_1));
  NOR2X1 g716__1705(.A (din), .B (n_37), .Y (n_0));
  CLKINVX1 g722(.A (din), .Y (n_7));
  INVXL g719(.A (rst), .Y (n_15));
  DFFRX4 \state_reg[0] (.RN (n_15), .CK (clk), .D (n_14), .Q
       (state[0]), .QN (UNCONNECTED));
  INVXL fopt734(.A (state[2]), .Y (n_24));
  INVX2 fopt735(.A (state[2]), .Y (n_26));
  CLKINVX2 fopt736(.A (n_28), .Y (n_27));
  INVX1 fopt3(.A (state[2]), .Y (n_28));
  DFFRHQX4 \state_reg[2] (.RN (n_15), .CK (clk), .D (n_9), .Q
       (state[2]));
  INVXL fopt739(.A (state[0]), .Y (n_31));
  CLKINVX1 fopt740(.A (state[0]), .Y (n_32));
  INVXL fopt741(.A (state[1]), .Y (n_34));
  INVX1 fopt4(.A (n_37), .Y (n_36));
  CLKINVX2 fopt5(.A (n_38), .Y (n_37));
  CLKINVX2 fopt6(.A (state[1]), .Y (n_38));
  DFFRXL dout_1001_reg(.RN (n_15), .CK (clk), .D (n_8), .Q (dout_1001),
       .QN (UNCONNECTED0));
  DFFRX2 dout_1100_reg(.RN (n_15), .CK (clk), .D (n_13), .Q
       (dout_1100), .QN (UNCONNECTED1));
endmodule

