/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Wed Jun 24 09:34:45 2026
#  Design:            count8
#  Command:           saveNetlist count8_physicalnetlist.v
###############################################################
*/
module count8 (
	clk, 
	rst, 
	u_d, 
	counter);
   input clk;
   input rst;
   input u_d;
   output [7:0] counter;

   // Internal wires
   wire FE_OCPN9_n_27;
   wire FE_RN_2_0;
   wire FE_RN_1_0;
   wire FE_RN_0_0;
   wire FE_OCPN6_counter_3;
   wire FE_OCPN5_counter_1;
   wire FE_OCPN2_counter_4;
   wire FE_RN_2;
   wire FE_OCPN0_counter_0;
   wire FE_RN_1;
   wire [7:0] counter_u_d;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_26;
   wire n_27;
   wire n_29;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_54;
   wire n_61;
   wire n_67;
   wire n_70;
   wire n_71;
   wire n_72;

   BUFX3 FE_OCPC9_n_27 (.A(n_27),
	.Y(FE_OCPN9_n_27));
   NOR2X1 FE_RC_5_0 (.A(n_9),
	.B(u_d),
	.Y(FE_RN_0_0));
   AOI21X1 FE_RC_4_0 (.A0(n_9),
	.A1(u_d),
	.B0(FE_RN_0_0),
	.Y(FE_RN_1_0));
   CLKXOR2X1 FE_RC_3_0 (.A(FE_OCPN0_counter_0),
	.B(u_d),
	.Y(FE_RN_2_0));
   MXI2X1 FE_RC_2_0 (.A(FE_RN_2_0),
	.B(FE_RN_1_0),
	.S0(FE_OCPN5_counter_1),
	.Y(n_71));
   CLKBUFX2 FE_OCPC6_counter_3 (.A(counter[3]),
	.Y(FE_OCPN6_counter_3));
   CLKBUFX2 FE_OCPC5_counter_1 (.A(counter[1]),
	.Y(FE_OCPN5_counter_1));
   CLKBUFX2 FE_OCPC3_counter_4 (.A(FE_OCPN2_counter_4),
	.Y(counter[4]));
   NAND4X2 FE_RC_1_0 (.A(FE_OCPN2_counter_4),
	.B(counter[1]),
	.C(counter[3]),
	.D(counter_u_d[2]),
	.Y(n_11));
   OAI32X2 FE_RC_0_0 (.A0(n_32),
	.A1(n_33),
	.A2(n_12),
	.B0(n_15),
	.B1(n_20),
	.Y(n_39));
   NOR2X1 g4833__6783_dup (.A(u_d),
	.B(counter[3]),
	.Y(FE_RN_2));
   BUFX2 FE_OCPC1_counter_0 (.A(FE_OCPN0_counter_0),
	.Y(counter[0]));
   NOR2X1 g4828__4319_dup (.A(FE_OCPN2_counter_4),
	.B(counter[1]),
	.Y(FE_RN_1));
   INVX1 FE_OFC0_rst (.A(rst),
	.Y(n_49));
   DFFRHQX1 \counter_u_d_reg[7]  (.CK(clk),
	.D(n_48),
	.Q(counter[7]),
	.RN(n_49));
   DFFRHQX8 \counter_u_d_reg[6]  (.CK(clk),
	.D(n_47),
	.Q(counter[6]),
	.RN(n_49));
   NAND2X1 g4796__2398 (.A(n_42),
	.B(n_43),
	.Y(n_48));
   DFFRHQX4 \counter_u_d_reg[4]  (.CK(clk),
	.D(n_46),
	.Q(FE_OCPN2_counter_4),
	.RN(n_49));
   DFFRHQX2 \counter_u_d_reg[5]  (.CK(clk),
	.D(n_70),
	.Q(counter[5]),
	.RN(n_49));
   MXI2X1 g4798__5107 (.A(n_40),
	.B(n_39),
	.S0(counter[6]),
	.Y(n_47));
   MXI2X1 g4793__6260 (.A(counter[4]),
	.B(n_67),
	.S0(n_29),
	.Y(n_46));
   MXI2X1 g4794__8428 (.A(FE_OCPN6_counter_3),
	.B(n_54),
	.S0(n_31),
	.Y(n_44));
   AOI31X1 g4800__5526 (.A0(counter[7]),
	.A1(u_d),
	.A2(n_24),
	.B0(n_38),
	.Y(n_43));
   AOI33X1 g4801__6783 (.A0(n_3),
	.A1(n_37),
	.A2(n_36),
	.B0(u_d),
	.B1(n_35),
	.B2(n_23),
	.Y(n_42));
   MXI2X1 g4795__3680 (.A(counter[2]),
	.B(n_61),
	.S0(n_22),
	.Y(n_41));
   DFFRHQX4 \counter_u_d_reg[1]  (.CK(clk),
	.D(n_71),
	.Q(counter[1]),
	.RN(n_49));
   CLKINVX2 g4806 (.A(n_39),
	.Y(n_40));
   AOI211X1 g4808__1617 (.A0(n_37),
	.A1(n_36),
	.B0(u_d),
	.C0(n_35),
	.Y(n_38));
   OAI31X1 g4809__2802 (.A0(n_33),
	.A1(n_16),
	.A2(n_32),
	.B0(n_21),
	.Y(n_34));
   AOI32X2 g4802__5122 (.A0(u_d),
	.A1(counter[2]),
	.A2(n_72),
	.B0(FE_OCPN9_n_27),
	.B1(n_26),
	.Y(n_31));
   AOI32X1 g4804__7098 (.A0(n_54),
	.A1(n_27),
	.A2(n_26),
	.B0(n_18),
	.B1(n_72),
	.Y(n_29));
   INVXL g4811 (.A(n_23),
	.Y(n_24));
   MXI2X1 g4805__6131 (.A(n_26),
	.B(n_72),
	.S0(u_d),
	.Y(n_22));
   NOR2X1 g4812__1881 (.A(n_11),
	.B(n_10),
	.Y(n_23));
   NAND3X1 g4813__5115 (.A(n_4),
	.B(FE_RN_1),
	.C(FE_RN_2),
	.Y(n_21));
   NAND2X1 g4814__7482 (.A(n_5),
	.B(n_19),
	.Y(n_20));
   NOR2X1 g4815__4733 (.A(n_16),
	.B(n_61),
	.Y(n_18));
   NAND2X1 g4816__6161 (.A(n_14),
	.B(n_61),
	.Y(n_15));
   CLKAND2X3 g4820__9945 (.A(n_8),
	.B(n_7),
	.Y(n_36));
   NAND3X2 g4817__2883 (.A(u_d),
	.B(counter[3]),
	.C(counter[5]),
	.Y(n_12));
   NAND3X2 g4819__1666 (.A(counter[6]),
	.B(counter[5]),
	.C(FE_OCPN0_counter_0),
	.Y(n_10));
   NOR3X2 g4822__7410 (.A(counter[6]),
	.B(counter[5]),
	.C(FE_OCPN0_counter_0),
	.Y(n_37));
   DFFRHQX4 \counter_u_d_reg[0]  (.CK(clk),
	.D(n_9),
	.Q(FE_OCPN0_counter_0),
	.RN(n_49));
   NOR2X2 g4824__6417 (.A(FE_OCPN2_counter_4),
	.B(counter[3]),
	.Y(n_8));
   NOR2X1 g4823__5477 (.A(counter[1]),
	.B(counter_u_d[2]),
	.Y(n_7));
   NOR2X1 g4825__5107 (.A(FE_OCPN0_counter_0),
	.B(counter[5]),
	.Y(n_5));
   NOR2X1 g4834__6260 (.A(counter_u_d[2]),
	.B(u_d),
	.Y(n_27));
   NOR2X1 g4828__4319 (.A(counter[1]),
	.B(FE_OCPN2_counter_4),
	.Y(n_19));
   NOR2X2 g4830__8428 (.A(FE_OCPN0_counter_0),
	.B(counter_u_d[2]),
	.Y(n_4));
   NOR2XL g4826__5526 (.A(counter[7]),
	.B(u_d),
	.Y(n_3));
   NOR2X1 g4833__6783 (.A(u_d),
	.B(counter[3]),
	.Y(n_14));
   NAND2X1 g4832__3680 (.A(counter[3]),
	.B(u_d),
	.Y(n_16));
   NAND2X2 g4827__1617 (.A(counter[1]),
	.B(FE_OCPN2_counter_4),
	.Y(n_33));
   NAND2X2 g4831__2802 (.A(FE_OCPN0_counter_0),
	.B(counter_u_d[2]),
	.Y(n_32));
   NOR2X2 g4836__1705 (.A(FE_OCPN0_counter_0),
	.B(counter[1]),
	.Y(n_26));
   CLKINVX1 g4843 (.A(counter[0]),
	.Y(n_9));
   CLKINVX1 g4837 (.A(counter[7]),
	.Y(n_35));
   DFFRX4 \counter_u_d_reg[2]  (.CK(clk),
	.D(n_41),
	.Q(counter_u_d[2]),
	.QN(n_61),
	.RN(n_49));
   CLKINVX1 fopt2 (.A(counter[3]),
	.Y(n_54));
   DFFRHQX4 \counter_u_d_reg[3]  (.CK(clk),
	.D(n_44),
	.Q(counter[3]),
	.RN(n_49));
   CLKINVX3 fopt4864 (.A(n_61),
	.Y(counter[2]));
   CLKINVX1 fopt4867 (.A(counter[4]),
	.Y(n_67));
   XOR2XL g2 (.A(counter[5]),
	.B(n_34),
	.Y(n_70));
   AND2X4 g4869 (.A(FE_OCPN0_counter_0),
	.B(counter[1]),
	.Y(n_72));
endmodule

