
//input ports
add mapped point addr[15] addr[15] -type PI PI
add mapped point addr[14] addr[14] -type PI PI
add mapped point addr[13] addr[13] -type PI PI
add mapped point addr[12] addr[12] -type PI PI
add mapped point addr[11] addr[11] -type PI PI
add mapped point addr[10] addr[10] -type PI PI
add mapped point addr[9] addr[9] -type PI PI
add mapped point addr[8] addr[8] -type PI PI
add mapped point addr[7] addr[7] -type PI PI
add mapped point addr[6] addr[6] -type PI PI
add mapped point addr[5] addr[5] -type PI PI
add mapped point addr[4] addr[4] -type PI PI
add mapped point addr[3] addr[3] -type PI PI
add mapped point addr[2] addr[2] -type PI PI
add mapped point addr[1] addr[1] -type PI PI
add mapped point addr[0] addr[0] -type PI PI
add mapped point cs cs -type PI PI
add mapped point re re -type PI PI
add mapped point we we -type PI PI
add mapped point clk clk -type PI PI
add mapped point reset reset -type PI PI
add mapped point data_in[31] data_in[31] -type PI PI
add mapped point data_in[30] data_in[30] -type PI PI
add mapped point data_in[29] data_in[29] -type PI PI
add mapped point data_in[28] data_in[28] -type PI PI
add mapped point data_in[27] data_in[27] -type PI PI
add mapped point data_in[26] data_in[26] -type PI PI
add mapped point data_in[25] data_in[25] -type PI PI
add mapped point data_in[24] data_in[24] -type PI PI
add mapped point data_in[23] data_in[23] -type PI PI
add mapped point data_in[22] data_in[22] -type PI PI
add mapped point data_in[21] data_in[21] -type PI PI
add mapped point data_in[20] data_in[20] -type PI PI
add mapped point data_in[19] data_in[19] -type PI PI
add mapped point data_in[18] data_in[18] -type PI PI
add mapped point data_in[17] data_in[17] -type PI PI
add mapped point data_in[16] data_in[16] -type PI PI
add mapped point data_in[15] data_in[15] -type PI PI
add mapped point data_in[14] data_in[14] -type PI PI
add mapped point data_in[13] data_in[13] -type PI PI
add mapped point data_in[12] data_in[12] -type PI PI
add mapped point data_in[11] data_in[11] -type PI PI
add mapped point data_in[10] data_in[10] -type PI PI
add mapped point data_in[9] data_in[9] -type PI PI
add mapped point data_in[8] data_in[8] -type PI PI
add mapped point data_in[7] data_in[7] -type PI PI
add mapped point data_in[6] data_in[6] -type PI PI
add mapped point data_in[5] data_in[5] -type PI PI
add mapped point data_in[4] data_in[4] -type PI PI
add mapped point data_in[3] data_in[3] -type PI PI
add mapped point data_in[2] data_in[2] -type PI PI
add mapped point data_in[1] data_in[1] -type PI PI
add mapped point data_in[0] data_in[0] -type PI PI

//output ports
add mapped point data_out[31] data_out[31] -type PO PO
add mapped point data_out[30] data_out[30] -type PO PO
add mapped point data_out[29] data_out[29] -type PO PO
add mapped point data_out[28] data_out[28] -type PO PO
add mapped point data_out[27] data_out[27] -type PO PO
add mapped point data_out[26] data_out[26] -type PO PO
add mapped point data_out[25] data_out[25] -type PO PO
add mapped point data_out[24] data_out[24] -type PO PO
add mapped point data_out[23] data_out[23] -type PO PO
add mapped point data_out[22] data_out[22] -type PO PO
add mapped point data_out[21] data_out[21] -type PO PO
add mapped point data_out[20] data_out[20] -type PO PO
add mapped point data_out[19] data_out[19] -type PO PO
add mapped point data_out[18] data_out[18] -type PO PO
add mapped point data_out[17] data_out[17] -type PO PO
add mapped point data_out[16] data_out[16] -type PO PO
add mapped point data_out[15] data_out[15] -type PO PO
add mapped point data_out[14] data_out[14] -type PO PO
add mapped point data_out[13] data_out[13] -type PO PO
add mapped point data_out[12] data_out[12] -type PO PO
add mapped point data_out[11] data_out[11] -type PO PO
add mapped point data_out[10] data_out[10] -type PO PO
add mapped point data_out[9] data_out[9] -type PO PO
add mapped point data_out[8] data_out[8] -type PO PO
add mapped point data_out[7] data_out[7] -type PO PO
add mapped point data_out[6] data_out[6] -type PO PO
add mapped point data_out[5] data_out[5] -type PO PO
add mapped point data_out[4] data_out[4] -type PO PO
add mapped point data_out[3] data_out[3] -type PO PO
add mapped point data_out[2] data_out[2] -type PO PO
add mapped point data_out[1] data_out[1] -type PO PO
add mapped point data_out[0] data_out[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point data_out[0]/q data_out_reg[0]/Q -type DFF DFF
add mapped point data_out[1]/q data_out_reg[1]/Q -type DFF DFF
add mapped point data_out[4]/q data_out_reg[4]/Q -type DFF DFF
add mapped point data_out[11]/q data_out_reg[11]/Q -type DFF DFF
add mapped point data_out[26]/q data_out_reg[26]/Q -type DFF DFF
add mapped point data_out[12]/q data_out_reg[12]/Q -type DFF DFF
add mapped point data_out[27]/q data_out_reg[27]/Q -type DFF DFF
add mapped point data_out[28]/q data_out_reg[28]/Q -type DFF DFF
add mapped point data_out[13]/q data_out_reg[13]/Q -type DFF DFF
add mapped point data_out[29]/q data_out_reg[29]/Q -type DFF DFF
add mapped point data_out[30]/q data_out_reg[30]/Q -type DFF DFF
add mapped point data_out[14]/q data_out_reg[14]/Q -type DFF DFF
add mapped point data_out[31]/q data_out_reg[31]/Q -type DFF DFF
add mapped point data_out[5]/q data_out_reg[5]/Q -type DFF DFF
add mapped point data_out[15]/q data_out_reg[15]/Q -type DFF DFF
add mapped point data_out[6]/q data_out_reg[6]/Q -type DFF DFF
add mapped point data_out[16]/q data_out_reg[16]/Q -type DFF DFF
add mapped point data_out[17]/q data_out_reg[17]/Q -type DFF DFF
add mapped point data_out[2]/q data_out_reg[2]/Q -type DFF DFF
add mapped point data_out[7]/q data_out_reg[7]/Q -type DFF DFF
add mapped point data_out[18]/q data_out_reg[18]/Q -type DFF DFF
add mapped point data_out[19]/q data_out_reg[19]/Q -type DFF DFF
add mapped point data_out[8]/q data_out_reg[8]/Q -type DFF DFF
add mapped point data_out[20]/q data_out_reg[20]/Q -type DFF DFF
add mapped point data_out[21]/q data_out_reg[21]/Q -type DFF DFF
add mapped point data_out[3]/q data_out_reg[3]/Q -type DFF DFF
add mapped point data_out[9]/q data_out_reg[9]/Q -type DFF DFF
add mapped point data_out[22]/q data_out_reg[22]/Q -type DFF DFF
add mapped point data_out[23]/q data_out_reg[23]/Q -type DFF DFF
add mapped point data_out[10]/q data_out_reg[10]/Q -type DFF DFF
add mapped point data_out[24]/q data_out_reg[24]/Q -type DFF DFF
add mapped point data_out[25]/q data_out_reg[25]/Q -type DFF DFF
add mapped point mem[2][20]/q mem_reg[2][20]/Q -type DFF DFF
add mapped point mem[3][23]/q mem_reg[3][23]/Q -type DFF DFF
add mapped point mem[3][19]/q mem_reg[3][19]/Q -type DFF DFF
add mapped point mem[4][23]/q mem_reg[4][23]/Q -type DFF DFF
add mapped point mem[5][23]/q mem_reg[5][23]/Q -type DFF DFF
add mapped point mem[3][15]/q mem_reg[3][15]/Q -type DFF DFF
add mapped point mem[4][19]/q mem_reg[4][19]/Q -type DFF DFF
add mapped point mem[5][19]/q mem_reg[5][19]/Q -type DFF DFF
add mapped point mem[3][7]/q mem_reg[3][7]/Q -type DFF DFF
add mapped point mem[3][3]/q mem_reg[3][3]/Q -type DFF DFF
add mapped point mem[4][15]/q mem_reg[4][15]/Q -type DFF DFF
add mapped point mem[5][15]/q mem_reg[5][15]/Q -type DFF DFF
add mapped point mem[0][31]/q mem_reg[0][31]/Q -type DFF DFF
add mapped point mem[5][7]/q mem_reg[5][7]/Q -type DFF DFF
add mapped point mem[3][31]/q mem_reg[3][31]/Q -type DFF DFF
add mapped point mem[0][23]/q mem_reg[0][23]/Q -type DFF DFF
add mapped point mem[9][25]/q mem_reg[9][25]/Q -type DFF DFF
add mapped point mem[9][30]/q mem_reg[9][30]/Q -type DFF DFF
add mapped point mem[10][7]/q mem_reg[10][7]/Q -type DFF DFF
add mapped point mem[10][29]/q mem_reg[10][29]/Q -type DFF DFF
add mapped point mem[0][12]/q mem_reg[0][12]/Q -type DFF DFF
add mapped point mem[10][4]/q mem_reg[10][4]/Q -type DFF DFF
add mapped point mem[0][8]/q mem_reg[0][8]/Q -type DFF DFF
add mapped point mem[0][20]/q mem_reg[0][20]/Q -type DFF DFF
add mapped point mem[1][0]/q mem_reg[1][0]/Q -type DFF DFF
add mapped point mem[1][1]/q mem_reg[1][1]/Q -type DFF DFF
add mapped point mem[1][2]/q mem_reg[1][2]/Q -type DFF DFF
add mapped point mem[1][3]/q mem_reg[1][3]/Q -type DFF DFF
add mapped point mem[1][4]/q mem_reg[1][4]/Q -type DFF DFF
add mapped point mem[1][5]/q mem_reg[1][5]/Q -type DFF DFF
add mapped point mem[10][22]/q mem_reg[10][22]/Q -type DFF DFF
add mapped point mem[1][6]/q mem_reg[1][6]/Q -type DFF DFF
add mapped point mem[1][7]/q mem_reg[1][7]/Q -type DFF DFF
add mapped point mem[1][8]/q mem_reg[1][8]/Q -type DFF DFF
add mapped point mem[0][16]/q mem_reg[0][16]/Q -type DFF DFF
add mapped point mem[1][9]/q mem_reg[1][9]/Q -type DFF DFF
add mapped point mem[1][10]/q mem_reg[1][10]/Q -type DFF DFF
add mapped point mem[1][11]/q mem_reg[1][11]/Q -type DFF DFF
add mapped point mem[10][16]/q mem_reg[10][16]/Q -type DFF DFF
add mapped point mem[1][12]/q mem_reg[1][12]/Q -type DFF DFF
add mapped point mem[1][13]/q mem_reg[1][13]/Q -type DFF DFF
add mapped point mem[1][14]/q mem_reg[1][14]/Q -type DFF DFF
add mapped point mem[1][15]/q mem_reg[1][15]/Q -type DFF DFF
add mapped point mem[1][16]/q mem_reg[1][16]/Q -type DFF DFF
add mapped point mem[1][17]/q mem_reg[1][17]/Q -type DFF DFF
add mapped point mem[1][18]/q mem_reg[1][18]/Q -type DFF DFF
add mapped point mem[9][19]/q mem_reg[9][19]/Q -type DFF DFF
add mapped point mem[1][19]/q mem_reg[1][19]/Q -type DFF DFF
add mapped point mem[1][20]/q mem_reg[1][20]/Q -type DFF DFF
add mapped point mem[1][21]/q mem_reg[1][21]/Q -type DFF DFF
add mapped point mem[9][16]/q mem_reg[9][16]/Q -type DFF DFF
add mapped point mem[1][22]/q mem_reg[1][22]/Q -type DFF DFF
add mapped point mem[1][23]/q mem_reg[1][23]/Q -type DFF DFF
add mapped point mem[1][24]/q mem_reg[1][24]/Q -type DFF DFF
add mapped point mem[9][13]/q mem_reg[9][13]/Q -type DFF DFF
add mapped point mem[1][25]/q mem_reg[1][25]/Q -type DFF DFF
add mapped point mem[1][26]/q mem_reg[1][26]/Q -type DFF DFF
add mapped point mem[1][27]/q mem_reg[1][27]/Q -type DFF DFF
add mapped point mem[1][28]/q mem_reg[1][28]/Q -type DFF DFF
add mapped point mem[1][29]/q mem_reg[1][29]/Q -type DFF DFF
add mapped point mem[1][30]/q mem_reg[1][30]/Q -type DFF DFF
add mapped point mem[1][31]/q mem_reg[1][31]/Q -type DFF DFF
add mapped point mem[9][7]/q mem_reg[9][7]/Q -type DFF DFF
add mapped point mem[2][0]/q mem_reg[2][0]/Q -type DFF DFF
add mapped point mem[2][1]/q mem_reg[2][1]/Q -type DFF DFF
add mapped point mem[2][2]/q mem_reg[2][2]/Q -type DFF DFF
add mapped point mem[9][3]/q mem_reg[9][3]/Q -type DFF DFF
add mapped point mem[2][3]/q mem_reg[2][3]/Q -type DFF DFF
add mapped point mem[2][4]/q mem_reg[2][4]/Q -type DFF DFF
add mapped point mem[2][5]/q mem_reg[2][5]/Q -type DFF DFF
add mapped point mem[8][31]/q mem_reg[8][31]/Q -type DFF DFF
add mapped point mem[2][6]/q mem_reg[2][6]/Q -type DFF DFF
add mapped point mem[2][7]/q mem_reg[2][7]/Q -type DFF DFF
add mapped point mem[2][8]/q mem_reg[2][8]/Q -type DFF DFF
add mapped point mem[2][9]/q mem_reg[2][9]/Q -type DFF DFF
add mapped point mem[2][10]/q mem_reg[2][10]/Q -type DFF DFF
add mapped point mem[2][11]/q mem_reg[2][11]/Q -type DFF DFF
add mapped point mem[2][12]/q mem_reg[2][12]/Q -type DFF DFF
add mapped point mem[8][23]/q mem_reg[8][23]/Q -type DFF DFF
add mapped point mem[2][13]/q mem_reg[2][13]/Q -type DFF DFF
add mapped point mem[2][14]/q mem_reg[2][14]/Q -type DFF DFF
add mapped point mem[2][15]/q mem_reg[2][15]/Q -type DFF DFF
add mapped point mem[8][19]/q mem_reg[8][19]/Q -type DFF DFF
add mapped point mem[2][16]/q mem_reg[2][16]/Q -type DFF DFF
add mapped point mem[2][17]/q mem_reg[2][17]/Q -type DFF DFF
add mapped point mem[2][18]/q mem_reg[2][18]/Q -type DFF DFF
add mapped point mem[8][15]/q mem_reg[8][15]/Q -type DFF DFF
add mapped point mem[2][19]/q mem_reg[2][19]/Q -type DFF DFF
add mapped point mem[4][7]/q mem_reg[4][7]/Q -type DFF DFF
add mapped point mem[2][21]/q mem_reg[2][21]/Q -type DFF DFF
add mapped point mem[2][22]/q mem_reg[2][22]/Q -type DFF DFF
add mapped point mem[2][23]/q mem_reg[2][23]/Q -type DFF DFF
add mapped point mem[2][24]/q mem_reg[2][24]/Q -type DFF DFF
add mapped point mem[2][25]/q mem_reg[2][25]/Q -type DFF DFF
add mapped point mem[8][7]/q mem_reg[8][7]/Q -type DFF DFF
add mapped point mem[2][26]/q mem_reg[2][26]/Q -type DFF DFF
add mapped point mem[2][27]/q mem_reg[2][27]/Q -type DFF DFF
add mapped point mem[2][28]/q mem_reg[2][28]/Q -type DFF DFF
add mapped point mem[8][3]/q mem_reg[8][3]/Q -type DFF DFF
add mapped point mem[2][29]/q mem_reg[2][29]/Q -type DFF DFF
add mapped point mem[2][30]/q mem_reg[2][30]/Q -type DFF DFF
add mapped point mem[2][31]/q mem_reg[2][31]/Q -type DFF DFF
add mapped point mem[7][31]/q mem_reg[7][31]/Q -type DFF DFF
add mapped point mem[5][29]/q mem_reg[5][29]/Q -type DFF DFF
add mapped point mem[5][30]/q mem_reg[5][30]/Q -type DFF DFF
add mapped point mem[5][31]/q mem_reg[5][31]/Q -type DFF DFF
add mapped point mem[6][0]/q mem_reg[6][0]/Q -type DFF DFF
add mapped point mem[6][1]/q mem_reg[6][1]/Q -type DFF DFF
add mapped point mem[6][2]/q mem_reg[6][2]/Q -type DFF DFF
add mapped point mem[6][3]/q mem_reg[6][3]/Q -type DFF DFF
add mapped point mem[7][23]/q mem_reg[7][23]/Q -type DFF DFF
add mapped point mem[6][4]/q mem_reg[6][4]/Q -type DFF DFF
add mapped point mem[6][5]/q mem_reg[6][5]/Q -type DFF DFF
add mapped point mem[6][6]/q mem_reg[6][6]/Q -type DFF DFF
add mapped point mem[7][19]/q mem_reg[7][19]/Q -type DFF DFF
add mapped point mem[6][7]/q mem_reg[6][7]/Q -type DFF DFF
add mapped point mem[6][8]/q mem_reg[6][8]/Q -type DFF DFF
add mapped point mem[6][9]/q mem_reg[6][9]/Q -type DFF DFF
add mapped point mem[7][15]/q mem_reg[7][15]/Q -type DFF DFF
add mapped point mem[6][10]/q mem_reg[6][10]/Q -type DFF DFF
add mapped point mem[6][11]/q mem_reg[6][11]/Q -type DFF DFF
add mapped point mem[6][12]/q mem_reg[6][12]/Q -type DFF DFF
add mapped point mem[6][13]/q mem_reg[6][13]/Q -type DFF DFF
add mapped point mem[6][14]/q mem_reg[6][14]/Q -type DFF DFF
add mapped point mem[6][15]/q mem_reg[6][15]/Q -type DFF DFF
add mapped point mem[6][16]/q mem_reg[6][16]/Q -type DFF DFF
add mapped point mem[7][7]/q mem_reg[7][7]/Q -type DFF DFF
add mapped point mem[6][17]/q mem_reg[6][17]/Q -type DFF DFF
add mapped point mem[6][18]/q mem_reg[6][18]/Q -type DFF DFF
add mapped point mem[6][19]/q mem_reg[6][19]/Q -type DFF DFF
add mapped point mem[7][3]/q mem_reg[7][3]/Q -type DFF DFF
add mapped point mem[6][20]/q mem_reg[6][20]/Q -type DFF DFF
add mapped point mem[6][21]/q mem_reg[6][21]/Q -type DFF DFF
add mapped point mem[6][22]/q mem_reg[6][22]/Q -type DFF DFF
add mapped point mem[6][23]/q mem_reg[6][23]/Q -type DFF DFF
add mapped point mem[6][24]/q mem_reg[6][24]/Q -type DFF DFF
add mapped point mem[6][25]/q mem_reg[6][25]/Q -type DFF DFF
add mapped point mem[6][26]/q mem_reg[6][26]/Q -type DFF DFF
add mapped point mem[6][27]/q mem_reg[6][27]/Q -type DFF DFF
add mapped point mem[6][28]/q mem_reg[6][28]/Q -type DFF DFF
add mapped point mem[6][29]/q mem_reg[6][29]/Q -type DFF DFF
add mapped point mem[6][30]/q mem_reg[6][30]/Q -type DFF DFF
add mapped point mem[6][31]/q mem_reg[6][31]/Q -type DFF DFF
add mapped point mem[7][0]/q mem_reg[7][0]/Q -type DFF DFF
add mapped point mem[7][1]/q mem_reg[7][1]/Q -type DFF DFF
add mapped point mem[7][2]/q mem_reg[7][2]/Q -type DFF DFF
add mapped point mem[7][4]/q mem_reg[7][4]/Q -type DFF DFF
add mapped point mem[7][5]/q mem_reg[7][5]/Q -type DFF DFF
add mapped point mem[7][6]/q mem_reg[7][6]/Q -type DFF DFF
add mapped point mem[7][8]/q mem_reg[7][8]/Q -type DFF DFF
add mapped point mem[7][9]/q mem_reg[7][9]/Q -type DFF DFF
add mapped point mem[7][10]/q mem_reg[7][10]/Q -type DFF DFF
add mapped point mem[7][11]/q mem_reg[7][11]/Q -type DFF DFF
add mapped point mem[7][12]/q mem_reg[7][12]/Q -type DFF DFF
add mapped point mem[7][13]/q mem_reg[7][13]/Q -type DFF DFF
add mapped point mem[7][14]/q mem_reg[7][14]/Q -type DFF DFF
add mapped point mem[7][16]/q mem_reg[7][16]/Q -type DFF DFF
add mapped point mem[7][17]/q mem_reg[7][17]/Q -type DFF DFF
add mapped point mem[7][18]/q mem_reg[7][18]/Q -type DFF DFF
add mapped point mem[7][20]/q mem_reg[7][20]/Q -type DFF DFF
add mapped point mem[7][21]/q mem_reg[7][21]/Q -type DFF DFF
add mapped point mem[7][22]/q mem_reg[7][22]/Q -type DFF DFF
add mapped point mem[7][24]/q mem_reg[7][24]/Q -type DFF DFF
add mapped point mem[7][25]/q mem_reg[7][25]/Q -type DFF DFF
add mapped point mem[7][26]/q mem_reg[7][26]/Q -type DFF DFF
add mapped point mem[7][27]/q mem_reg[7][27]/Q -type DFF DFF
add mapped point mem[7][28]/q mem_reg[7][28]/Q -type DFF DFF
add mapped point mem[7][29]/q mem_reg[7][29]/Q -type DFF DFF
add mapped point mem[7][30]/q mem_reg[7][30]/Q -type DFF DFF
add mapped point mem[8][0]/q mem_reg[8][0]/Q -type DFF DFF
add mapped point mem[8][1]/q mem_reg[8][1]/Q -type DFF DFF
add mapped point mem[8][2]/q mem_reg[8][2]/Q -type DFF DFF
add mapped point mem[8][4]/q mem_reg[8][4]/Q -type DFF DFF
add mapped point mem[8][5]/q mem_reg[8][5]/Q -type DFF DFF
add mapped point mem[8][6]/q mem_reg[8][6]/Q -type DFF DFF
add mapped point mem[8][8]/q mem_reg[8][8]/Q -type DFF DFF
add mapped point mem[3][20]/q mem_reg[3][20]/Q -type DFF DFF
add mapped point mem[8][10]/q mem_reg[8][10]/Q -type DFF DFF
add mapped point mem[8][11]/q mem_reg[8][11]/Q -type DFF DFF
add mapped point mem[8][12]/q mem_reg[8][12]/Q -type DFF DFF
add mapped point mem[8][13]/q mem_reg[8][13]/Q -type DFF DFF
add mapped point mem[8][14]/q mem_reg[8][14]/Q -type DFF DFF
add mapped point mem[8][16]/q mem_reg[8][16]/Q -type DFF DFF
add mapped point mem[8][17]/q mem_reg[8][17]/Q -type DFF DFF
add mapped point mem[8][18]/q mem_reg[8][18]/Q -type DFF DFF
add mapped point mem[8][20]/q mem_reg[8][20]/Q -type DFF DFF
add mapped point mem[8][21]/q mem_reg[8][21]/Q -type DFF DFF
add mapped point mem[8][22]/q mem_reg[8][22]/Q -type DFF DFF
add mapped point mem[8][24]/q mem_reg[8][24]/Q -type DFF DFF
add mapped point mem[8][25]/q mem_reg[8][25]/Q -type DFF DFF
add mapped point mem[8][26]/q mem_reg[8][26]/Q -type DFF DFF
add mapped point mem[8][27]/q mem_reg[8][27]/Q -type DFF DFF
add mapped point mem[8][28]/q mem_reg[8][28]/Q -type DFF DFF
add mapped point mem[8][29]/q mem_reg[8][29]/Q -type DFF DFF
add mapped point mem[8][30]/q mem_reg[8][30]/Q -type DFF DFF
add mapped point mem[9][0]/q mem_reg[9][0]/Q -type DFF DFF
add mapped point mem[9][1]/q mem_reg[9][1]/Q -type DFF DFF
add mapped point mem[9][2]/q mem_reg[9][2]/Q -type DFF DFF
add mapped point mem[9][4]/q mem_reg[9][4]/Q -type DFF DFF
add mapped point mem[9][5]/q mem_reg[9][5]/Q -type DFF DFF
add mapped point mem[9][6]/q mem_reg[9][6]/Q -type DFF DFF
add mapped point mem[9][8]/q mem_reg[9][8]/Q -type DFF DFF
add mapped point mem[9][9]/q mem_reg[9][9]/Q -type DFF DFF
add mapped point mem[9][10]/q mem_reg[9][10]/Q -type DFF DFF
add mapped point mem[0][0]/q mem_reg[0][0]/Q -type DFF DFF
add mapped point mem[0][1]/q mem_reg[0][1]/Q -type DFF DFF
add mapped point mem[9][11]/q mem_reg[9][11]/Q -type DFF DFF
add mapped point mem[9][12]/q mem_reg[9][12]/Q -type DFF DFF
add mapped point mem[9][14]/q mem_reg[9][14]/Q -type DFF DFF
add mapped point mem[0][2]/q mem_reg[0][2]/Q -type DFF DFF
add mapped point mem[9][15]/q mem_reg[9][15]/Q -type DFF DFF
add mapped point mem[9][17]/q mem_reg[9][17]/Q -type DFF DFF
add mapped point mem[9][18]/q mem_reg[9][18]/Q -type DFF DFF
add mapped point mem[0][3]/q mem_reg[0][3]/Q -type DFF DFF
add mapped point mem[4][31]/q mem_reg[4][31]/Q -type DFF DFF
add mapped point mem[9][20]/q mem_reg[9][20]/Q -type DFF DFF
add mapped point mem[9][21]/q mem_reg[9][21]/Q -type DFF DFF
add mapped point mem[9][22]/q mem_reg[9][22]/Q -type DFF DFF
add mapped point mem[0][4]/q mem_reg[0][4]/Q -type DFF DFF
add mapped point mem[9][23]/q mem_reg[9][23]/Q -type DFF DFF
add mapped point mem[0][14]/q mem_reg[0][14]/Q -type DFF DFF
add mapped point mem[10][15]/q mem_reg[10][15]/Q -type DFF DFF
add mapped point mem[0][15]/q mem_reg[0][15]/Q -type DFF DFF
add mapped point mem[10][17]/q mem_reg[10][17]/Q -type DFF DFF
add mapped point mem[10][18]/q mem_reg[10][18]/Q -type DFF DFF
add mapped point mem[10][19]/q mem_reg[10][19]/Q -type DFF DFF
add mapped point mem[10][20]/q mem_reg[10][20]/Q -type DFF DFF
add mapped point mem[10][21]/q mem_reg[10][21]/Q -type DFF DFF
add mapped point mem[0][17]/q mem_reg[0][17]/Q -type DFF DFF
add mapped point mem[10][23]/q mem_reg[10][23]/Q -type DFF DFF
add mapped point mem[10][24]/q mem_reg[10][24]/Q -type DFF DFF
add mapped point mem[0][18]/q mem_reg[0][18]/Q -type DFF DFF
add mapped point mem[10][25]/q mem_reg[10][25]/Q -type DFF DFF
add mapped point mem[10][26]/q mem_reg[10][26]/Q -type DFF DFF
add mapped point mem[0][19]/q mem_reg[0][19]/Q -type DFF DFF
add mapped point mem[0][21]/q mem_reg[0][21]/Q -type DFF DFF
add mapped point mem[10][27]/q mem_reg[10][27]/Q -type DFF DFF
add mapped point mem[10][28]/q mem_reg[10][28]/Q -type DFF DFF
add mapped point mem[10][30]/q mem_reg[10][30]/Q -type DFF DFF
add mapped point mem[10][31]/q mem_reg[10][31]/Q -type DFF DFF
add mapped point mem[0][22]/q mem_reg[0][22]/Q -type DFF DFF
add mapped point mem[0][24]/q mem_reg[0][24]/Q -type DFF DFF
add mapped point mem[0][25]/q mem_reg[0][25]/Q -type DFF DFF
add mapped point mem[0][26]/q mem_reg[0][26]/Q -type DFF DFF
add mapped point mem[0][27]/q mem_reg[0][27]/Q -type DFF DFF
add mapped point mem[0][28]/q mem_reg[0][28]/Q -type DFF DFF
add mapped point mem[0][29]/q mem_reg[0][29]/Q -type DFF DFF
add mapped point mem[0][30]/q mem_reg[0][30]/Q -type DFF DFF
add mapped point mem[3][0]/q mem_reg[3][0]/Q -type DFF DFF
add mapped point mem[3][1]/q mem_reg[3][1]/Q -type DFF DFF
add mapped point mem[3][2]/q mem_reg[3][2]/Q -type DFF DFF
add mapped point mem[3][4]/q mem_reg[3][4]/Q -type DFF DFF
add mapped point mem[3][5]/q mem_reg[3][5]/Q -type DFF DFF
add mapped point mem[3][6]/q mem_reg[3][6]/Q -type DFF DFF
add mapped point mem[3][8]/q mem_reg[3][8]/Q -type DFF DFF
add mapped point mem[3][9]/q mem_reg[3][9]/Q -type DFF DFF
add mapped point mem[3][10]/q mem_reg[3][10]/Q -type DFF DFF
add mapped point mem[3][11]/q mem_reg[3][11]/Q -type DFF DFF
add mapped point mem[3][12]/q mem_reg[3][12]/Q -type DFF DFF
add mapped point mem[3][13]/q mem_reg[3][13]/Q -type DFF DFF
add mapped point mem[3][14]/q mem_reg[3][14]/Q -type DFF DFF
add mapped point mem[3][16]/q mem_reg[3][16]/Q -type DFF DFF
add mapped point mem[3][17]/q mem_reg[3][17]/Q -type DFF DFF
add mapped point mem[3][18]/q mem_reg[3][18]/Q -type DFF DFF
add mapped point mem[8][9]/q mem_reg[8][9]/Q -type DFF DFF
add mapped point mem[3][21]/q mem_reg[3][21]/Q -type DFF DFF
add mapped point mem[3][22]/q mem_reg[3][22]/Q -type DFF DFF
add mapped point mem[3][24]/q mem_reg[3][24]/Q -type DFF DFF
add mapped point mem[3][25]/q mem_reg[3][25]/Q -type DFF DFF
add mapped point mem[3][26]/q mem_reg[3][26]/Q -type DFF DFF
add mapped point mem[3][27]/q mem_reg[3][27]/Q -type DFF DFF
add mapped point mem[3][28]/q mem_reg[3][28]/Q -type DFF DFF
add mapped point mem[3][29]/q mem_reg[3][29]/Q -type DFF DFF
add mapped point mem[3][30]/q mem_reg[3][30]/Q -type DFF DFF
add mapped point mem[4][0]/q mem_reg[4][0]/Q -type DFF DFF
add mapped point mem[4][1]/q mem_reg[4][1]/Q -type DFF DFF
add mapped point mem[4][2]/q mem_reg[4][2]/Q -type DFF DFF
add mapped point mem[4][4]/q mem_reg[4][4]/Q -type DFF DFF
add mapped point mem[4][5]/q mem_reg[4][5]/Q -type DFF DFF
add mapped point mem[4][6]/q mem_reg[4][6]/Q -type DFF DFF
add mapped point mem[4][8]/q mem_reg[4][8]/Q -type DFF DFF
add mapped point mem[4][9]/q mem_reg[4][9]/Q -type DFF DFF
add mapped point mem[4][10]/q mem_reg[4][10]/Q -type DFF DFF
add mapped point mem[4][11]/q mem_reg[4][11]/Q -type DFF DFF
add mapped point mem[4][12]/q mem_reg[4][12]/Q -type DFF DFF
add mapped point mem[4][13]/q mem_reg[4][13]/Q -type DFF DFF
add mapped point mem[4][14]/q mem_reg[4][14]/Q -type DFF DFF
add mapped point mem[4][16]/q mem_reg[4][16]/Q -type DFF DFF
add mapped point mem[4][17]/q mem_reg[4][17]/Q -type DFF DFF
add mapped point mem[4][18]/q mem_reg[4][18]/Q -type DFF DFF
add mapped point mem[4][20]/q mem_reg[4][20]/Q -type DFF DFF
add mapped point mem[4][21]/q mem_reg[4][21]/Q -type DFF DFF
add mapped point mem[4][22]/q mem_reg[4][22]/Q -type DFF DFF
add mapped point mem[4][24]/q mem_reg[4][24]/Q -type DFF DFF
add mapped point mem[4][25]/q mem_reg[4][25]/Q -type DFF DFF
add mapped point mem[4][26]/q mem_reg[4][26]/Q -type DFF DFF
add mapped point mem[4][27]/q mem_reg[4][27]/Q -type DFF DFF
add mapped point mem[4][28]/q mem_reg[4][28]/Q -type DFF DFF
add mapped point mem[4][29]/q mem_reg[4][29]/Q -type DFF DFF
add mapped point mem[4][30]/q mem_reg[4][30]/Q -type DFF DFF
add mapped point mem[5][0]/q mem_reg[5][0]/Q -type DFF DFF
add mapped point mem[5][1]/q mem_reg[5][1]/Q -type DFF DFF
add mapped point mem[5][2]/q mem_reg[5][2]/Q -type DFF DFF
add mapped point mem[5][4]/q mem_reg[5][4]/Q -type DFF DFF
add mapped point mem[5][5]/q mem_reg[5][5]/Q -type DFF DFF
add mapped point mem[5][6]/q mem_reg[5][6]/Q -type DFF DFF
add mapped point mem[5][8]/q mem_reg[5][8]/Q -type DFF DFF
add mapped point mem[5][9]/q mem_reg[5][9]/Q -type DFF DFF
add mapped point mem[5][10]/q mem_reg[5][10]/Q -type DFF DFF
add mapped point mem[5][11]/q mem_reg[5][11]/Q -type DFF DFF
add mapped point mem[5][12]/q mem_reg[5][12]/Q -type DFF DFF
add mapped point mem[5][13]/q mem_reg[5][13]/Q -type DFF DFF
add mapped point mem[5][14]/q mem_reg[5][14]/Q -type DFF DFF
add mapped point mem[5][16]/q mem_reg[5][16]/Q -type DFF DFF
add mapped point mem[5][17]/q mem_reg[5][17]/Q -type DFF DFF
add mapped point mem[5][18]/q mem_reg[5][18]/Q -type DFF DFF
add mapped point mem[5][20]/q mem_reg[5][20]/Q -type DFF DFF
add mapped point mem[5][21]/q mem_reg[5][21]/Q -type DFF DFF
add mapped point mem[5][22]/q mem_reg[5][22]/Q -type DFF DFF
add mapped point mem[5][24]/q mem_reg[5][24]/Q -type DFF DFF
add mapped point mem[5][25]/q mem_reg[5][25]/Q -type DFF DFF
add mapped point mem[5][26]/q mem_reg[5][26]/Q -type DFF DFF
add mapped point mem[5][27]/q mem_reg[5][27]/Q -type DFF DFF
add mapped point mem[5][28]/q mem_reg[5][28]/Q -type DFF DFF
add mapped point mem[9][24]/q mem_reg[9][24]/Q -type DFF DFF
add mapped point mem[0][5]/q mem_reg[0][5]/Q -type DFF DFF
add mapped point mem[9][26]/q mem_reg[9][26]/Q -type DFF DFF
add mapped point mem[0][6]/q mem_reg[0][6]/Q -type DFF DFF
add mapped point mem[0][7]/q mem_reg[0][7]/Q -type DFF DFF
add mapped point mem[9][27]/q mem_reg[9][27]/Q -type DFF DFF
add mapped point mem[9][28]/q mem_reg[9][28]/Q -type DFF DFF
add mapped point mem[9][29]/q mem_reg[9][29]/Q -type DFF DFF
add mapped point mem[9][31]/q mem_reg[9][31]/Q -type DFF DFF
add mapped point mem[10][0]/q mem_reg[10][0]/Q -type DFF DFF
add mapped point mem[10][1]/q mem_reg[10][1]/Q -type DFF DFF
add mapped point mem[10][2]/q mem_reg[10][2]/Q -type DFF DFF
add mapped point mem[0][9]/q mem_reg[0][9]/Q -type DFF DFF
add mapped point mem[0][10]/q mem_reg[0][10]/Q -type DFF DFF
add mapped point mem[10][3]/q mem_reg[10][3]/Q -type DFF DFF
add mapped point mem[10][5]/q mem_reg[10][5]/Q -type DFF DFF
add mapped point mem[10][6]/q mem_reg[10][6]/Q -type DFF DFF
add mapped point mem[0][11]/q mem_reg[0][11]/Q -type DFF DFF
add mapped point mem[10][8]/q mem_reg[10][8]/Q -type DFF DFF
add mapped point mem[10][9]/q mem_reg[10][9]/Q -type DFF DFF
add mapped point mem[10][10]/q mem_reg[10][10]/Q -type DFF DFF
add mapped point mem[0][13]/q mem_reg[0][13]/Q -type DFF DFF
add mapped point mem[10][11]/q mem_reg[10][11]/Q -type DFF DFF
add mapped point mem[10][12]/q mem_reg[10][12]/Q -type DFF DFF
add mapped point mem[10][13]/q mem_reg[10][13]/Q -type DFF DFF
add mapped point mem[10][14]/q mem_reg[10][14]/Q -type DFF DFF
add mapped point mem[4][3]/q mem_reg[4][3]/Q -type DFF DFF
add mapped point mem[5][3]/q mem_reg[5][3]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
