
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun  9 2026 10:43:41 IST (Jun  9 2026 05:13:41 UTC)

// Verification Directory fv/mome 

module mome(clk, rst, din, dout);
  input clk, rst, din;
  output dout;
  wire clk, rst, din;
  wire dout;
  assign dout = 1'b0;
endmodule

