/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Wed Jun 24 10:27:50 2026
#  Design:            mealy
#  Command:           saveNetlist mealy_phy_netlist.v
###############################################################
*/
module mealy (
	clk, 
	rst, 
	din, 
	dout_1001, 
	dout_1100, 
	dout_1101);
   input clk;
   input rst;
   input din;
   output dout_1001;
   output dout_1100;
   output dout_1101;

   // Internal wires
   wire FE_DBTN2_state_2;
   wire FE_DBTN1_state_1;
   wire FE_DBTN0_state_0;
   wire [2:0] state;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire n_0;
   wire n_1;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;

   INVX1 FE_DBTC2_state_2 (.A(state[2]),
	.Y(FE_DBTN2_state_2));
   CLKINVX2 FE_DBTC1_state_1 (.A(state[1]),
	.Y(FE_DBTN1_state_1));
   CLKINVX1 FE_DBTC0_state_0 (.A(state[0]),
	.Y(FE_DBTN0_state_0));
   DFFRHQX1 dout_1101_reg (.CK(clk),
	.D(n_12),
	.Q(dout_1101),
	.RN(n_15));
   AOI21X1 g708__2398 (.A0(state[2]),
	.A1(n_3),
	.B0(n_7),
	.Y(n_14));
   OAI21XL g710__5107 (.A0(n_4),
	.A1(n_1),
	.B0(n_5),
	.Y(n_13));
   DFFRHQX4 \state_reg[1]  (.CK(clk),
	.D(n_11),
	.Q(state[1]),
	.RN(n_15));
   AOI21X1 g709__6260 (.A0(FE_DBTN0_state_0),
	.A1(n_0),
	.B0(FE_DBTN2_state_2),
	.Y(n_12));
   NOR3X1 g711__4319 (.A(state[2]),
	.B(state[1]),
	.C(FE_DBTN0_state_0),
	.Y(n_11));
   NOR3X2 g712__8428 (.A(din),
	.B(FE_DBTN1_state_1),
	.C(state[2]),
	.Y(n_9));
   NOR4X1 g713__5526 (.A(n_7),
	.B(state[0]),
	.C(state[1]),
	.D(FE_DBTN2_state_2),
	.Y(n_8));
   NAND4X1 g714__6783 (.A(state[1]),
	.B(din),
	.C(state[0]),
	.D(FE_DBTN2_state_2),
	.Y(n_5));
   NAND2XL g715__3680 (.A(n_7),
	.B(FE_DBTN0_state_0),
	.Y(n_4));
   NAND2X1 g717__1617 (.A(FE_DBTN0_state_0),
	.B(FE_DBTN1_state_1),
	.Y(n_3));
   NAND2XL g718__2802 (.A(state[2]),
	.B(FE_DBTN1_state_1),
	.Y(n_1));
   NOR2X1 g716__1705 (.A(din),
	.B(state[1]),
	.Y(n_0));
   CLKINVX1 g722 (.A(din),
	.Y(n_7));
   INVXL g719 (.A(rst),
	.Y(n_15));
   DFFRX4 \state_reg[0]  (.CK(clk),
	.D(n_14),
	.Q(state[0]),
	.QN(UNCONNECTED),
	.RN(n_15));
   DFFRHQX4 \state_reg[2]  (.CK(clk),
	.D(n_9),
	.Q(state[2]),
	.RN(n_15));
   DFFRXL dout_1001_reg (.CK(clk),
	.D(n_8),
	.Q(dout_1001),
	.QN(UNCONNECTED0),
	.RN(n_15));
   DFFRX2 dout_1100_reg (.CK(clk),
	.D(n_13),
	.Q(dout_1100),
	.QN(UNCONNECTED1),
	.RN(n_15));
endmodule

