/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Wed Jun 24 13:40:59 2026
#  Design:            TrafficLight
#  Command:           saveNetlist TrafficLight_physical_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 24 2026 13:21:04 IST (Jun 24 2026 07:51:04 UTC)
// Verification Directory fv/TrafficLight 
module TrafficLight (
	clk, 
	rst, 
	LED_NS, 
	LED_WE);
   input clk;
   input rst;
   output [2:0] LED_NS;
   output [2:0] LED_WE;

   // Internal wires
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_RN_3_0;
   wire FE_OCPN17_n_269;
   wire FE_OCPN16_state_0;
   wire FE_OCPN15_count_1;
   wire FE_OCPN14_n_1421;
   wire FE_OCPN13_n_937;
   wire FE_OCPN12_FE_DBTN1_state_2;
   wire FE_OCPN11_n_1567;
   wire FE_OCPN10_FE_DBTN3_state_5;
   wire FE_OCPN9_n_1565;
   wire FE_OCPN8_state_3;
   wire FE_OCPN7_n_1564;
   wire FE_OCPN6_n_404;
   wire FE_OCPN5_n_1569;
   wire FE_RN_1;
   wire FE_OCPN7_n_88;
   wire FE_OCPN6_n_88;
   wire FE_OCPN5_n_88;
   wire FE_OCPN3_n_88;
   wire FE_OCPN2_n_88;
   wire FE_OCPN1_n_1875;
   wire FE_RN_0_0;
   wire FE_OFN0_n_88;
   wire FE_DBTN3_state_5;
   wire FE_DBTN2_state_4;
   wire FE_DBTN1_state_2;
   wire FE_DBTN0_n_88;
   wire [3:0] count;
   wire [5:0] state;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire n_19;
   wire n_20;
   wire n_44;
   wire n_45;
   wire n_52;
   wire n_53;
   wire n_57;
   wire n_71;
   wire n_85;
   wire n_88;
   wire n_91;
   wire n_229;
   wire n_231;
   wire n_269;
   wire n_394;
   wire n_404;
   wire n_424;
   wire n_426;
   wire n_428;
   wire n_438;
   wire n_480;
   wire n_522;
   wire n_717;
   wire n_719;
   wire n_820;
   wire n_821;
   wire n_904;
   wire n_926;
   wire n_927;
   wire n_936;
   wire n_937;
   wire n_948;
   wire n_979;
   wire n_990;
   wire n_1263;
   wire n_1264;
   wire n_1315;
   wire n_1316;
   wire n_1318;
   wire n_1331;
   wire n_1332;
   wire n_1333;
   wire n_1350;
   wire n_1351;
   wire n_1359;
   wire n_1372;
   wire n_1373;
   wire n_1375;
   wire n_1381;
   wire n_1404;
   wire n_1408;
   wire n_1415;
   wire n_1417;
   wire n_1418;
   wire n_1419;
   wire n_1420;
   wire n_1421;
   wire n_1536;
   wire n_1562;
   wire n_1563;
   wire n_1564;
   wire n_1565;
   wire n_1566;
   wire n_1567;
   wire n_1568;
   wire n_1569;
   wire n_1571;
   wire n_1583;
   wire n_1585;
   wire n_1586;
   wire n_1587;
   wire n_1591;
   wire n_1637;
   wire n_1638;
   wire n_1640;
   wire n_1642;
   wire n_1643;
   wire n_1644;
   wire n_1646;
   wire n_1647;
   wire n_1648;
   wire n_1650;
   wire n_1652;
   wire n_1653;
   wire n_1824;
   wire n_1825;
   wire n_1826;
   wire n_1866;
   wire n_1867;
   wire n_1868;
   wire n_1869;
   wire n_1872;
   wire n_1875;
   wire n_1876;
   wire n_1886;
   wire n_1888;
   wire n_1889;
   wire n_1890;

   INVX4 FE_RC_12_0 (.A(state[2]),
	.Y(FE_DBTN1_state_2));
   CLKINVX1 FE_RC_11_0 (.A(n_428),
	.Y(FE_RN_4_0));
   CLKAND2X2 FE_RC_10_0 (.A(FE_RN_4_0),
	.B(n_426),
	.Y(FE_RN_5_0));
   NAND2X2 FE_RC_9_0 (.A(FE_OCPN7_n_1564),
	.B(FE_RN_5_0),
	.Y(n_1643));
   OR2X1 FE_RC_8_0 (.A(n_1583),
	.B(n_1652),
	.Y(FE_RN_3_0));
   NAND2X2 FE_RC_7_0 (.A(FE_RN_3_0),
	.B(FE_OCPN2_n_88),
	.Y(n_1585));
   CLKBUFX2 FE_OCPC17_n_269 (.A(n_269),
	.Y(FE_OCPN17_n_269));
   CLKBUFX2 FE_OCPC16_state_0 (.A(state[0]),
	.Y(FE_OCPN16_state_0));
   CLKBUFX2 FE_OCPC15_count_1 (.A(count[1]),
	.Y(FE_OCPN15_count_1));
   BUFX2 FE_OCPC14_n_1421 (.A(n_1421),
	.Y(FE_OCPN14_n_1421));
   CLKBUFX2 FE_OCPC13_n_937 (.A(n_937),
	.Y(FE_OCPN13_n_937));
   CLKBUFX2 FE_OCPC12_FE_DBTN1_state_2 (.A(FE_DBTN1_state_2),
	.Y(FE_OCPN12_FE_DBTN1_state_2));
   CLKBUFX2 FE_OCPC11_n_1567 (.A(n_1567),
	.Y(FE_OCPN11_n_1567));
   CLKBUFX2 FE_OCPC10_FE_DBTN3_state_5 (.A(FE_DBTN3_state_5),
	.Y(FE_OCPN10_FE_DBTN3_state_5));
   BUFX3 FE_OCPC9_n_1565 (.A(n_1565),
	.Y(FE_OCPN9_n_1565));
   CLKBUFX2 FE_OCPC8_state_3 (.A(state[3]),
	.Y(FE_OCPN8_state_3));
   CLKBUFX2 FE_OCPC7_n_1564 (.A(n_1564),
	.Y(FE_OCPN7_n_1564));
   CLKBUFX2 FE_OCPC6_n_404 (.A(n_404),
	.Y(FE_OCPN6_n_404));
   CLKBUFX2 FE_OCPC5_n_1569 (.A(n_1569),
	.Y(FE_OCPN5_n_1569));
   NAND2X1 g169_dup (.A(state[4]),
	.B(n_979),
	.Y(FE_RN_1));
   OAI21X1 FE_RC_6_0 (.A0(n_1331),
	.A1(n_1888),
	.B0(n_1332),
	.Y(n_1333));
   OAI21X1 FE_RC_5_0 (.A0(n_1646),
	.A1(n_1886),
	.B0(n_1647),
	.Y(n_1648));
   INVX1 FE_OCPC11_n_88 (.A(FE_OFN0_n_88),
	.Y(FE_OCPN7_n_88));
   INVX1 FE_OCPC10_n_88 (.A(FE_OFN0_n_88),
	.Y(FE_OCPN6_n_88));
   INVX1 FE_OCPC9_n_88 (.A(FE_OFN0_n_88),
	.Y(FE_OCPN5_n_88));
   CLKINVX2 FE_OCPC8_n_88 (.A(FE_OFN0_n_88),
	.Y(FE_OCPN3_n_88));
   INVX1 FE_OCPC7_n_88 (.A(n_88),
	.Y(FE_OCPN2_n_88));
   CLKINVX6 FE_OCPC6_n_88 (.A(n_88),
	.Y(FE_OFN0_n_88));
   BUFX2 FE_OCPC5_n_88 (.A(n_88),
	.Y(FE_DBTN0_n_88));
   BUFX6 FE_OCPC3_n_1875 (.A(n_1875),
	.Y(FE_OCPN1_n_1875));
   NAND2X2 FE_RC_1_0 (.A(n_404),
	.B(FE_RN_1),
	.Y(FE_RN_0_0));
   NAND2X2 FE_RC_0_0 (.A(n_426),
	.B(FE_RN_0_0),
	.Y(n_438));
   INVX3 FE_OFC1_rst (.A(rst),
	.Y(n_91));
   CLKINVX4 FE_DBTC3_state_5 (.A(state[5]),
	.Y(FE_DBTN3_state_5));
   CLKINVX2 FE_DBTC2_state_4 (.A(state[4]),
	.Y(FE_DBTN2_state_4));
   DFFRHQX8 \count_reg[2]  (.CK(clk),
	.D(n_821),
	.Q(count[2]),
	.RN(n_91));
   DFFRHQX4 \count_reg[3]  (.CK(clk),
	.D(n_1648),
	.Q(count[3]),
	.RN(n_91));
   DFFRHQX4 \count_reg[1]  (.CK(clk),
	.D(n_1333),
	.Q(count[1]),
	.RN(n_91));
   DFFRHQX4 \count_reg[0]  (.CK(clk),
	.D(n_1890),
	.Q(count[0]),
	.RN(n_91));
   DFFRHQX4 \state_reg[2]  (.CK(clk),
	.D(n_1315),
	.Q(state[2]),
	.RN(n_91));
   DFFRHQX4 \state_reg[5]  (.CK(clk),
	.D(n_1318),
	.Q(state[5]),
	.RN(n_91));
   DFFRHQX4 \state_reg[1]  (.CK(clk),
	.D(n_1869),
	.Q(state[1]),
	.RN(n_91));
   OAI21X1 g13617__8428 (.A0(FE_OCPN3_n_88),
	.A1(n_522),
	.B0(n_71),
	.Y(n_85));
   OAI21X2 g13619__1881 (.A0(n_1653),
	.A1(FE_OCPN3_n_88),
	.B0(FE_OCPN8_state_3),
	.Y(n_71));
   TLATNXL \LED_NS_reg[2]  (.D(n_52),
	.GN(FE_DBTN0_n_88),
	.Q(LED_NS[2]),
	.QN(UNCONNECTED));
   TLATNXL \LED_WE_reg[0]  (.D(FE_OCPN13_n_937),
	.GN(FE_DBTN0_n_88),
	.Q(LED_WE[0]),
	.QN(UNCONNECTED0));
   TLATNXL \LED_NS_reg[0]  (.D(n_1417),
	.GN(FE_DBTN0_n_88),
	.Q(LED_NS[0]),
	.QN(UNCONNECTED1));
   TLATNXL \LED_NS_reg[1]  (.D(n_1415),
	.GN(FE_DBTN0_n_88),
	.Q(LED_NS[1]),
	.QN(UNCONNECTED2));
   TLATNXL \LED_WE_reg[2]  (.D(n_990),
	.GN(FE_DBTN0_n_88),
	.Q(LED_WE[2]),
	.QN(UNCONNECTED3));
   TLATNXL \LED_WE_reg[1]  (.D(n_1372),
	.GN(FE_DBTN0_n_88),
	.Q(LED_WE[1]),
	.QN(UNCONNECTED4));
   NOR2X4 g13641__6161 (.A(n_53),
	.B(n_948),
	.Y(n_88));
   AOI21X4 g13643__6417 (.A0(n_927),
	.A1(n_438),
	.B0(n_424),
	.Y(n_53));
   INVXL g13650 (.A(n_948),
	.Y(n_52));
   NOR2XL g13653__4319 (.A(count[0]),
	.B(n_44),
	.Y(n_45));
   NAND2X1 g13664__5122 (.A(n_1653),
	.B(FE_OCPN8_state_3),
	.Y(n_44));
   CLKINVX2 g13676 (.A(n_1653),
	.Y(n_57));
   OA21X1 g13674__1666 (.A0(count[0]),
	.A1(count[1]),
	.B0(n_19),
	.Y(n_20));
   NAND2X1 g13687__8246 (.A(count[0]),
	.B(count[1]),
	.Y(n_19));
   DFFRHQX4 \state_reg[4]  (.CK(clk),
	.D(n_1351),
	.Q(state[4]),
	.RN(n_91));
   XNOR2X1 g13864 (.A(count[2]),
	.B(n_19),
	.Y(n_229));
   CLKINVX1 g13865 (.A(count[2]),
	.Y(n_231));
   CLKINVX2 g13901 (.A(FE_OCPN11_n_1567),
	.Y(n_269));
   NAND2XL g126 (.A(n_44),
	.B(n_926),
	.Y(n_394));
   NAND2X2 g43 (.A(state[3]),
	.B(FE_DBTN2_state_4),
	.Y(n_404));
   CLKINVX1 g167 (.A(n_1564),
	.Y(n_424));
   NOR2X1 g165 (.A(state[2]),
	.B(state[5]),
	.Y(n_426));
   NAND2X1 g169 (.A(state[4]),
	.B(n_979),
	.Y(n_428));
   NAND2XL g30 (.A(n_88),
	.B(FE_OCPN16_state_0),
	.Y(n_480));
   NAND2BX1 g14022 (.AN(n_1568),
	.B(n_719),
	.Y(n_522));
   MX2X1 g14070 (.A(FE_OCPN1_n_1875),
	.B(n_1568),
	.S0(FE_OCPN14_n_1421),
	.Y(n_717));
   CLKINVX4 g14073 (.A(n_1421),
	.Y(n_719));
   OAI21X1 g72 (.A0(n_1264),
	.A1(n_1316),
	.B0(n_820),
	.Y(n_821));
   NAND2X2 g74 (.A(count[2]),
	.B(FE_OCPN6_n_88),
	.Y(n_820));
   AND2X6 g24 (.A(n_1563),
	.B(n_1565),
	.Y(n_904));
   OAI21XL g32 (.A0(FE_OCPN5_n_1569),
	.A1(state[4]),
	.B0(FE_OCPN14_n_1421),
	.Y(n_926));
   NAND2X2 g33 (.A(FE_OCPN9_n_1565),
	.B(n_1569),
	.Y(n_927));
   NOR3X1 g39 (.A(n_424),
	.B(FE_OCPN6_n_404),
	.C(n_936),
	.Y(n_937));
   CLKINVX1 g40 (.A(n_1408),
	.Y(n_936));
   NAND2X4 g14175 (.A(n_1872),
	.B(n_1875),
	.Y(n_948));
   INVX2 fopt (.A(state[3]),
	.Y(n_979));
   NOR2XL g14195 (.A(FE_OCPN13_n_937),
	.B(n_1372),
	.Y(n_990));
   NOR2XL g14344 (.A(n_1591),
	.B(n_1263),
	.Y(n_1264));
   NAND2X1 g14345 (.A(n_57),
	.B(FE_OCPN1_n_1875),
	.Y(n_1263));
   OAI21X1 g14367 (.A0(FE_OCPN2_n_88),
	.A1(FE_OCPN12_FE_DBTN1_state_2),
	.B0(n_717),
	.Y(n_1315));
   NAND2X2 g14368 (.A(n_229),
	.B(FE_OFN0_n_88),
	.Y(n_1316));
   OAI21X1 g13622__14370 (.A0(FE_OFN0_n_88),
	.A1(FE_OCPN10_FE_DBTN3_state_5),
	.B0(n_1375),
	.Y(n_1318));
   NOR2X1 g88 (.A(n_394),
	.B(n_1876),
	.Y(n_1331));
   NAND2X2 g89 (.A(FE_OCPN15_count_1),
	.B(FE_OCPN7_n_88),
	.Y(n_1332));
   OAI211XL g14386 (.A0(FE_OFN0_n_88),
	.A1(FE_DBTN2_state_4),
	.B0(n_1350),
	.C0(n_1373),
	.Y(n_1351));
   NAND2XL g14389 (.A(n_937),
	.B(n_57),
	.Y(n_1350));
   NOR2X1 g14397 (.A(state[0]),
	.B(n_1381),
	.Y(n_1359));
   NAND2X1 g14402 (.A(n_1372),
	.B(FE_OCPN14_n_1421),
	.Y(n_1373));
   CLKINVX2 g14403 (.A(n_1643),
	.Y(n_1372));
   MXI2X1 g14404 (.A(FE_OCPN17_n_269),
	.B(n_1372),
	.S0(n_719),
	.Y(n_1375));
   CLKINVX2 g14406 (.A(state[1]),
	.Y(n_1381));
   DFFRHQX4 \state_reg[3]  (.CK(clk),
	.D(n_85),
	.Q(state[3]),
	.RN(n_91));
   CLKAND2X3 g82 (.A(count[1]),
	.B(count[3]),
	.Y(n_1404));
   AND2X6 g81 (.A(FE_DBTN3_state_5),
	.B(FE_DBTN1_state_2),
	.Y(n_1408));
   CLKINVX1 g76 (.A(FE_OCPN1_n_1875),
	.Y(n_1415));
   INVXL g14427 (.A(n_1872),
	.Y(n_1417));
   NAND2X4 g21 (.A(n_1418),
	.B(n_1420),
	.Y(n_1421));
   NOR2X4 g23 (.A(count[0]),
	.B(count[2]),
	.Y(n_1418));
   NOR2X2 g22 (.A(count[3]),
	.B(n_1419),
	.Y(n_1420));
   CLKINVX2 g14428 (.A(count[1]),
	.Y(n_1419));
   NOR2X2 g14478 (.A(state[1]),
	.B(n_1562),
	.Y(n_1563));
   NAND2XL g50 (.A(n_1564),
	.B(n_1565),
	.Y(n_1566));
   NOR2X1 g51 (.A(state[1]),
	.B(state[0]),
	.Y(n_1564));
   NOR2X4 g52 (.A(state[4]),
	.B(state[3]),
	.Y(n_1565));
   NAND2X2 g49 (.A(n_1567),
	.B(n_1568),
	.Y(n_1569));
   NAND2X2 g53 (.A(state[5]),
	.B(FE_DBTN1_state_2),
	.Y(n_1567));
   NAND2X2 g54 (.A(state[2]),
	.B(FE_DBTN3_state_5),
	.Y(n_1568));
   CLKAND2X3 g14481 (.A(n_1565),
	.B(n_1359),
	.Y(n_1571));
   NAND2X1 g34 (.A(n_1585),
	.B(n_480),
	.Y(n_1586));
   CLKAND2X3 g42 (.A(n_269),
	.B(n_719),
	.Y(n_1583));
   CLKINVX1 g20 (.A(n_1566),
	.Y(n_1587));
   NAND2X1 g14491 (.A(n_1643),
	.B(n_1642),
	.Y(n_1591));
   AOI22X2 g103 (.A0(n_1653),
	.A1(n_1637),
	.B0(n_1638),
	.B1(n_1644),
	.Y(n_1640));
   NOR2X1 g107 (.A(n_1872),
	.B(count[0]),
	.Y(n_1637));
   AND2X1 g106 (.A(n_1536),
	.B(n_1421),
	.Y(n_1638));
   NAND3X2 g69 (.A(n_1643),
	.B(n_1642),
	.C(FE_OCPN1_n_1875),
	.Y(n_1644));
   NAND2X2 g71 (.A(n_1587),
	.B(FE_OCPN5_n_1569),
	.Y(n_1642));
   NOR2XL g90 (.A(n_1591),
	.B(n_1263),
	.Y(n_1646));
   NAND2X1 g91 (.A(count[3]),
	.B(FE_OCPN5_n_88),
	.Y(n_1647));
   NOR2BX1 g29 (.AN(n_1650),
	.B(n_1872),
	.Y(n_1652));
   NAND3X1 g31 (.A(n_1536),
	.B(count[2]),
	.C(n_1404),
	.Y(n_1650));
   CLKINVX3 g14494 (.A(count[0]),
	.Y(n_1536));
   NAND3X4 g14496 (.A(n_1536),
	.B(count[2]),
	.C(n_1404),
	.Y(n_1653));
   MXI2X1 g14607 (.A(count[3]),
	.B(n_1824),
	.S0(n_1825),
	.Y(n_1826));
   INVX1 g14608 (.A(count[3]),
	.Y(n_1824));
   OR2X1 g14609 (.A(n_231),
	.B(n_19),
	.Y(n_1825));
   NAND3XL g67 (.A(n_1866),
	.B(n_1867),
	.C(n_1868),
	.Y(n_1869));
   NAND2XL g14641 (.A(state[1]),
	.B(n_88),
	.Y(n_1866));
   NAND2X1 g68 (.A(n_1415),
	.B(n_1421),
	.Y(n_1867));
   NAND2XL g14642 (.A(n_57),
	.B(n_1417),
	.Y(n_1868));
   AOI22X2 g14644 (.A0(n_1872),
	.A1(n_719),
	.B0(n_57),
	.B1(FE_OCPN1_n_1875),
	.Y(n_1876));
   NAND2X8 g14645 (.A(n_1408),
	.B(n_904),
	.Y(n_1872));
   NAND2X4 g14647 (.A(n_1408),
	.B(n_1571),
	.Y(n_1875));
   NAND2X2 g14654 (.A(n_1826),
	.B(FE_OFN0_n_88),
	.Y(n_1886));
   NAND2X2 g14656 (.A(n_20),
	.B(FE_OFN0_n_88),
	.Y(n_1888));
   OAI211X1 g14658 (.A0(n_1536),
	.A1(FE_OFN0_n_88),
	.B0(n_1640),
	.C0(n_1889),
	.Y(n_1890));
   NAND2X1 g13636__14659 (.A(n_45),
	.B(FE_OFN0_n_88),
	.Y(n_1889));
   DFFSX1 \state_reg[0]  (.CK(clk),
	.D(n_1586),
	.Q(state[0]),
	.QN(n_1562),
	.SN(n_91));
endmodule

