/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Wed Jun 24 14:36:50 2026
#  Design:            alu
#  Command:           saveNetlist alu_physical_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 24 2026 14:22:25 IST (Jun 24 2026 08:52:25 UTC)
// Verification Directory fv/alu 
module alu (
	a, 
	b, 
	c, 
	clk, 
	rst, 
	y);
   input [3:0] a;
   input [3:0] b;
   input [3:0] c;
   input clk;
   input rst;
   output [7:0] y;

   // Internal wires
   wire FE_OCPN11_n_1142;
   wire FE_RN_15_0;
   wire FE_RN_14_0;
   wire FE_RN_13_0;
   wire FE_RN_12_0;
   wire FE_RN_11_0;
   wire FE_RN_10_0;
   wire FE_OCPN10_n_1223;
   wire FE_RN_9_0;
   wire FE_RN_4;
   wire FE_RN_3;
   wire FE_RN_8_0;
   wire FE_OCPN9_n_1226;
   wire FE_RN_7_0;
   wire FE_RN_6_0;
   wire FE_RN_5_0;
   wire FE_RN_2;
   wire FE_RN_4_0;
   wire FE_OCPN8_n_980;
   wire FE_RN_1;
   wire FE_RN_3_0;
   wire FE_RN_2_0;
   wire FE_RN_1_0;
   wire FE_OCPN7_n_1674;
   wire FE_RN_0_0;
   wire FE_DBTN6_a_3;
   wire FE_DBTN5_a_2;
   wire FE_DBTN4_a_1;
   wire FE_DBTN3_a_0;
   wire FE_DBTN2_b_3;
   wire FE_DBTN1_b_2;
   wire FE_DBTN0_c_3;
   wire n_3;
   wire n_5;
   wire n_6;
   wire n_8;
   wire n_14;
   wire n_15;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_28;
   wire n_44;
   wire n_46;
   wire n_47;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_60;
   wire n_67;
   wire n_70;
   wire n_72;
   wire n_81;
   wire n_84;
   wire n_87;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_94;
   wire n_99;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_110;
   wire n_111;
   wire n_116;
   wire n_118;
   wire n_119;
   wire n_122;
   wire n_126;
   wire n_128;
   wire n_133;
   wire n_137;
   wire n_139;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_147;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_156;
   wire n_158;
   wire n_159;
   wire n_161;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_176;
   wire n_192;
   wire n_200;
   wire n_202;
   wire n_206;
   wire n_209;
   wire n_216;
   wire n_222;
   wire n_223;
   wire n_226;
   wire n_247;
   wire n_304;
   wire n_343;
   wire n_354;
   wire n_355;
   wire n_360;
   wire n_609;
   wire n_610;
   wire n_614;
   wire n_639;
   wire n_642;
   wire n_648;
   wire n_656;
   wire n_657;
   wire n_658;
   wire n_663;
   wire n_691;
   wire n_699;
   wire n_708;
   wire n_739;
   wire n_760;
   wire n_761;
   wire n_777;
   wire n_778;
   wire n_783;
   wire n_785;
   wire n_809;
   wire n_821;
   wire n_834;
   wire n_835;
   wire n_868;
   wire n_880;
   wire n_881;
   wire n_882;
   wire n_891;
   wire n_892;
   wire n_915;
   wire n_919;
   wire n_920;
   wire n_938;
   wire n_939;
   wire n_951;
   wire n_956;
   wire n_957;
   wire n_965;
   wire n_968;
   wire n_971;
   wire n_972;
   wire n_974;
   wire n_979;
   wire n_980;
   wire n_981;
   wire n_984;
   wire n_1012;
   wire n_1013;
   wire n_1017;
   wire n_1034;
   wire n_1035;
   wire n_1039;
   wire n_1066;
   wire n_1067;
   wire n_1068;
   wire n_1069;
   wire n_1108;
   wire n_1114;
   wire n_1115;
   wire n_1116;
   wire n_1117;
   wire n_1118;
   wire n_1119;
   wire n_1137;
   wire n_1142;
   wire n_1144;
   wire n_1145;
   wire n_1147;
   wire n_1148;
   wire n_1149;
   wire n_1150;
   wire n_1151;
   wire n_1152;
   wire n_1153;
   wire n_1161;
   wire n_1205;
   wire n_1220;
   wire n_1223;
   wire n_1226;
   wire n_1227;
   wire n_1229;
   wire n_1230;
   wire n_1240;
   wire n_1241;
   wire n_1244;
   wire n_1245;
   wire n_1248;
   wire n_1249;
   wire n_1250;
   wire n_1254;
   wire n_1255;
   wire n_1257;
   wire n_1258;
   wire n_1364;
   wire n_1365;
   wire n_1366;
   wire n_1374;
   wire n_1378;
   wire n_1392;
   wire n_1393;
   wire n_1396;
   wire n_1404;
   wire n_1405;
   wire n_1407;
   wire n_1408;
   wire n_1409;
   wire n_1414;
   wire n_1415;
   wire n_1416;
   wire n_1417;
   wire n_1418;
   wire n_1419;
   wire n_1422;
   wire n_1423;
   wire n_1424;
   wire n_1425;
   wire n_1430;
   wire n_1431;
   wire n_1432;
   wire n_1433;
   wire n_1477;
   wire n_1504;
   wire n_1506;
   wire n_1507;
   wire n_1513;
   wire n_1514;
   wire n_1515;
   wire n_1516;
   wire n_1517;
   wire n_1610;
   wire n_1614;
   wire n_1616;
   wire n_1630;
   wire n_1632;
   wire n_1633;
   wire n_1673;
   wire n_1674;
   wire n_1675;
   wire n_1676;
   wire n_1679;
   wire n_1680;
   wire n_1682;
   wire n_1683;
   wire n_1684;
   wire n_1685;
   wire n_1708;
   wire n_1710;
   wire n_1711;
   wire n_1713;
   wire n_1714;
   wire n_1718;
   wire n_1719;
   wire n_1720;
   wire n_1722;
   wire n_1739;
   wire n_1740;
   wire n_1743;
   wire n_1744;
   wire n_1745;
   wire n_1746;
   wire n_1749;
   wire n_1750;
   wire n_1751;
   wire n_1752;
   wire n_1753;
   wire n_1754;
   wire n_1755;
   wire n_1756;
   wire n_1759;
   wire n_1760;
   wire n_1764;
   wire n_1765;
   wire n_1767;
   wire n_1768;
   wire n_1770;
   wire n_1771;
   wire n_1772;
   wire n_1774;
   wire n_1775;
   wire n_1776;
   wire n_1777;
   wire n_1780;
   wire n_1781;
   wire n_1783;
   wire n_1784;
   wire n_1785;
   wire n_1786;
   wire n_1787;
   wire n_1788;
   wire n_1789;
   wire n_1790;
   wire n_1821;
   wire n_1822;
   wire n_1823;
   wire n_1824;
   wire n_1838;
   wire n_1839;
   wire n_1840;
   wire n_1841;
   wire n_1881;
   wire n_1887;
   wire n_1888;
   wire n_1889;
   wire n_1890;
   wire n_1909;
   wire n_1910;
   wire n_1911;
   wire n_1912;
   wire n_1913;
   wire n_1914;
   wire n_1915;
   wire n_1916;
   wire n_1917;
   wire n_1918;
   wire n_1923;

   CLKBUFX2 FE_OCPC11_n_1142 (.A(n_1142),
	.Y(FE_OCPN11_n_1142));
   INVX20 FE_RC_43_0 (.A(c[0]),
	.Y(n_3));
   CLKINVX3 FE_RC_42_0 (.A(c[0]),
	.Y(FE_RN_15_0));
   NOR2X2 FE_RC_41_0 (.A(FE_RN_15_0),
	.B(c[2]),
	.Y(n_44));
   NAND3BX4 FE_RC_40_0 (.AN(c[2]),
	.B(c[0]),
	.C(n_1673),
	.Y(n_173));
   CLKINVX1 FE_RC_39_0 (.A(n_55),
	.Y(n_56));
   CLKINVX1 FE_RC_38_0 (.A(FE_RN_10_0),
	.Y(FE_RN_11_0));
   CLKINVX1 FE_RC_37_0 (.A(n_1374),
	.Y(FE_RN_12_0));
   NAND2X1 FE_RC_36_0 (.A(n_55),
	.B(FE_RN_12_0),
	.Y(FE_RN_13_0));
   NAND2X1 FE_RC_35_0 (.A(FE_RN_11_0),
	.B(FE_RN_13_0),
	.Y(FE_RN_14_0));
   NOR2X2 FE_RC_34_0 (.A(n_1772),
	.B(FE_RN_14_0),
	.Y(n_1774));
   NAND3X1 FE_RC_33_0 (.A(n_1616),
	.B(n_1477),
	.C(n_1378),
	.Y(n_1632));
   CLKINVX1 FE_RC_32_0 (.A(FE_RN_1_0),
	.Y(FE_RN_10_0));
   CLKBUFX2 FE_OCPC10_n_1223 (.A(n_1223),
	.Y(FE_OCPN10_n_1223));
   NAND3X6 FE_RC_30_0 (.A(c[1]),
	.B(FE_DBTN0_c_3),
	.C(n_656),
	.Y(n_657));
   OAI21X2 FE_RC_29_0 (.A0(n_1765),
	.A1(n_1039),
	.B0(n_1257),
	.Y(n_951));
   NOR2X4 FE_RC_28_0 (.A(FE_DBTN6_a_3),
	.B(n_1205),
	.Y(n_1229));
   NOR2X8 FE_RC_27_0 (.A(n_1205),
	.B(FE_DBTN6_a_3),
	.Y(FE_RN_9_0));
   NAND2X6 FE_RC_26_0 (.A(FE_RN_4),
	.B(FE_RN_9_0),
	.Y(n_1711));
   NOR2X8 g38765_dup (.A(FE_DBTN2_b_3),
	.B(FE_RN_3),
	.Y(FE_RN_4));
   OAI22X4 FE_RC_25_0 (.A0(n_708),
	.A1(n_610),
	.B0(n_609),
	.B1(n_1364),
	.Y(n_614));
   AOI21X4 FE_RC_24_0 (.A0(n_1720),
	.A1(n_1722),
	.B0(n_1013),
	.Y(n_1764));
   AOI22X4 FE_RC_23_0 (.A0(n_1227),
	.A1(n_1226),
	.B0(n_1230),
	.B1(n_1229),
	.Y(n_1708));
   CLKINVX20 FE_DBTC4_a_1_dup1 (.A(a[1]),
	.Y(FE_RN_3));
   AOI21X4 FE_RC_22_0 (.A0(n_1249),
	.A1(n_1250),
	.B0(n_1912),
	.Y(n_868));
   NAND2XL FE_RC_21_0 (.A(c[3]),
	.B(n_354),
	.Y(FE_RN_8_0));
   NOR2BX2 FE_RC_20_0 (.AN(FE_RN_8_0),
	.B(n_972),
	.Y(n_785));
   INVX20 FE_RC_19_0 (.A(b[2]),
	.Y(FE_DBTN1_b_2));
   CLKBUFX2 FE_OCPC9_n_1226 (.A(n_1226),
	.Y(FE_OCPN9_n_1226));
   CLKINVX1 FE_RC_18_0 (.A(n_223),
	.Y(FE_RN_5_0));
   CLKINVX1 FE_RC_17_0 (.A(n_222),
	.Y(FE_RN_6_0));
   NAND2BX1 FE_RC_16_0 (.AN(FE_RN_6_0),
	.B(n_971),
	.Y(FE_RN_7_0));
   OAI211X1 FE_RC_15_0 (.A0(n_979),
	.A1(FE_OCPN11_n_1142),
	.B0(FE_RN_7_0),
	.C0(FE_RN_5_0),
	.Y(n_1161));
   CLKINVX20 FE_DBTC2_b_3_dup (.A(b[3]),
	.Y(FE_RN_2));
   NAND2XL FE_RC_14_0 (.A(n_881),
	.B(n_206),
	.Y(FE_RN_4_0));
   NOR2BX1 FE_RC_13_0 (.AN(FE_RN_4_0),
	.B(n_216),
	.Y(n_1430));
   CLKBUFX2 FE_OCPC8_n_980 (.A(n_980),
	.Y(FE_OCPN8_n_980));
   CLKINVX12 FE_DBTC4_a_1_dup (.A(a[1]),
	.Y(FE_RN_1));
   NAND2X2 FE_RC_12_0 (.A(n_1118),
	.B(n_1119),
	.Y(FE_RN_2_0));
   NAND2X2 FE_RC_11_0 (.A(n_1117),
	.B(FE_RN_2_0),
	.Y(FE_RN_3_0));
   OAI21X4 FE_RC_10_0 (.A0(n_1777),
	.A1(FE_RN_3_0),
	.B0(n_981),
	.Y(n_1745));
   INVX2 FE_RC_9_0 (.A(n_1767),
	.Y(FE_RN_1_0));
   AOI22X4 FE_RC_7_0 (.A0(n_1254),
	.A1(n_1405),
	.B0(n_835),
	.B1(n_614),
	.Y(n_1409));
   BUFX3 FE_OCPC7_n_1674 (.A(n_1674),
	.Y(FE_OCPN7_n_1674));
   NOR3X2 FE_RC_6_0 (.A(n_1257),
	.B(n_1765),
	.C(n_1039),
	.Y(n_1258));
   NOR3X2 FE_RC_5_0 (.A(n_1220),
	.B(n_1745),
	.C(n_1824),
	.Y(n_984));
   NAND2X2 FE_RC_4_0 (.A(n_1780),
	.B(n_1781),
	.Y(FE_RN_0_0));
   NAND2X2 FE_RC_3_0 (.A(n_1840),
	.B(FE_RN_0_0),
	.Y(n_1841));
   AOI21X2 FE_RC_2_0 (.A0(n_47),
	.A1(n_1255),
	.B0(n_355),
	.Y(n_972));
   AOI21X2 FE_RC_1_0 (.A0(n_1108),
	.A1(n_1746),
	.B0(n_1674),
	.Y(n_1114));
   INVX1 FE_OFC3_n_15 (.A(n_15),
	.Y(n_111));
   INVX1 FE_OFC2_n_785 (.A(n_785),
	.Y(n_216));
   INVX1 FE_OFC1_n_99 (.A(n_99),
	.Y(n_172));
   INVX1 FE_OFC0_rst (.A(rst),
	.Y(n_247));
   CLKINVX20 FE_DBTC6_a_3 (.A(a[3]),
	.Y(FE_DBTN6_a_3));
   CLKINVX20 FE_DBTC5_a_2 (.A(a[2]),
	.Y(FE_DBTN5_a_2));
   CLKINVX20 FE_DBTC4_a_1 (.A(a[1]),
	.Y(FE_DBTN4_a_1));
   CLKINVX20 FE_DBTC3_a_0 (.A(a[0]),
	.Y(FE_DBTN3_a_0));
   CLKINVX20 FE_DBTC2_b_3 (.A(b[3]),
	.Y(FE_DBTN2_b_3));
   CLKINVX12 FE_DBTC0_c_3 (.A(c[3]),
	.Y(FE_DBTN0_c_3));
   DFFRHQX4 \y_reg[5]  (.CK(clk),
	.D(n_1822),
	.Q(y[5]),
	.RN(n_247));
   DFFRHQX1 \y_reg[4]  (.CK(clk),
	.D(n_1433),
	.Q(y[4]),
	.RN(n_247));
   DFFRHQX4 \y_reg[6]  (.CK(clk),
	.D(n_360),
	.Q(y[6]),
	.RN(n_247));
   DFFRHQX1 \y_reg[7]  (.CK(clk),
	.D(n_778),
	.Q(y[7]),
	.RN(n_247));
   DFFRHQX4 \y_reg[3]  (.CK(clk),
	.D(n_1161),
	.Q(y[3]),
	.RN(n_247));
   DFFRHQX8 \y_reg[0]  (.CK(clk),
	.D(n_1517),
	.Q(y[0]),
	.RN(n_247));
   DFFRHQX1 \y_reg[2]  (.CK(clk),
	.D(n_1151),
	.Q(y[2]),
	.RN(n_247));
   DFFRHQX1 \y_reg[1]  (.CK(clk),
	.D(n_226),
	.Q(y[1]),
	.RN(n_247));
   NAND4X1 g38136__6131 (.A(n_161),
	.B(n_156),
	.C(n_1396),
	.D(n_209),
	.Y(n_226));
   OAI21X1 g38139__5115 (.A0(n_222),
	.A1(n_882),
	.B0(n_968),
	.Y(n_223));
   AOI22X1 g38151__7410 (.A0(n_159),
	.A1(n_1516),
	.B0(n_94),
	.B1(n_149),
	.Y(n_209));
   CLKINVX1 g38141 (.A(n_984),
	.Y(n_202));
   AOI221XL g38176__6260 (.A0(n_1404),
	.A1(n_821),
	.B0(n_104),
	.B1(n_1911),
	.C0(n_151),
	.Y(n_200));
   OAI2BB1X1 g38175__2802 (.A0N(n_111),
	.A1N(n_1911),
	.B0(n_147),
	.Y(n_192));
   AOI21X1 g38169__7482 (.A0(n_150),
	.A1(n_133),
	.B0(n_126),
	.Y(n_176));
   OAI211X1 g38178__6161 (.A0(n_173),
	.A1(n_1881),
	.B0(n_172),
	.C0(n_119),
	.Y(n_174));
   AOI22XL g38195__7410 (.A0(n_99),
	.A1(n_1392),
	.B0(n_1911),
	.B1(n_23),
	.Y(n_161));
   OAI211X1 g38168__6417 (.A0(n_51),
	.A1(n_72),
	.B0(n_118),
	.C0(n_1916),
	.Y(n_159));
   AOI32X1 g38186__2398 (.A0(n_1909),
	.A1(n_304),
	.A2(n_67),
	.B0(n_108),
	.B1(n_70),
	.Y(n_158));
   AOI22XL g38177__5107 (.A0(n_91),
	.A1(FE_RN_1),
	.B0(n_821),
	.B1(n_1374),
	.Y(n_156));
   OAI21X1 g38199__6783 (.A0(n_150),
	.A1(n_172),
	.B0(n_105),
	.Y(n_151));
   OAI221X1 g38192__3680 (.A0(n_1017),
	.A1(n_657),
	.B0(n_46),
	.B1(n_173),
	.C0(n_144),
	.Y(n_149));
   AOI32X1 g38193__1617 (.A0(n_1914),
	.A1(n_1516),
	.A2(n_81),
	.B0(FE_DBTN5_a_2),
	.B1(n_139),
	.Y(n_147));
   OAI221X1 g38198__2802 (.A0(n_144),
	.A1(n_143),
	.B0(n_142),
	.B1(n_809),
	.C0(n_107),
	.Y(n_145));
   NAND2XL g38202__8246 (.A(n_55),
	.B(n_116),
	.Y(n_137));
   NAND3XL g38205__4733 (.A(n_144),
	.B(n_657),
	.C(n_173),
	.Y(n_133));
   OAI22X1 g38196__9315 (.A0(n_110),
	.A1(n_173),
	.B0(n_657),
	.B1(n_868),
	.Y(n_128));
   AOI21X1 g38207__9945 (.A0(n_809),
	.A1(n_1142),
	.B0(n_1404),
	.Y(n_126));
   AOI21X1 g38215__1666 (.A0(n_1909),
	.A1(n_106),
	.B0(n_84),
	.Y(n_122));
   NAND2XL g38203__6417 (.A(n_868),
	.B(n_658),
	.Y(n_119));
   OAI211X1 g38212__5477 (.A0(FE_DBTN6_a_3),
	.A1(n_92),
	.B0(n_1914),
	.C0(n_57),
	.Y(n_118));
   OAI211X1 g38234__2398 (.A0(FE_DBTN4_a_1),
	.A1(b[0]),
	.B0(b[2]),
	.C0(n_49),
	.Y(n_116));
   OAI21X1 g38235__8428 (.A0(FE_DBTN5_a_2),
	.A1(n_1017),
	.B0(n_1770),
	.Y(n_108));
   NAND2XL g38225__5526 (.A(n_15),
	.B(n_106),
	.Y(n_107));
   OA22X1 g38214__6783 (.A0(n_104),
	.A1(n_90),
	.B0(a[0]),
	.B1(n_1423),
	.Y(n_105));
   INVXL g38269 (.A(n_1392),
	.Y(n_94));
   OAI21XL g38200__1705 (.A0(b[1]),
	.A1(n_90),
	.B0(n_1423),
	.Y(n_91));
   OAI221X1 g38208__8246 (.A0(n_1759),
	.A1(n_1610),
	.B0(a[1]),
	.B1(n_28),
	.C0(n_21),
	.Y(n_87));
   NOR2XL g38221__1881 (.A(n_1767),
	.B(n_809),
	.Y(n_84));
   AOI21X1 g38272__7482 (.A0(b[1]),
	.A1(FE_DBTN6_a_3),
	.B0(n_92),
	.Y(n_81));
   NOR2X1 g38229__9945 (.A(c[1]),
	.B(n_90),
	.Y(n_99));
   INVXL g38246 (.A(n_892),
	.Y(n_72));
   AOI21X1 g38278__2346 (.A0(FE_DBTN4_a_1),
	.A1(b[0]),
	.B0(n_1069),
	.Y(n_70));
   NAND2X1 g38273__7410 (.A(b[1]),
	.B(n_1017),
	.Y(n_67));
   CLKINVX1 g38251 (.A(n_173),
	.Y(n_206));
   INVXL g38267 (.A(n_1414),
	.Y(n_222));
   NAND2X4 g38264__6260 (.A(c[2]),
	.B(n_60),
	.Y(n_144));
   AOI21X1 g38224__5526 (.A0(FE_DBTN6_a_3),
	.A1(n_6),
	.B0(n_1068),
	.Y(n_57));
   INVXL g38268 (.A(n_143),
	.Y(n_52));
   CLKINVX1 g38249 (.A(n_1423),
	.Y(n_139));
   OAI21X2 g38226__1617 (.A0(n_22),
	.A1(n_1404),
	.B0(n_1374),
	.Y(n_110));
   NAND2XL g38275__2802 (.A(a[2]),
	.B(n_1610),
	.Y(n_51));
   INVXL g38325 (.A(n_1017),
	.Y(n_50));
   NAND2X1 g38277__1705 (.A(a[0]),
	.B(n_1610),
	.Y(n_49));
   CLKINVX1 g38248 (.A(n_90),
	.Y(n_106));
   NOR2X1 g38258__7098 (.A(n_14),
	.B(n_46),
	.Y(n_150));
   NOR2X1 g38259__4733 (.A(n_1767),
	.B(n_1770),
	.Y(n_55));
   CLKINVX1 g38330 (.A(FE_OCPN10_n_1223),
	.Y(n_142));
   CLKINVX4 g38293 (.A(n_663),
	.Y(n_60));
   AOI22X1 g38282__2883 (.A0(a[2]),
	.A1(FE_DBTN1_b_2),
	.B0(b[2]),
	.B1(FE_DBTN5_a_2),
	.Y(n_143));
   CLKINVX3 g38322 (.A(n_28),
	.Y(n_92));
   NAND2X2 g38262__6417 (.A(c[3]),
	.B(n_656),
	.Y(n_90));
   INVXL g38287 (.A(n_22),
	.Y(n_23));
   NAND2XL g38333__5107 (.A(b[1]),
	.B(FE_DBTN5_a_2),
	.Y(n_21));
   CLKINVX1 g38292 (.A(n_14),
	.Y(n_104));
   NAND2X4 g38344__8428 (.A(b[0]),
	.B(FE_DBTN5_a_2),
	.Y(n_28));
   AOI22X1 g38276__3680 (.A0(b[0]),
	.A1(a[1]),
	.B0(b[1]),
	.B1(a[0]),
	.Y(n_8));
   NAND2X2 g38336__2802 (.A(b[3]),
	.B(FE_DBTN6_a_3),
	.Y(n_47));
   CLKINVX1 g38297 (.A(n_1404),
	.Y(n_46));
   NAND2X2 g38332__7482 (.A(a[1]),
	.B(a[2]),
	.Y(n_6));
   NOR2XL g38300__4733 (.A(b[1]),
	.B(b[3]),
	.Y(n_5));
   NOR2X1 g38340__6161 (.A(b[2]),
	.B(a[2]),
	.Y(n_15));
   NOR2X4 g38301__6260 (.A(b[1]),
	.B(a[1]),
	.Y(n_22));
   NOR2X1 g38307__8428 (.A(b[0]),
	.B(a[0]),
	.Y(n_14));
   NOR2XL g38280__38400 (.A(FE_DBTN5_a_2),
	.B(n_1116),
	.Y(n_304));
   OAI21X1 g164 (.A0(n_343),
	.A1(n_760),
	.B0(n_1425),
	.Y(n_360));
   OR2XL g171 (.A(n_1142),
	.B(n_1774),
	.Y(n_343));
   CLKINVX2 g183 (.A(c[2]),
	.Y(n_354));
   OR2X1 g175 (.A(n_1915),
	.B(n_657),
	.Y(n_355));
   CLKINVX4 g40 (.A(n_609),
	.Y(n_610));
   NAND2X8 g41 (.A(a[1]),
	.B(b[1]),
	.Y(n_609));
   NOR2X4 g33 (.A(n_639),
	.B(n_691),
	.Y(n_642));
   NAND2X8 g38478 (.A(b[0]),
	.B(b[1]),
	.Y(n_639));
   NAND2X1 g1071 (.A(n_980),
	.B(n_202),
	.Y(n_648));
   CLKINVX1 g54 (.A(n_657),
	.Y(n_658));
   NOR2X8 g62 (.A(c[2]),
	.B(c[0]),
	.Y(n_656));
   NAND2X4 g61 (.A(c[1]),
	.B(FE_DBTN0_c_3),
	.Y(n_663));
   NAND3X8 g18 (.A(a[2]),
	.B(a[3]),
	.C(FE_DBTN1_b_2),
	.Y(n_691));
   NOR2X1 g24 (.A(n_1115),
	.B(n_1116),
	.Y(n_699));
   NAND2X6 g38506 (.A(b[0]),
	.B(a[2]),
	.Y(n_708));
   NAND2X6 g34 (.A(a[2]),
	.B(b[2]),
	.Y(n_739));
   NOR2X1 g38522 (.A(n_1114),
	.B(n_1507),
	.Y(n_760));
   NOR2XL g68 (.A(n_1890),
	.B(n_1504),
	.Y(n_761));
   NAND3XL g115 (.A(n_785),
	.B(n_957),
	.C(n_777),
	.Y(n_778));
   NAND2X1 g38532 (.A(n_1114),
	.B(n_1679),
	.Y(n_777));
   NAND2BX1 g145 (.AN(n_1142),
	.B(n_1774),
	.Y(n_783));
   NAND3X4 g28 (.A(c[2]),
	.B(c[0]),
	.C(n_1673),
	.Y(n_809));
   NOR2X2 g38548 (.A(c[1]),
	.B(n_1423),
	.Y(n_821));
   CLKINVX2 g9 (.A(n_834),
	.Y(n_835));
   NAND2X2 g10 (.A(a[0]),
	.B(b[2]),
	.Y(n_834));
   OAI21X1 g83 (.A0(n_1909),
	.A1(n_880),
	.B0(n_1767),
	.Y(n_881));
   AOI21X1 g38584 (.A0(n_111),
	.A1(n_110),
	.B0(FE_OCPN10_n_1223),
	.Y(n_880));
   AOI21X1 g38585 (.A0(n_880),
	.A1(n_206),
	.B0(n_1680),
	.Y(n_882));
   NOR2X1 g38592 (.A(FE_DBTN1_b_2),
	.B(n_891),
	.Y(n_892));
   NAND2X4 g38593 (.A(a[3]),
	.B(FE_RN_2),
	.Y(n_891));
   CLKINVX2 g97 (.A(n_1746),
	.Y(n_915));
   NOR2X1 g95 (.A(n_915),
	.B(n_1142),
	.Y(n_919));
   NOR3XL g38605 (.A(n_984),
	.B(n_1142),
	.C(n_915),
	.Y(n_920));
   NOR2X1 g38620 (.A(n_761),
	.B(n_938),
	.Y(n_939));
   CLKINVX2 g38621 (.A(n_1108),
	.Y(n_938));
   NAND2BX1 g81 (.AN(n_1142),
	.B(n_956),
	.Y(n_957));
   OAI22XL g38632 (.A0(n_1768),
	.A1(n_1771),
	.B0(n_1374),
	.B1(n_56),
	.Y(n_956));
   NAND2X8 g38640 (.A(a[2]),
	.B(a[3]),
	.Y(n_965));
   NOR3X1 g38641 (.A(n_1910),
	.B(n_1515),
	.C(n_1419),
	.Y(n_968));
   OAI221XL g99 (.A0(n_1255),
	.A1(n_657),
	.B0(n_173),
	.B1(n_880),
	.C0(n_172),
	.Y(n_971));
   AOI2BB1X1 g17 (.A0N(n_984),
	.A1N(n_915),
	.B0(n_1142),
	.Y(n_974));
   XOR3XL g84 (.A(n_1257),
	.B(n_1409),
	.C(n_1676),
	.Y(n_979));
   OAI21X2 g38645 (.A0(n_1409),
	.A1(n_1258),
	.B0(n_951),
	.Y(n_980));
   CLKINVX2 g38647 (.A(n_699),
	.Y(n_981));
   AOI21X4 g38656 (.A0(b[3]),
	.A1(a[0]),
	.B0(n_1012),
	.Y(n_1013));
   NAND2X8 g38657 (.A(b[2]),
	.B(a[1]),
	.Y(n_1012));
   NOR2X4 g38660 (.A(a[0]),
	.B(n_1759),
	.Y(n_1017));
   NOR3X1 g38678 (.A(b[2]),
	.B(FE_OCPN9_n_1226),
	.C(n_1069),
	.Y(n_1034));
   NOR2X4 g38679 (.A(n_1719),
	.B(n_1787),
	.Y(n_1039));
   NAND2X8 g51 (.A(a[0]),
	.B(b[3]),
	.Y(n_1035));
   NAND2XL g38698 (.A(n_1066),
	.B(n_1914),
	.Y(n_1067));
   AOI21X1 g3 (.A0(FE_DBTN6_a_3),
	.A1(b[0]),
	.B0(b[1]),
	.Y(n_1066));
   CLKINVX2 g38699 (.A(n_1068),
	.Y(n_1069));
   NOR2X4 g38345__38700 (.A(b[1]),
	.B(FE_DBTN6_a_3),
	.Y(n_1068));
   NAND2X2 g219 (.A(n_1504),
	.B(n_1890),
	.Y(n_1108));
   NAND2X2 g375 (.A(n_1115),
	.B(n_1116),
	.Y(n_1117));
   NAND2X8 g379 (.A(b[3]),
	.B(a[0]),
	.Y(n_1115));
   NAND2X6 g380 (.A(b[2]),
	.B(a[1]),
	.Y(n_1116));
   NAND2X8 g382 (.A(a[3]),
	.B(b[0]),
	.Y(n_1118));
   NAND2X6 g378 (.A(b[1]),
	.B(a[2]),
	.Y(n_1119));
   AOI31X4 g50 (.A0(b[1]),
	.A1(b[0]),
	.A2(a[3]),
	.B0(n_739),
	.Y(n_1137));
   NAND4X1 g147 (.A(n_1150),
	.B(n_1148),
	.C(n_1149),
	.D(n_1147),
	.Y(n_1151));
   NAND2BX1 g148 (.AN(n_1142),
	.B(n_1408),
	.Y(n_1147));
   NAND2X4 g152 (.A(n_44),
	.B(n_60),
	.Y(n_1142));
   MXI2X1 g151 (.A(n_1144),
	.B(n_614),
	.S0(n_834),
	.Y(n_1145));
   CLKINVX1 g155 (.A(n_614),
	.Y(n_1144));
   AOI22XL g150 (.A0(n_142),
	.A1(n_821),
	.B0(n_52),
	.B1(n_128),
	.Y(n_1148));
   NOR2XL g154 (.A(n_145),
	.B(n_192),
	.Y(n_1149));
   NAND2XL g153 (.A(n_143),
	.B(n_174),
	.Y(n_1150));
   OAI2BB1X1 g22 (.A0N(n_1746),
	.A1N(n_648),
	.B0(n_1152),
	.Y(n_1153));
   NOR2X1 g23 (.A(n_1142),
	.B(n_939),
	.Y(n_1152));
   CLKINVX20 g38744 (.A(b[1]),
	.Y(n_1205));
   NOR2X1 g216 (.A(n_1888),
	.B(n_1841),
	.Y(n_1220));
   NOR2X4 g38756 (.A(FE_DBTN1_b_2),
	.B(FE_DBTN5_a_2),
	.Y(n_1223));
   NAND2X8 g38761 (.A(a[1]),
	.B(b[3]),
	.Y(n_1226));
   NAND2X8 g38762 (.A(a[3]),
	.B(b[1]),
	.Y(n_1227));
   NOR2X4 g38765 (.A(FE_DBTN2_b_3),
	.B(FE_RN_3),
	.Y(n_1230));
   NAND2X2 g38767 (.A(n_1240),
	.B(n_1244),
	.Y(n_1245));
   AOI21X2 g92 (.A0(n_1768),
	.A1(n_1756),
	.B0(n_1740),
	.Y(n_1240));
   CLKINVX1 g93 (.A(n_1755),
	.Y(n_1244));
   NAND2X6 g38771 (.A(a[2]),
	.B(b[3]),
	.Y(n_1241));
   OAI21X2 g557 (.A0(n_1248),
	.A1(n_868),
	.B0(n_1254),
	.Y(n_1255));
   NOR2X1 g563 (.A(a[2]),
	.B(FE_DBTN1_b_2),
	.Y(n_1248));
   NAND2X2 g561 (.A(b[1]),
	.B(FE_DBTN4_a_1),
	.Y(n_1249));
   NAND2X2 g562 (.A(b[0]),
	.B(FE_DBTN3_a_0),
	.Y(n_1250));
   NAND2X2 g560 (.A(a[2]),
	.B(FE_DBTN1_b_2),
	.Y(n_1254));
   NOR2X4 g26 (.A(n_708),
	.B(n_1374),
	.Y(n_1257));
   NOR2X4 g38849 (.A(n_1759),
	.B(FE_DBTN5_a_2),
	.Y(n_1364));
   CLKINVX1 g38850 (.A(n_1610),
	.Y(n_1365));
   NAND4X1 g38238__38852 (.A(n_1914),
	.B(FE_DBTN6_a_3),
	.C(n_1364),
	.D(n_1365),
	.Y(n_1366));
   NAND4XL g38861 (.A(n_92),
	.B(FE_RN_1),
	.C(a[0]),
	.D(n_1915),
	.Y(n_1378));
   AOI21X1 g270 (.A0(n_1392),
	.A1(n_1393),
	.B0(n_1683),
	.Y(n_1396));
   NOR2X1 g274 (.A(n_1912),
	.B(n_1365),
	.Y(n_1392));
   OAI22X1 g272 (.A0(n_1404),
	.A1(n_173),
	.B0(n_657),
	.B1(n_50),
	.Y(n_1393));
   NAND2X8 g38877 (.A(a[1]),
	.B(b[1]),
	.Y(n_1374));
   NAND2X8 g38316__38878 (.A(b[0]),
	.B(a[0]),
	.Y(n_1404));
   NOR2X8 g38261__38880 (.A(n_1374),
	.B(n_1404),
	.Y(n_1405));
   MXI2X1 g38881 (.A(n_1405),
	.B(n_1407),
	.S0(n_1145),
	.Y(n_1408));
   INVXL g38882 (.A(n_1405),
	.Y(n_1407));
   NAND3X1 g58 (.A(n_1416),
	.B(n_1417),
	.C(n_1418),
	.Y(n_1419));
   NAND2XL g38889 (.A(n_1414),
	.B(n_1415),
	.Y(n_1416));
   NAND2X1 g38890 (.A(n_891),
	.B(n_47),
	.Y(n_1414));
   INVX1 g63 (.A(n_144),
	.Y(n_1415));
   NAND2X1 g38891 (.A(FE_DBTN6_a_3),
	.B(n_139),
	.Y(n_1417));
   NAND2X1 g38892 (.A(n_821),
	.B(n_1767),
	.Y(n_1418));
   NAND2X2 g38893 (.A(n_354),
	.B(n_1422),
	.Y(n_1423));
   NOR2X2 g38894 (.A(n_3),
	.B(FE_DBTN0_c_3),
	.Y(n_1422));
   NOR2BX1 g38897 (.AN(n_785),
	.B(n_1424),
	.Y(n_1425));
   NOR2X2 g38898 (.A(n_783),
	.B(n_1114),
	.Y(n_1424));
   NAND3XL g38901 (.A(n_1430),
	.B(n_1432),
	.C(n_1431),
	.Y(n_1433));
   NAND2X1 g38902 (.A(n_974),
	.B(FE_OCPN8_n_980),
	.Y(n_1431));
   NAND2XL g38903 (.A(n_920),
	.B(n_1506),
	.Y(n_1432));
   OR2X1 g75 (.A(n_1017),
	.B(n_1682),
	.Y(n_1477));
   NOR2X2 g38 (.A(FE_OCPN7_n_1674),
	.B(n_1506),
	.Y(n_1507));
   NAND2X4 g38946 (.A(n_1754),
	.B(n_1245),
	.Y(n_1504));
   INVX1 g38947 (.A(n_980),
	.Y(n_1506));
   OAI21X1 g38952 (.A0(n_1514),
	.A1(n_1067),
	.B0(n_122),
	.Y(n_1515));
   NAND2X2 g38284__38953 (.A(n_1513),
	.B(n_1673),
	.Y(n_1514));
   NOR2X2 g38299__38954 (.A(c[0]),
	.B(n_354),
	.Y(n_1513));
   CLKINVX1 g38955 (.A(n_1514),
	.Y(n_1516));
   OAI211X1 g38132__38956 (.A0(n_1514),
	.A1(n_1633),
	.B0(n_200),
	.C0(n_176),
	.Y(n_1517));
   AOI33X1 g67 (.A0(n_1914),
	.A1(n_1610),
	.A2(n_1684),
	.B0(FE_DBTN5_a_2),
	.B1(n_1614),
	.B2(n_1915),
	.Y(n_1616));
   NAND2X4 g71 (.A(b[1]),
	.B(FE_RN_1),
	.Y(n_1610));
   INVX1 g39042 (.A(n_1374),
	.Y(n_1614));
   NOR3X2 g39050 (.A(n_1630),
	.B(n_1685),
	.C(n_1632),
	.Y(n_1633));
   OAI2BB1X1 g65 (.A0N(n_892),
	.A1N(n_87),
	.B0(n_137),
	.Y(n_1630));
   NOR2X6 g38304__39084 (.A(c[1]),
	.B(c[3]),
	.Y(n_1673));
   NOR2X1 g39085 (.A(n_1890),
	.B(n_1504),
	.Y(n_1674));
   AND2XL g2 (.A(a[3]),
	.B(FE_DBTN1_b_2),
	.Y(n_1675));
   OR2X1 g39086 (.A(n_1039),
	.B(n_1765),
	.Y(n_1676));
   NOR2XL g39089 (.A(n_1767),
	.B(n_1142),
	.Y(n_1679));
   NOR2BX1 g39090 (.AN(n_1255),
	.B(n_657),
	.Y(n_1680));
   AOI32X1 g39092 (.A0(a[2]),
	.A1(n_1784),
	.A2(n_5),
	.B0(n_1610),
	.B1(n_1675),
	.Y(n_1682));
   OAI32X1 g39093 (.A0(n_8),
	.A1(n_1405),
	.A2(n_1142),
	.B0(n_809),
	.B1(n_1374),
	.Y(n_1683));
   OAI2BB1X2 g39094 (.A0N(a[0]),
	.A1N(n_1783),
	.B0(b[0]),
	.Y(n_1684));
   NAND3BX1 g39095 (.AN(n_1034),
	.B(n_1366),
	.C(n_158),
	.Y(n_1685));
   NAND2X4 g39109 (.A(n_1227),
	.B(n_1226),
	.Y(n_1710));
   OAI21X4 g39111 (.A0(n_1713),
	.A1(n_1714),
	.B0(n_1718),
	.Y(n_1719));
   NAND2X8 g39112 (.A(b[2]),
	.B(a[1]),
	.Y(n_1713));
   CLKINVX4 g39113 (.A(n_1035),
	.Y(n_1714));
   NAND2X4 g39114 (.A(n_1713),
	.B(n_1749),
	.Y(n_1718));
   NAND2X6 g39117 (.A(b[2]),
	.B(a[1]),
	.Y(n_1720));
   NOR2X6 g39118 (.A(FE_DBTN3_a_0),
	.B(FE_RN_2),
	.Y(n_1722));
   NOR2X2 g21 (.A(n_1917),
	.B(n_1739),
	.Y(n_1740));
   NAND2X8 g39125 (.A(a[1]),
	.B(b[1]),
	.Y(n_1739));
   OAI21X4 g273 (.A0(n_1743),
	.A1(n_1744),
	.B0(n_1745),
	.Y(n_1746));
   NOR2X2 g39126 (.A(n_1888),
	.B(n_1841),
	.Y(n_1743));
   NOR2X2 g277 (.A(n_1708),
	.B(n_1823),
	.Y(n_1744));
   NOR2X6 g11 (.A(FE_DBTN3_a_0),
	.B(FE_RN_2),
	.Y(n_1749));
   OAI21X2 g181 (.A0(n_1750),
	.A1(n_1752),
	.B0(n_1753),
	.Y(n_1754));
   AOI22X4 g182 (.A0(b[3]),
	.A1(a[2]),
	.B0(a[3]),
	.B1(b[2]),
	.Y(n_1750));
   NOR2X2 g184 (.A(n_1241),
	.B(n_1751),
	.Y(n_1752));
   NAND2X8 g185 (.A(a[3]),
	.B(b[2]),
	.Y(n_1751));
   NOR2X2 g186 (.A(n_1917),
	.B(n_1918),
	.Y(n_1753));
   NOR2X2 g39129 (.A(n_1241),
	.B(n_1751),
	.Y(n_1755));
   NAND2X6 g187 (.A(b[3]),
	.B(a[2]),
	.Y(n_1756));
   CLKINVX20 g39131 (.A(b[0]),
	.Y(n_1759));
   AOI21X4 g39132 (.A0(n_1760),
	.A1(n_1923),
	.B0(n_1764),
	.Y(n_1765));
   NAND2X2 g47 (.A(n_1784),
	.B(n_1783),
	.Y(n_1760));
   NAND2X8 g79 (.A(b[3]),
	.B(a[3]),
	.Y(n_1767));
   NOR2X1 g74 (.A(n_1768),
	.B(n_1771),
	.Y(n_1772));
   NAND2X8 g78 (.A(a[3]),
	.B(b[2]),
	.Y(n_1768));
   OA21X1 g39136 (.A0(n_1918),
	.A1(n_1767),
	.B0(n_1770),
	.Y(n_1771));
   NAND2X4 g80 (.A(a[2]),
	.B(b[3]),
	.Y(n_1770));
   NOR2X6 g39137 (.A(n_1775),
	.B(n_1776),
	.Y(n_1777));
   NAND2X6 g39138 (.A(a[2]),
	.B(b[1]),
	.Y(n_1775));
   NAND2X8 g39139 (.A(b[0]),
	.B(a[3]),
	.Y(n_1776));
   NOR2X6 g39141 (.A(FE_DBTN1_b_2),
	.B(FE_DBTN5_a_2),
	.Y(n_1780));
   NAND3X8 g39 (.A(a[3]),
	.B(b[1]),
	.C(b[0]),
	.Y(n_1781));
   NAND2X4 g112 (.A(n_1785),
	.B(n_1786),
	.Y(n_1787));
   NAND2X4 g113 (.A(n_1783),
	.B(n_1784),
	.Y(n_1785));
   NAND2X8 g116 (.A(a[2]),
	.B(b[1]),
	.Y(n_1783));
   NAND2X8 g39144 (.A(b[0]),
	.B(a[3]),
	.Y(n_1784));
   NAND4X8 g114 (.A(a[2]),
	.B(b[0]),
	.C(a[3]),
	.D(b[1]),
	.Y(n_1786));
   NOR2X6 g39145 (.A(n_1789),
	.B(n_1788),
	.Y(n_1790));
   NAND2X8 g39146 (.A(a[2]),
	.B(b[0]),
	.Y(n_1788));
   NAND2X8 g39147 (.A(a[3]),
	.B(b[1]),
	.Y(n_1789));
   NAND3XL g39168 (.A(n_1821),
	.B(n_785),
	.C(n_1153),
	.Y(n_1822));
   NAND3X1 g39169 (.A(n_939),
	.B(n_919),
	.C(n_648),
	.Y(n_1821));
   NOR2X1 g39170 (.A(n_1708),
	.B(n_1823),
	.Y(n_1824));
   NOR2X2 g39171 (.A(n_1137),
	.B(n_642),
	.Y(n_1823));
   NAND2X2 g39182 (.A(n_1838),
	.B(n_1839),
	.Y(n_1840));
   NOR2X6 g52 (.A(n_1759),
	.B(n_1205),
	.Y(n_1838));
   NOR2X4 g39184 (.A(b[2]),
	.B(n_965),
	.Y(n_1839));
   INVXL g39211 (.A(n_110),
	.Y(n_1881));
   OAI21X2 g98 (.A0(n_1887),
	.A1(n_1888),
	.B0(n_1889),
	.Y(n_1890));
   NOR2X2 g39217 (.A(n_1790),
	.B(n_1223),
	.Y(n_1887));
   NAND2X4 g101 (.A(n_1710),
	.B(n_1711),
	.Y(n_1888));
   NAND2X1 g100 (.A(n_1223),
	.B(n_1790),
	.Y(n_1889));
   NOR3X1 g39233 (.A(c[0]),
	.B(n_1909),
	.C(n_144),
	.Y(n_1910));
   NOR2X2 g39234 (.A(a[3]),
	.B(b[3]),
	.Y(n_1909));
   NOR2X1 g39235 (.A(c[0]),
	.B(n_144),
	.Y(n_1911));
   OAI22X1 g57 (.A0(n_1912),
	.A1(n_1913),
	.B0(n_1914),
	.B1(n_1915),
	.Y(n_1916));
   NOR2X4 g60 (.A(b[1]),
	.B(FE_RN_1),
	.Y(n_1912));
   AOI21X2 g39236 (.A0(b[1]),
	.A1(FE_DBTN5_a_2),
	.B0(b[0]),
	.Y(n_1913));
   NOR2X4 g59 (.A(b[2]),
	.B(b[3]),
	.Y(n_1914));
   CLKINVX2 g39237 (.A(n_891),
	.Y(n_1915));
   NAND2X8 g39238 (.A(a[3]),
	.B(b[3]),
	.Y(n_1917));
   NAND2X8 g39239 (.A(a[1]),
	.B(b[1]),
	.Y(n_1918));
   NAND4X8 g39244 (.A(a[3]),
	.B(b[1]),
	.C(b[0]),
	.D(a[2]),
	.Y(n_1923));
endmodule

