
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun  8 2026 14:06:50 IST (Jun  8 2026 08:36:50 UTC)

// Verification Directory fv/count8 

module count8(clk, rst, u_d, counter);
  input clk, rst, u_d;
  output [7:0] counter;
  wire clk, rst, u_d;
  wire [7:0] counter;
  wire [7:0] counter_u_d;
  wire UNCONNECTED, n_47, n_59, n_64, n_103, n_193, n_195, n_196;
  wire n_197, n_198, n_210, n_214, n_263, n_274, n_275, n_276;
  wire n_291, n_295, n_296, n_299, n_309, n_328, n_330, n_334;
  wire n_336, n_337, n_339, n_341, n_343, n_344, n_352, n_354;
  wire n_355, n_356, n_357, n_358, n_359, n_361, n_362, n_371;
  wire n_372, n_373, n_374, n_375, n_376, n_377, n_378, n_379;
  wire n_380, n_381, n_383, n_384, n_385, n_386, n_387, n_388;
  wire n_389, n_392, n_393, n_394, n_395, n_397, n_398, n_399;
  wire n_400, n_401, n_402, n_403, n_404, n_405;
  DFFRHQX4 \counter_u_d_reg[7] (.RN (n_64), .CK (clk), .D (n_198), .Q
       (counter[7]));
  DFFRHQX4 \counter_u_d_reg[4] (.RN (n_64), .CK (clk), .D (n_356), .Q
       (counter[4]));
  DFFRHQX4 \counter_u_d_reg[2] (.RN (n_64), .CK (clk), .D (n_395), .Q
       (counter[2]));
  DFFRHQX4 \counter_u_d_reg[5] (.RN (n_64), .CK (clk), .D (n_59), .Q
       (counter[5]));
  MXI2X1 g2939__8428(.A (counter[5]), .B (n_309), .S0 (n_276), .Y
       (n_59));
  NOR2X2 g2959__8246(.A (n_377), .B (n_381), .Y (n_47));
  DFFRHQX4 \counter_u_d_reg[1] (.RN (n_64), .CK (clk), .D (n_334), .Q
       (counter_u_d[1]));
  DFFRHQX4 \counter_u_d_reg[0] (.RN (n_64), .CK (clk), .D (n_210), .Q
       (counter[0]));
  INVXL g2997(.A (rst), .Y (n_64));
  SDFFRX2 \counter_u_d_reg[6] (.RN (n_64), .CK (clk), .D (n_374), .SI
       (n_375), .SE (counter[6]), .Q (counter[6]), .QN (UNCONNECTED));
  CLKINVX1 g599(.A (counter[7]), .Y (n_103));
  DFFRHQX4 \counter_u_d_reg[3] (.RN (n_64), .CK (clk), .D (n_380), .Q
       (counter[3]));
  OAI21X1 g223(.A0 (n_193), .A1 (n_405), .B0 (n_197), .Y (n_198));
  NAND2BX1 g225(.AN (u_d), .B (n_401), .Y (n_193));
  MXI2X1 g224(.A (n_195), .B (n_196), .S0 (n_47), .Y (n_197));
  AND2XL g227(.A (u_d), .B (counter[7]), .Y (n_195));
  AND2XL g228(.A (u_d), .B (n_103), .Y (n_196));
  INVXL g47(.A (counter[0]), .Y (n_210));
  NOR2XL g42(.A (n_399), .B (n_344), .Y (n_214));
  INVXL fopt3045(.A (n_344), .Y (counter[1]));
  NOR2XL g97(.A (n_383), .B (n_372), .Y (n_263));
  AOI31X1 g3056(.A0 (n_387), .A1 (n_341), .A2 (n_362), .B0 (n_275), .Y
       (n_276));
  NOR3X1 g3059(.A (n_358), .B (n_384), .C (n_274), .Y (n_275));
  NAND2XL g3062(.A (counter[2]), .B (counter[0]), .Y (n_274));
  AOI21XL g87(.A0 (n_339), .A1 (n_291), .B0 (n_373), .Y (n_295));
  NOR2XL g3069(.A (counter[0]), .B (counter[2]), .Y (n_291));
  NAND2XL g89(.A (n_339), .B (n_291), .Y (n_296));
  CLKINVX1 g95(.A (counter[2]), .Y (n_299));
  CLKINVX1 g3078(.A (counter[5]), .Y (n_309));
  NAND2X1 g129(.A (n_386), .B (n_336), .Y (n_328));
  NAND2BX1 g126(.AN (counter[5]), .B (n_357), .Y (n_330));
  XNOR3X1 g2947__3084(.A (counter[0]), .B (u_d), .C (counter[1]), .Y
       (n_334));
  NOR2X1 g3085(.A (counter_u_d[1]), .B (counter[2]), .Y (n_336));
  NOR2X1 g3086(.A (counter_u_d[1]), .B (counter[5]), .Y (n_337));
  NOR2XL g3088(.A (u_d), .B (counter_u_d[1]), .Y (n_339));
  NOR2XL g3090(.A (counter_u_d[1]), .B (counter[2]), .Y (n_341));
  NOR3X1 g3092(.A (counter_u_d[1]), .B (counter[0]), .C (counter[2]),
       .Y (n_343));
  INVX1 fopt3093(.A (counter_u_d[1]), .Y (n_344));
  AOI21X1 g70(.A0 (n_388), .A1 (n_343), .B0 (n_263), .Y (n_352));
  MXI2X1 g3098(.A (n_354), .B (n_355), .S0 (n_352), .Y (n_356));
  BUFX2 g3099(.A (counter[4]), .Y (n_354));
  INVX1 g3100(.A (n_354), .Y (n_355));
  NOR2X1 g3101(.A (counter[0]), .B (counter[4]), .Y (n_357));
  NAND2XL g3102(.A (counter[4]), .B (u_d), .Y (n_358));
  NOR2X1 g3103(.A (counter[4]), .B (counter[0]), .Y (n_359));
  NAND3XL g3105(.A (counter[0]), .B (counter[4]), .C (counter[5]), .Y
       (n_361));
  NOR2XL g3106(.A (counter[4]), .B (counter[0]), .Y (n_362));
  NOR2XL g24(.A (n_371), .B (n_372), .Y (n_373));
  NAND2XL g25(.A (counter_u_d[1]), .B (counter[0]), .Y (n_371));
  NAND2X1 g26(.A (u_d), .B (counter[2]), .Y (n_372));
  OAI22X1 g3113(.A0 (n_328), .A1 (n_330), .B0 (n_361), .B1 (n_385), .Y
       (n_374));
  INVXL g3114(.A (n_374), .Y (n_375));
  NOR2X1 g3115(.A (counter[6]), .B (counter[2]), .Y (n_376));
  NAND3X1 g2965__3116(.A (counter[6]), .B (counter[5]), .C
       (counter[0]), .Y (n_377));
  OAI21X1 g3117(.A0 (n_378), .A1 (n_295), .B0 (n_379), .Y (n_380));
  BUFX2 g3118(.A (counter[3]), .Y (n_378));
  OAI211XL g3119(.A0 (n_371), .A1 (n_372), .B0 (n_378), .C0 (n_296), .Y
       (n_379));
  NAND4X2 g3120(.A (counter[3]), .B (counter[2]), .C (counter[4]), .D
       (counter_u_d[1]), .Y (n_381));
  NAND3XL g3122(.A (counter_u_d[1]), .B (counter[3]), .C (counter[0]),
       .Y (n_383));
  NAND2XL g3123(.A (counter_u_d[1]), .B (counter[3]), .Y (n_384));
  NAND4X1 g3124(.A (counter[3]), .B (u_d), .C (counter_u_d[1]), .D
       (counter[2]), .Y (n_385));
  NOR2X1 g3125(.A (u_d), .B (counter[3]), .Y (n_386));
  NOR2XL g3126(.A (u_d), .B (counter[3]), .Y (n_387));
  NOR2XL g3127(.A (u_d), .B (counter[3]), .Y (n_388));
  NOR2XL g21(.A (n_299), .B (n_214), .Y (n_389));
  OAI21X1 g40(.A0 (n_392), .A1 (n_393), .B0 (n_394), .Y (n_395));
  INVX1 g43(.A (n_299), .Y (n_392));
  NOR2XL g3129(.A (n_214), .B (n_397), .Y (n_393));
  NAND2BXL g41(.AN (n_397), .B (n_389), .Y (n_394));
  NOR2BX1 g11(.AN (n_344), .B (n_398), .Y (n_397));
  OR2XL g2(.A (u_d), .B (counter[0]), .Y (n_398));
  NAND2XL g3130(.A (u_d), .B (counter[0]), .Y (n_399));
  NAND4XL g118(.A (n_400), .B (n_359), .C (n_376), .D (n_337), .Y
       (n_401));
  NOR2XL g120(.A (counter[3]), .B (n_103), .Y (n_400));
  AOI21X1 g117(.A0 (n_403), .A1 (n_404), .B0 (counter[7]), .Y (n_405));
  CLKAND2X2 g121(.A (n_402), .B (n_359), .Y (n_403));
  INVXL g122(.A (counter[3]), .Y (n_402));
  CLKAND2X2 g119(.A (n_376), .B (n_337), .Y (n_404));
endmodule

