
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul  1 2026 13:12:50 IST (Jul  1 2026 07:42:50 UTC)

// Verification Directory fv/async_fifo 

module async_fifo(wreq, wclk, wrst_n, rreq, rclk, rrst_n, wdata, rdata,
     wfull, rempty);
  input wreq, wclk, wrst_n, rreq, rclk, rrst_n;
  input [7:0] wdata;
  output [7:0] rdata;
  output wfull, rempty;
  wire wreq, wclk, wrst_n, rreq, rclk, rrst_n;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire wfull, rempty;
  wire [3:0] wptr;
  wire [3:0] wq2_rptr;
  wire [3:0] rq2_wptr;
  wire [3:0] wq1_rptr;
  wire [3:0] rq1_wptr;
  wire [3:0] rptr;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[3] ;
  wire [4:0] rbin;
  wire [7:0] \mem[5] ;
  wire [4:0] wbin;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[7] ;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_5, n_9, n_11;
  wire n_12, n_13, n_16, n_17, n_18, n_19, n_20, n_25;
  wire n_31, n_32, n_34, n_35, n_37, n_39, n_43, n_47;
  wire n_49, n_53, n_55, n_56, n_57, n_58, n_59, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_88, n_90, n_91;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_100, n_101;
  wire n_102, n_104, n_108, n_109, n_111, n_112, n_114, n_117;
  wire n_118, n_120, n_121, n_124, n_125, n_130, n_133, n_134;
  wire n_135, n_136, n_138, n_142, n_145, n_148, n_151, n_152;
  wire n_154, n_156, n_158, n_159, n_169, n_170, n_172, n_173;
  wire n_179, n_183, n_188, n_189, n_190, n_191, n_192, n_199;
  wire n_200, n_202, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_215, n_217, n_218, n_228, n_230, n_231, n_235;
  wire n_238, n_239, n_241, n_242, n_244, n_246, n_269, n_271;
  wire n_280, n_285, n_289, n_291, n_296, n_306, n_321, n_323;
  wire n_325, n_346, n_349, n_350, n_352, n_354, n_355, n_356;
  wire n_364, n_376, n_377, n_380, n_381, n_382, n_387, n_390;
  wire n_391, n_392, n_400, n_405, n_406, n_422, n_423, n_428;
  wire n_431, n_435, n_436, n_437, n_440, n_441, n_443, n_444;
  wire n_449, n_450, n_451, n_452, n_459, n_460, n_466, n_467;
  wire n_468, n_469, n_470, n_471, n_472, n_475, n_476, n_478;
  wire n_479, n_480, n_481, n_482, n_483, n_485, n_486, n_487;
  wire n_488, n_489, n_490, n_493, n_495, n_496, n_503, n_504;
  wire n_505, n_506, n_508, n_509, n_510, n_511, n_512, n_513;
  wire n_514, n_515, n_516, n_520, n_521, n_522, n_524, n_525;
  wire n_529, n_530, n_531, n_532, n_533, n_536, n_539, n_542;
  wire n_544, n_545, n_552, n_553, n_554, n_555, n_556, n_557;
  wire n_558, n_559, n_629, n_630, n_631, n_633, n_634, n_636;
  wire n_637, n_638, n_650, n_651, n_657, n_659, n_661, n_664;
  wire n_665, n_666, n_668, n_669, n_711, n_712, n_713, n_715;
  wire n_721, n_728, n_735, n_737, n_742, n_743, n_744, n_745;
  wire n_746, n_747, n_748, n_749, n_750, n_751, n_753, n_792;
  wire n_793, n_794, n_795, n_799, n_800, n_806, n_807, n_810;
  wire n_811, n_814, n_815, n_819, n_821;
  DFFRHQX1 wfull_reg(.RN (wrst_n), .CK (wclk), .D (n_246), .Q (wfull));
  NOR2X1 g12412__2398(.A (n_242), .B (n_244), .Y (n_246));
  NAND3X1 g12414__6260(.A (wptr[3]), .B (n_231), .C (n_239), .Y
       (n_244));
  AOI31X1 g12415__8428(.A0 (wq2_rptr[2]), .A1 (wptr[2]), .A2
       (wq2_rptr[3]), .B0 (n_238), .Y (n_242));
  NAND2X1 g12416__5526(.A (n_235), .B (n_815), .Y (n_241));
  XNOR2X1 g12422__3680(.A (wq2_rptr[1]), .B (wptr[1]), .Y (n_239));
  NOR3X1 g12417__1617(.A (wq2_rptr[2]), .B (wptr[2]), .C (wq2_rptr[3]),
       .Y (n_238));
  AOI21X1 g12418__5122(.A0 (rq2_wptr[1]), .A1 (n_799), .B0 (n_228), .Y
       (n_235));
  XNOR2X1 g12425__6131(.A (wq2_rptr[0]), .B (wptr[0]), .Y (n_231));
  DFFRHQX1 \wq2_rptr_reg[1] (.RN (wrst_n), .CK (wclk), .D
       (wq1_rptr[1]), .Q (wq2_rptr[1]));
  DFFRHQX1 \wq2_rptr_reg[2] (.RN (wrst_n), .CK (wclk), .D
       (wq1_rptr[2]), .Q (wq2_rptr[2]));
  NOR2X1 g12431__1881(.A (rq2_wptr[0]), .B (n_800), .Y (n_228));
  DFFRX1 \wq2_rptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (wq1_rptr[3]),
       .Q (UNCONNECTED), .QN (wq2_rptr[3]));
  DFFRHQX1 \rq2_wptr_reg[1] (.RN (rrst_n), .CK (rclk), .D
       (rq1_wptr[1]), .Q (rq2_wptr[1]));
  DFFRHQX1 \rq2_wptr_reg[2] (.RN (rrst_n), .CK (rclk), .D
       (rq1_wptr[2]), .Q (rq2_wptr[2]));
  DFFRHQX1 \wq1_rptr_reg[2] (.RN (wrst_n), .CK (wclk), .D (rptr[2]), .Q
       (wq1_rptr[2]));
  DFFRHQX1 \wq1_rptr_reg[1] (.RN (wrst_n), .CK (wclk), .D (rptr[1]), .Q
       (wq1_rptr[1]));
  DFFRHQX1 \rq1_wptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (wptr[3]), .Q
       (rq1_wptr[3]));
  DFFRHQX1 \wq2_rptr_reg[0] (.RN (wrst_n), .CK (wclk), .D
       (wq1_rptr[0]), .Q (wq2_rptr[0]));
  DFFRHQX1 \wq1_rptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (rptr[3]), .Q
       (wq1_rptr[3]));
  DFFRHQX1 \rq2_wptr_reg[0] (.RN (rrst_n), .CK (rclk), .D
       (rq1_wptr[0]), .Q (rq2_wptr[0]));
  DFFRHQX1 \rq1_wptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (wptr[2]), .Q
       (rq1_wptr[2]));
  DFFRHQX1 \rq1_wptr_reg[1] (.RN (rrst_n), .CK (rclk), .D (wptr[1]), .Q
       (rq1_wptr[1]));
  DFFRHQX1 \rptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_387), .Q
       (rptr[2]));
  DFFRHQX1 \rptr_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_742), .Q
       (rptr[1]));
  DFFRHQX1 \rq1_wptr_reg[0] (.RN (rrst_n), .CK (rclk), .D (wptr[0]), .Q
       (rq1_wptr[0]));
  DFFRHQX1 \wq1_rptr_reg[0] (.RN (wrst_n), .CK (wclk), .D (rptr[0]), .Q
       (wq1_rptr[0]));
  DFFRHQX1 \rptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_715), .Q
       (rptr[3]));
  DFFRHQX1 \wptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_744), .Q
       (wptr[3]));
  SDFFQX1 \mem_reg[12][5] (.CK (wclk), .D (\mem[12] [5]), .SI
       (wdata[5]), .SE (n_218), .Q (\mem[12] [5]));
  DFFRHQX1 \wptr_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_192), .Q
       (wptr[1]));
  SDFFQX1 \mem_reg[10][1] (.CK (wclk), .D (\mem[10] [1]), .SI
       (wdata[1]), .SE (n_217), .Q (\mem[10] [1]));
  SDFFQX1 \mem_reg[12][7] (.CK (wclk), .D (\mem[12] [7]), .SI
       (wdata[7]), .SE (n_218), .Q (\mem[12] [7]));
  SDFFQX1 \mem_reg[10][0] (.CK (wclk), .D (\mem[10] [0]), .SI
       (wdata[0]), .SE (n_217), .Q (\mem[10] [0]));
  SDFFQX1 \mem_reg[12][0] (.CK (wclk), .D (\mem[12] [0]), .SI
       (wdata[0]), .SE (n_218), .Q (\mem[12] [0]));
  SDFFQX1 \mem_reg[12][1] (.CK (wclk), .D (\mem[12] [1]), .SI
       (wdata[1]), .SE (n_218), .Q (\mem[12] [1]));
  SDFFQX1 \mem_reg[12][2] (.CK (wclk), .D (\mem[12] [2]), .SI
       (wdata[2]), .SE (n_218), .Q (\mem[12] [2]));
  SDFFQX1 \mem_reg[12][3] (.CK (wclk), .D (\mem[12] [3]), .SI
       (wdata[3]), .SE (n_218), .Q (\mem[12] [3]));
  SDFFQX1 \mem_reg[12][4] (.CK (wclk), .D (\mem[12] [4]), .SI
       (wdata[4]), .SE (n_218), .Q (\mem[12] [4]));
  SDFFQX1 \mem_reg[12][6] (.CK (wclk), .D (\mem[12] [6]), .SI
       (wdata[6]), .SE (n_218), .Q (\mem[12] [6]));
  DFFRHQX1 \wptr_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_200), .Q
       (wptr[2]));
  SDFFQX1 \mem_reg[10][2] (.CK (wclk), .D (\mem[10] [2]), .SI
       (wdata[2]), .SE (n_217), .Q (\mem[10] [2]));
  SDFFQX1 \mem_reg[14][1] (.CK (wclk), .D (\mem[14] [1]), .SI
       (wdata[1]), .SE (n_215), .Q (\mem[14] [1]));
  SDFFQX1 \mem_reg[14][2] (.CK (wclk), .D (\mem[14] [2]), .SI
       (wdata[2]), .SE (n_215), .Q (\mem[14] [2]));
  SDFFQX1 \mem_reg[14][3] (.CK (wclk), .D (\mem[14] [3]), .SI
       (wdata[3]), .SE (n_215), .Q (\mem[14] [3]));
  SDFFQX1 \mem_reg[14][4] (.CK (wclk), .D (\mem[14] [4]), .SI
       (wdata[4]), .SE (n_215), .Q (\mem[14] [4]));
  SDFFQX1 \mem_reg[14][5] (.CK (wclk), .D (\mem[14] [5]), .SI
       (wdata[5]), .SE (n_215), .Q (\mem[14] [5]));
  SDFFQX1 \mem_reg[14][0] (.CK (wclk), .D (\mem[14] [0]), .SI
       (wdata[0]), .SE (n_215), .Q (\mem[14] [0]));
  SDFFQX1 \mem_reg[14][7] (.CK (wclk), .D (\mem[14] [7]), .SI
       (wdata[7]), .SE (n_215), .Q (\mem[14] [7]));
  SDFFQX1 \mem_reg[10][3] (.CK (wclk), .D (\mem[10] [3]), .SI
       (wdata[3]), .SE (n_217), .Q (\mem[10] [3]));
  SDFFQX1 \mem_reg[10][4] (.CK (wclk), .D (\mem[10] [4]), .SI
       (wdata[4]), .SE (n_217), .Q (\mem[10] [4]));
  SDFFQX1 \mem_reg[10][5] (.CK (wclk), .D (\mem[10] [5]), .SI
       (wdata[5]), .SE (n_217), .Q (\mem[10] [5]));
  SDFFQX1 \mem_reg[10][6] (.CK (wclk), .D (\mem[10] [6]), .SI
       (wdata[6]), .SE (n_217), .Q (\mem[10] [6]));
  SDFFQX1 \mem_reg[10][7] (.CK (wclk), .D (\mem[10] [7]), .SI
       (wdata[7]), .SE (n_217), .Q (\mem[10] [7]));
  SDFFQX1 \mem_reg[14][6] (.CK (wclk), .D (\mem[14] [6]), .SI
       (wdata[6]), .SE (n_215), .Q (\mem[14] [6]));
  SDFFQX1 \mem_reg[2][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[2] [4]),
       .SE (n_207), .Q (\mem[2] [4]));
  SDFFQX1 \mem_reg[11][2] (.CK (wclk), .D (\mem[11] [2]), .SI
       (wdata[2]), .SE (n_208), .Q (\mem[11] [2]));
  DFFRHQX1 \wptr_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_745), .Q
       (wptr[0]));
  SDFFQX1 \mem_reg[0][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[0] [5]),
       .SE (n_210), .Q (\mem[0] [5]));
  SDFFQX1 \mem_reg[0][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[0] [7]),
       .SE (n_210), .Q (\mem[0] [7]));
  SDFFQX1 \mem_reg[0][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[0] [2]),
       .SE (n_210), .Q (\mem[0] [2]));
  SDFFQX1 \mem_reg[13][7] (.CK (wclk), .D (\mem[13] [7]), .SI
       (wdata[7]), .SE (n_209), .Q (\mem[13] [7]));
  SDFFQX1 \mem_reg[13][4] (.CK (wclk), .D (\mem[13] [4]), .SI
       (wdata[4]), .SE (n_209), .Q (\mem[13] [4]));
  SDFFQX1 \mem_reg[11][6] (.CK (wclk), .D (\mem[11] [6]), .SI
       (wdata[6]), .SE (n_208), .Q (\mem[11] [6]));
  SDFFQX1 \mem_reg[8][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[8] [2]),
       .SE (n_202), .Q (\mem[8] [2]));
  SDFFQX1 \mem_reg[11][5] (.CK (wclk), .D (\mem[11] [5]), .SI
       (wdata[5]), .SE (n_208), .Q (\mem[11] [5]));
  SDFFQX1 \mem_reg[2][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[2] [0]),
       .SE (n_207), .Q (\mem[2] [0]));
  SDFFQX1 \mem_reg[2][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[2] [1]),
       .SE (n_207), .Q (\mem[2] [1]));
  SDFFQX1 \mem_reg[2][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[2] [2]),
       .SE (n_207), .Q (\mem[2] [2]));
  SDFFQX1 \mem_reg[2][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[2] [3]),
       .SE (n_207), .Q (\mem[2] [3]));
  SDFFQX1 \mem_reg[9][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[9] [6]),
       .SE (n_206), .Q (\mem[9] [6]));
  SDFFQX1 \mem_reg[2][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[2] [5]),
       .SE (n_207), .Q (\mem[2] [5]));
  SDFFQX1 \mem_reg[2][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[2] [6]),
       .SE (n_207), .Q (\mem[2] [6]));
  SDFFQX1 \mem_reg[9][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[9] [2]),
       .SE (n_206), .Q (\mem[9] [2]));
  SDFFQX1 \mem_reg[4][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[4] [0]),
       .SE (n_205), .Q (\mem[4] [0]));
  SDFFQX1 \mem_reg[4][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[4] [1]),
       .SE (n_205), .Q (\mem[4] [1]));
  SDFFQX1 \mem_reg[4][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[4] [2]),
       .SE (n_205), .Q (\mem[4] [2]));
  SDFFQX1 \mem_reg[4][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[4] [3]),
       .SE (n_205), .Q (\mem[4] [3]));
  SDFFQX1 \mem_reg[4][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[4] [4]),
       .SE (n_205), .Q (\mem[4] [4]));
  SDFFQX1 \mem_reg[4][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[4] [5]),
       .SE (n_205), .Q (\mem[4] [5]));
  SDFFQX1 \mem_reg[4][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[4] [6]),
       .SE (n_205), .Q (\mem[4] [6]));
  SDFFQX1 \mem_reg[6][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[6] [0]),
       .SE (n_204), .Q (\mem[6] [0]));
  SDFFQX1 \mem_reg[6][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[6] [1]),
       .SE (n_204), .Q (\mem[6] [1]));
  SDFFQX1 \mem_reg[6][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[6] [2]),
       .SE (n_204), .Q (\mem[6] [2]));
  SDFFQX1 \mem_reg[6][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[6] [3]),
       .SE (n_204), .Q (\mem[6] [3]));
  SDFFQX1 \mem_reg[6][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[6] [4]),
       .SE (n_204), .Q (\mem[6] [4]));
  SDFFQX1 \mem_reg[6][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[6] [5]),
       .SE (n_204), .Q (\mem[6] [5]));
  SDFFQX1 \mem_reg[6][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[6] [6]),
       .SE (n_204), .Q (\mem[6] [6]));
  DFFRHQX1 \rptr_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_183), .Q
       (rptr[0]));
  SDFFQX1 \mem_reg[8][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[8] [1]),
       .SE (n_202), .Q (\mem[8] [1]));
  SDFFQX1 \mem_reg[8][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[8] [3]),
       .SE (n_202), .Q (\mem[8] [3]));
  SDFFQX1 \mem_reg[8][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[8] [4]),
       .SE (n_202), .Q (\mem[8] [4]));
  SDFFQX1 \mem_reg[8][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[8] [5]),
       .SE (n_202), .Q (\mem[8] [5]));
  SDFFQX1 \mem_reg[4][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[4] [7]),
       .SE (n_205), .Q (\mem[4] [7]));
  SDFFQX1 \mem_reg[8][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[8] [7]),
       .SE (n_202), .Q (\mem[8] [7]));
  SDFFQX1 \mem_reg[9][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[9] [0]),
       .SE (n_206), .Q (\mem[9] [0]));
  SDFFQX1 \mem_reg[9][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[9] [1]),
       .SE (n_206), .Q (\mem[9] [1]));
  SDFFQX1 \mem_reg[9][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[9] [3]),
       .SE (n_206), .Q (\mem[9] [3]));
  SDFFQX1 \mem_reg[9][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[9] [4]),
       .SE (n_206), .Q (\mem[9] [4]));
  SDFFQX1 \mem_reg[9][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[9] [5]),
       .SE (n_206), .Q (\mem[9] [5]));
  SDFFQX1 \mem_reg[9][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[9] [7]),
       .SE (n_206), .Q (\mem[9] [7]));
  SDFFQX1 \mem_reg[11][4] (.CK (wclk), .D (\mem[11] [4]), .SI
       (wdata[4]), .SE (n_208), .Q (\mem[11] [4]));
  SDFFQX1 \mem_reg[11][7] (.CK (wclk), .D (\mem[11] [7]), .SI
       (wdata[7]), .SE (n_208), .Q (\mem[11] [7]));
  SDFFQX1 \mem_reg[13][2] (.CK (wclk), .D (\mem[13] [2]), .SI
       (wdata[2]), .SE (n_209), .Q (\mem[13] [2]));
  SDFFQX1 \mem_reg[13][0] (.CK (wclk), .D (\mem[13] [0]), .SI
       (wdata[0]), .SE (n_209), .Q (\mem[13] [0]));
  SDFFQX1 \mem_reg[6][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[6] [7]),
       .SE (n_204), .Q (\mem[6] [7]));
  SDFFQX1 \mem_reg[13][3] (.CK (wclk), .D (\mem[13] [3]), .SI
       (wdata[3]), .SE (n_209), .Q (\mem[13] [3]));
  SDFFQX1 \mem_reg[13][1] (.CK (wclk), .D (\mem[13] [1]), .SI
       (wdata[1]), .SE (n_209), .Q (\mem[13] [1]));
  SDFFQX1 \mem_reg[13][6] (.CK (wclk), .D (\mem[13] [6]), .SI
       (wdata[6]), .SE (n_209), .Q (\mem[13] [6]));
  SDFFQX1 \mem_reg[13][5] (.CK (wclk), .D (\mem[13] [5]), .SI
       (wdata[5]), .SE (n_209), .Q (\mem[13] [5]));
  SDFFQX1 \mem_reg[0][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[0] [4]),
       .SE (n_210), .Q (\mem[0] [4]));
  SDFFQX1 \mem_reg[0][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[0] [6]),
       .SE (n_210), .Q (\mem[0] [6]));
  SDFFQX1 \mem_reg[0][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[0] [0]),
       .SE (n_210), .Q (\mem[0] [0]));
  SDFFQX1 \mem_reg[0][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[0] [1]),
       .SE (n_210), .Q (\mem[0] [1]));
  SDFFQX1 \mem_reg[0][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[0] [3]),
       .SE (n_210), .Q (\mem[0] [3]));
  SDFFQX1 \mem_reg[11][0] (.CK (wclk), .D (\mem[11] [0]), .SI
       (wdata[0]), .SE (n_208), .Q (\mem[11] [0]));
  SDFFQX1 \mem_reg[11][1] (.CK (wclk), .D (\mem[11] [1]), .SI
       (wdata[1]), .SE (n_208), .Q (\mem[11] [1]));
  SDFFQX1 \mem_reg[11][3] (.CK (wclk), .D (\mem[11] [3]), .SI
       (wdata[3]), .SE (n_208), .Q (\mem[11] [3]));
  SDFFQX1 \mem_reg[8][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[8] [0]),
       .SE (n_202), .Q (\mem[8] [0]));
  SDFFQX1 \mem_reg[2][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[2] [7]),
       .SE (n_207), .Q (\mem[2] [7]));
  SDFFQX1 \mem_reg[8][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[8] [6]),
       .SE (n_202), .Q (\mem[8] [6]));
  XNOR2X1 g12521__5477(.A (n_191), .B (n_199), .Y (n_200));
  XNOR2X1 g12520__8428(.A (n_179), .B (n_191), .Y (n_192));
  SDFFQX1 \mem_reg[1][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[1] [0]),
       .SE (n_190), .Q (\mem[1] [0]));
  SDFFQX1 \mem_reg[1][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[1] [1]),
       .SE (n_190), .Q (\mem[1] [1]));
  SDFFQX1 \mem_reg[1][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[1] [4]),
       .SE (n_190), .Q (\mem[1] [4]));
  SDFFQX1 \mem_reg[1][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[1] [7]),
       .SE (n_190), .Q (\mem[1] [7]));
  SDFFQX1 \mem_reg[1][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[1] [6]),
       .SE (n_190), .Q (\mem[1] [6]));
  SDFFQX1 \mem_reg[3][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[3] [0]),
       .SE (n_189), .Q (\mem[3] [0]));
  SDFFQX1 \mem_reg[3][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[3] [1]),
       .SE (n_189), .Q (\mem[3] [1]));
  SDFFQX1 \mem_reg[3][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[3] [2]),
       .SE (n_189), .Q (\mem[3] [2]));
  SDFFQX1 \mem_reg[3][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[3] [4]),
       .SE (n_189), .Q (\mem[3] [4]));
  SDFFQX1 \mem_reg[3][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[3] [5]),
       .SE (n_189), .Q (\mem[3] [5]));
  DFFRHQX1 \rbin_reg[4] (.RN (rrst_n), .CK (rclk), .D (n_158), .Q
       (rbin[4]));
  SDFFQX1 \mem_reg[5][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[5] [0]),
       .SE (n_188), .Q (\mem[5] [0]));
  SDFFQX1 \mem_reg[5][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[5] [1]),
       .SE (n_188), .Q (\mem[5] [1]));
  SDFFQX1 \mem_reg[5][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[5] [2]),
       .SE (n_188), .Q (\mem[5] [2]));
  SDFFQX1 \mem_reg[5][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[5] [4]),
       .SE (n_188), .Q (\mem[5] [4]));
  SDFFQX1 \mem_reg[5][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[5] [5]),
       .SE (n_188), .Q (\mem[5] [5]));
  SDFFQX1 \mem_reg[5][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[5] [6]),
       .SE (n_188), .Q (\mem[5] [6]));
  SDFFQX1 \mem_reg[5][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[5] [7]),
       .SE (n_188), .Q (\mem[5] [7]));
  SDFFQX1 \mem_reg[5][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[5] [3]),
       .SE (n_188), .Q (\mem[5] [3]));
  SDFFQX1 \mem_reg[1][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[1] [3]),
       .SE (n_190), .Q (\mem[1] [3]));
  SDFFQX1 \mem_reg[3][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[3] [3]),
       .SE (n_189), .Q (\mem[3] [3]));
  SDFFQX1 \mem_reg[1][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[1] [5]),
       .SE (n_190), .Q (\mem[1] [5]));
  SDFFQX1 \mem_reg[1][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[1] [2]),
       .SE (n_190), .Q (\mem[1] [2]));
  SDFFQX1 \mem_reg[3][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[3] [7]),
       .SE (n_189), .Q (\mem[3] [7]));
  SDFFQX1 \mem_reg[3][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[3] [6]),
       .SE (n_189), .Q (\mem[3] [6]));
  DFFRHQX1 \wbin_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_159), .Q
       (wbin[2]));
  INVXL g12600(.A (n_800), .Y (n_183));
  NOR2XL g12607__6131(.A (n_124), .B (n_142), .Y (n_173));
  NOR2XL g12608__1881(.A (n_467), .B (n_125), .Y (n_172));
  SDFFQX1 \mem_reg[15][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[15]
       [4]), .SE (n_170), .Q (\mem[15] [4]));
  SDFFQX1 \mem_reg[15][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[15]
       [0]), .SE (n_170), .Q (\mem[15] [0]));
  DFFRHQX1 \rbin_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_169), .Q
       (rbin[3]));
  SDFFQX1 \mem_reg[15][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[15]
       [2]), .SE (n_170), .Q (\mem[15] [2]));
  SDFFQX1 \mem_reg[15][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[15]
       [1]), .SE (n_170), .Q (\mem[15] [1]));
  SDFFQX1 \mem_reg[15][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[15]
       [6]), .SE (n_170), .Q (\mem[15] [6]));
  SDFFQX1 \mem_reg[15][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[15]
       [7]), .SE (n_170), .Q (\mem[15] [7]));
  SDFFQX1 \mem_reg[15][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[15]
       [3]), .SE (n_170), .Q (\mem[15] [3]));
  SDFFQX1 \mem_reg[15][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[15]
       [5]), .SE (n_170), .Q (\mem[15] [5]));
  DFFRHQX1 \rbin_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_321), .Q
       (rbin[2]));
  INVX1 g12640(.A (n_191), .Y (n_159));
  INVXL g12639(.A (n_728), .Y (n_158));
  SDFFQX1 \mem_reg[7][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[7] [1]),
       .SE (n_154), .Q (\mem[7] [1]));
  SDFFQX1 \mem_reg[7][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[7] [0]),
       .SE (n_154), .Q (\mem[7] [0]));
  SDFFQX1 \mem_reg[7][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[7] [7]),
       .SE (n_154), .Q (\mem[7] [7]));
  SDFFQX1 \mem_reg[7][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[7] [4]),
       .SE (n_154), .Q (\mem[7] [4]));
  SDFFQX1 \mem_reg[7][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[7] [6]),
       .SE (n_154), .Q (\mem[7] [6]));
  SDFFQX1 \mem_reg[7][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[7] [3]),
       .SE (n_154), .Q (\mem[7] [3]));
  SDFFQX1 \mem_reg[7][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[7] [5]),
       .SE (n_154), .Q (\mem[7] [5]));
  SDFFQX1 \mem_reg[7][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[7] [2]),
       .SE (n_154), .Q (\mem[7] [2]));
  DFFRHQX1 \rbin_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_737), .Q
       (rbin[1]));
  NOR2X1 g12675__7410(.A (n_133), .B (n_152), .Y (n_217));
  NOR2X1 g12669__6417(.A (n_93), .B (n_152), .Y (n_215));
  NOR2X1 g12673__5477(.A (n_135), .B (n_152), .Y (n_218));
  OAI2BB1XL g12685__2398(.A0N (\mem[7] [5]), .A1N (n_400), .B0 (n_96),
       .Y (n_151));
  OAI2BB1XL g12687__6260(.A0N (\mem[7] [2]), .A1N (n_400), .B0 (n_97),
       .Y (n_148));
  AOI21XL g12633__5526(.A0 (n_452), .A1 (n_79), .B0 (n_136), .Y
       (n_145));
  AOI21XL g12631__3680(.A0 (n_47), .A1 (n_69), .B0 (n_376), .Y (n_142));
  OAI2BB1X1 g12621__1705(.A0N (n_49), .A1N (n_78), .B0 (n_130), .Y
       (n_138));
  INVX1 g12642(.A (n_661), .Y (n_169));
  NAND2X1 g12635__8246(.A (n_154), .B (n_94), .Y (n_199));
  DFFRHQX1 \wbin_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_179), .Q
       (wbin[1]));
  NOR2X1 g12694__7098(.A (n_135), .B (n_746), .Y (n_209));
  NAND2X1 g12670__6131(.A (n_117), .B (n_134), .Y (n_210));
  NAND2X1 g12674__1881(.A (n_108), .B (n_134), .Y (n_207));
  NAND2X1 g12693__5115(.A (n_17), .B (n_134), .Y (n_204));
  NOR2X1 g12692__7482(.A (n_133), .B (n_746), .Y (n_208));
  AOI21XL g12648__2346(.A0 (n_32), .A1 (n_66), .B0 (n_747), .Y (n_125));
  AOI21XL g12649__1666(.A0 (n_39), .A1 (n_63), .B0 (n_747), .Y (n_124));
  AOI21XL g12652__5477(.A0 (n_352), .A1 (n_73), .B0 (n_747), .Y
       (n_121));
  OAI2BB1XL g12684__2398(.A0N (\mem[7] [3]), .A1N (n_400), .B0 (n_98),
       .Y (n_120));
  DFFRHQX1 \wbin_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_114), .Q
       (wbin[0]));
  XNOR2X1 g12656__6260(.A (n_0), .B (n_90), .Y (n_156));
  AOI211XL g12658__4319(.A0 (wbin[2]), .A1 (n_95), .B0 (n_118), .C0
       (n_84), .Y (n_191));
  NAND2X1 g12668__6783(.A (n_118), .B (n_134), .Y (n_205));
  NAND2X1 g12666__3680(.A (n_117), .B (n_109), .Y (n_202));
  OR2X1 g12667__1617(.A (n_3), .B (n_746), .Y (n_206));
  NOR2X1 g12661__5122(.A (n_112), .B (n_88), .Y (n_111));
  INVX1 g12696(.A (n_109), .Y (n_152));
  NAND2X2 g12672__6131(.A (n_108), .B (n_102), .Y (n_189));
  NOR2X1 g12663__4733(.A (n_112), .B (n_65), .Y (n_104));
  DFFRHQX1 \rbin_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_72), .Q
       (rbin[0]));
  NAND2X2 g12671__6161(.A (n_117), .B (n_102), .Y (n_190));
  NAND2X2 g12676__9315(.A (n_118), .B (n_102), .Y (n_188));
  NAND2XL g12703__9945(.A (\mem[14] [6]), .B (n_377), .Y (n_101));
  NAND2XL g12702__2883(.A (\mem[14] [1]), .B (n_377), .Y (n_100));
  NAND2XL g12699__2346(.A (\mem[14] [3]), .B (n_377), .Y (n_98));
  NAND2XL g12700__1666(.A (\mem[14] [2]), .B (n_377), .Y (n_97));
  NAND2XL g12701__7410(.A (\mem[14] [5]), .B (n_377), .Y (n_96));
  XNOR2X1 g12690__5477(.A (wbin[1]), .B (n_95), .Y (n_179));
  OAI21X1 g12682__2398(.A0 (n_93), .A1 (n_95), .B0 (wbin[3]), .Y
       (n_94));
  OAI2BB1X1 g12727__6260(.A0N (n_19), .A1N (n_53), .B0 (n_91), .Y
       (n_114));
  NOR2X1 g12728__4319(.A (n_18), .B (n_91), .Y (n_109));
  NOR2X2 g12729__5526(.A (wbin[3]), .B (n_91), .Y (n_134));
  INVX1 g12731(.A (n_90), .Y (n_170));
  AOI22X1 g12697__3680(.A0 (\mem[1] [6]), .A1 (n_406), .B0 (\mem[8]
       [6]), .B1 (n_86), .Y (n_88));
  AOI22XL g12706__1617(.A0 (\mem[7] [0]), .A1 (n_406), .B0 (\mem[14]
       [0]), .B1 (n_86), .Y (n_85));
  NOR2X1 g12707__2802(.A (n_133), .B (n_95), .Y (n_84));
  NAND3X1 g12708__1705(.A (\mem[8] [4]), .B (n_440), .C (n_86), .Y
       (n_83));
  AOI22X1 g12709__5122(.A0 (\mem[1] [5]), .A1 (n_406), .B0 (\mem[8]
       [5]), .B1 (n_86), .Y (n_82));
  AOI22XL g12710__8246(.A0 (\mem[5] [2]), .A1 (n_406), .B0 (\mem[12]
       [2]), .B1 (n_86), .Y (n_81));
  AOI22X1 g12714__7098(.A0 (\mem[1] [0]), .A1 (n_406), .B0 (\mem[8]
       [0]), .B1 (n_86), .Y (n_80));
  AOI22XL g12717__6131(.A0 (\mem[3] [6]), .A1 (n_406), .B0 (\mem[10]
       [6]), .B1 (n_86), .Y (n_79));
  AOI22XL g12719__1881(.A0 (\mem[3] [2]), .A1 (n_406), .B0 (\mem[10]
       [2]), .B1 (n_86), .Y (n_78));
  AOI22X1 g12720__5115(.A0 (\mem[1] [2]), .A1 (n_406), .B0 (\mem[8]
       [2]), .B1 (n_86), .Y (n_77));
  AOI22XL g12733__6161(.A0 (\mem[5] [6]), .A1 (n_406), .B0 (\mem[12]
       [6]), .B1 (n_86), .Y (n_73));
  INVXL g12730(.A (n_71), .Y (n_72));
  AOI22XL g12732__9315(.A0 (\mem[3] [5]), .A1 (n_406), .B0 (\mem[10]
       [5]), .B1 (n_86), .Y (n_70));
  NOR2X1 g12726__9945(.A (wbin[3]), .B (n_95), .Y (n_102));
  AOI22XL g12750__2883(.A0 (\mem[7] [7]), .A1 (n_406), .B0 (\mem[14]
       [7]), .B1 (n_86), .Y (n_69));
  AOI22XL g12736__2346(.A0 (\mem[3] [1]), .A1 (n_406), .B0 (\mem[10]
       [1]), .B1 (n_86), .Y (n_68));
  AOI22XL g12740__7410(.A0 (\mem[5] [0]), .A1 (n_406), .B0 (\mem[12]
       [0]), .B1 (n_86), .Y (n_66));
  AOI22XL g12741__6417(.A0 (\mem[1] [1]), .A1 (n_406), .B0 (\mem[8]
       [1]), .B1 (n_86), .Y (n_65));
  AOI22X1 g12742__5477(.A0 (\mem[2] [7]), .A1 (n_544), .B0 (\mem[10]
       [7]), .B1 (n_86), .Y (n_64));
  AOI22XL g12743__2398(.A0 (\mem[5] [7]), .A1 (n_406), .B0 (\mem[12]
       [7]), .B1 (n_86), .Y (n_63));
  AOI22XL g12747__5107(.A0 (\mem[3] [0]), .A1 (n_406), .B0 (\mem[10]
       [0]), .B1 (n_86), .Y (n_62));
  AOI22X1 g12748__6260(.A0 (\mem[5] [4]), .A1 (n_406), .B0 (\mem[12]
       [4]), .B1 (n_86), .Y (n_61));
  AOI22XL g12752__8428(.A0 (\mem[1] [7]), .A1 (n_406), .B0 (\mem[8]
       [7]), .B1 (n_86), .Y (n_59));
  AOI22XL g12753__5526(.A0 (\mem[3] [4]), .A1 (n_406), .B0 (\mem[10]
       [4]), .B1 (n_86), .Y (n_58));
  AOI22XL g12755__6783(.A0 (\mem[3] [3]), .A1 (n_406), .B0 (\mem[10]
       [3]), .B1 (n_86), .Y (n_57));
  AOI22X1 g12760__3680(.A0 (\mem[5] [3]), .A1 (n_406), .B0 (\mem[12]
       [3]), .B1 (n_86), .Y (n_56));
  AOI22XL g12761__1617(.A0 (\mem[1] [3]), .A1 (n_406), .B0 (\mem[8]
       [3]), .B1 (n_86), .Y (n_55));
  NOR2X1 g12764__1705(.A (n_25), .B (n_13), .Y (n_90));
  OR2X1 g12763__5122(.A (n_53), .B (n_20), .Y (n_154));
  AOI22XL g12705__7098(.A0 (\mem[2] [2]), .A1 (n_544), .B0 (\mem[11]
       [2]), .B1 (n_636), .Y (n_49));
  AOI22X1 g12712__1881(.A0 (\mem[6] [7]), .A1 (n_544), .B0 (\mem[15]
       [7]), .B1 (n_296), .Y (n_47));
  AOI22X1 g12704__6161(.A0 (n_544), .A1 (\mem[2] [0]), .B0 (\mem[11]
       [0]), .B1 (n_296), .Y (n_43));
  AOI22X1 g12738__2883(.A0 (n_544), .A1 (\mem[4] [7]), .B0 (\mem[13]
       [7]), .B1 (n_296), .Y (n_39));
  AOI22X1 g12744__1666(.A0 (\mem[4] [4]), .A1 (n_544), .B0 (\mem[13]
       [4]), .B1 (n_289), .Y (n_37));
  AOI22X1 g12759__6417(.A0 (\mem[4] [3]), .A1 (n_544), .B0 (\mem[13]
       [3]), .B1 (n_289), .Y (n_35));
  AOI22XL g12751__5477(.A0 (\mem[2] [3]), .A1 (n_544), .B0 (\mem[11]
       [3]), .B1 (n_296), .Y (n_34));
  AOI22X1 g12756__5107(.A0 (\mem[4] [0]), .A1 (n_544), .B0 (\mem[13]
       [0]), .B1 (n_296), .Y (n_32));
  AOI22X1 g12757__6260(.A0 (\mem[0] [3]), .A1 (n_544), .B0 (\mem[9]
       [3]), .B1 (n_636), .Y (n_31));
  MXI2XL g12762__6783(.A (n_306), .B (n_638), .S0 (n_9), .Y (n_71));
  NAND2X2 g12778__3680(.A (wreq), .B (n_12), .Y (n_91));
  NAND2X1 g12766__6131(.A (wbin[3]), .B (n_16), .Y (n_25));
  NAND3X1 g12774__7482(.A (n_19), .B (n_18), .C (n_17), .Y (n_20));
  NAND2X4 g12773__6161(.A (wreq), .B (n_16), .Y (n_95));
  NAND2X1 g12767__9945(.A (wreq), .B (n_17), .Y (n_13));
  NOR2X2 g12801__2883(.A (wfull), .B (n_19), .Y (n_12));
  INVX1 g12784(.A (n_133), .Y (n_108));
  INVX1 g12783(.A (n_118), .Y (n_135));
  INVX1 g12796(.A (n_136), .Y (n_130));
  INVX3 g12800(.A (n_11), .Y (n_86));
  NAND2X1 g12789__2346(.A (n_1), .B (rreq), .Y (n_9));
  INVX1 g12795(.A (n_17), .Y (n_93));
  NAND2X1 g12792__6417(.A (wbin[1]), .B (n_5), .Y (n_133));
  NOR2X1 g12791__5477(.A (wbin[1]), .B (n_5), .Y (n_118));
  INVX3 g12797(.A (n_440), .Y (n_112));
  INVXL g12782(.A (n_117), .Y (n_3));
  NOR2X2 g12787__6260(.A (wfull), .B (n_2), .Y (n_16));
  NAND2X1 g12809__4319(.A (rbin[3]), .B (n_629), .Y (n_11));
  NAND2X1 g12804__5526(.A (n_792), .B (n_721), .Y (n_136));
  CLKAND2X2 g12803__1617(.A (wbin[2]), .B (wbin[1]), .Y (n_17));
  NAND2BX1 g12788__1705(.AN (wfull), .B (wreq), .Y (n_53));
  INVX1 g12812(.A (n_2), .Y (n_19));
  NOR2X1 g12790__5122(.A (wbin[2]), .B (wbin[1]), .Y (n_117));
  INVX1 g12814(.A (wbin[2]), .Y (n_5));
  INVX1 g12813(.A (wbin[0]), .Y (n_2));
  INVX1 fopt12984(.A (n_544), .Y (n_269));
  INVX1 fopt12985(.A (n_544), .Y (n_271));
  INVX1 fopt12990(.A (rbin[3]), .Y (n_280));
  INVX3 fopt12996(.A (n_291), .Y (n_289));
  INVX3 fopt13000(.A (n_291), .Y (n_296));
  INVXL fopt10(.A (n_638), .Y (n_306));
  XNOR2X1 g12659__13006(.A (n_721), .B (n_659), .Y (n_321));
  NAND2XL g12606__13008(.A (n_321), .B (n_661), .Y (n_323));
  NOR2XL g12605__13010(.A (n_321), .B (n_661), .Y (n_325));
  NOR3BX1 g124(.AN (\mem[9] [6]), .B (n_112), .C (n_291), .Y (n_346));
  AOI22X1 g13011(.A0 (\mem[4] [6]), .A1 (n_544), .B0 (\mem[13] [6]),
       .B1 (n_289), .Y (n_352));
  INVX1 g13013(.A (n_629), .Y (n_349));
  INVX2 g13014(.A (n_280), .Y (n_350));
  AOI21X1 g67(.A0 (n_668), .A1 (n_637), .B0 (n_355), .Y (n_356));
  NOR2BX1 g69(.AN (\mem[1] [4]), .B (n_354), .Y (n_355));
  INVXL g70(.A (n_406), .Y (n_354));
  AOI22X1 g13018(.A0 (\mem[11] [4]), .A1 (n_636), .B0 (\mem[2] [4]),
       .B1 (n_544), .Y (n_364));
  NOR2X1 g28(.A (n_11), .B (n_376), .Y (n_377));
  INVX3 g29(.A (n_651), .Y (n_376));
  NAND3XL g111(.A (n_138), .B (n_751), .C (n_382), .Y (rdata[2]));
  NOR2XL g112(.A (n_380), .B (n_381), .Y (n_382));
  AOI21X1 g114(.A0 (n_77), .A1 (n_545), .B0 (n_112), .Y (n_380));
  AOI21XL g113(.A0 (n_451), .A1 (n_81), .B0 (n_747), .Y (n_381));
  OR2XL g118(.A (n_325), .B (n_650), .Y (n_387));
  NAND2XL g98(.A (n_392), .B (n_172), .Y (rdata[0]));
  NOR2XL g99(.A (n_390), .B (n_391), .Y (n_392));
  AOI21XL g101(.A0 (n_80), .A1 (n_470), .B0 (n_112), .Y (n_390));
  AOI21XL g100(.A0 (n_43), .A1 (n_62), .B0 (n_136), .Y (n_391));
  NOR2BX1 g19(.AN (n_405), .B (n_376), .Y (n_400));
  BUFX6 g24(.A (n_405), .Y (n_406));
  NOR2X1 g25(.A (rbin[3]), .B (n_629), .Y (n_405));
  AOI21XL g88(.A0 (rq2_wptr[3]), .A1 (n_661), .B0 (n_422), .Y (n_423));
  NOR2XL g89(.A (rq2_wptr[3]), .B (n_661), .Y (n_422));
  NAND2BX2 g212(.AN (rempty), .B (rreq), .Y (n_428));
  NOR2BX1 g211(.AN (rreq), .B (n_285), .Y (n_431));
  NAND2X1 g209(.A (n_633), .B (n_436), .Y (n_437));
  NOR2BX1 g210(.AN (rreq), .B (n_435), .Y (n_436));
  INVX1 g215(.A (n_651), .Y (n_435));
  NOR2X1 g97(.A (rbin[1]), .B (rbin[2]), .Y (n_440));
  NAND2XL g92(.A (n_444), .B (n_173), .Y (rdata[7]));
  NOR2XL g93(.A (n_441), .B (n_443), .Y (n_444));
  AOI21XL g94(.A0 (n_64), .A1 (n_468), .B0 (n_136), .Y (n_441));
  AOI21XL g95(.A0 (n_472), .A1 (n_59), .B0 (n_112), .Y (n_443));
  AOI21XL g13035(.A0 (n_449), .A1 (n_70), .B0 (n_136), .Y (n_450));
  AOI22XL g13036(.A0 (\mem[11] [5]), .A1 (n_636), .B0 (\mem[2] [5]),
       .B1 (n_544), .Y (n_449));
  AOI22XL g13037(.A0 (\mem[13] [2]), .A1 (n_636), .B0 (\mem[4] [2]),
       .B1 (n_544), .Y (n_451));
  AOI22XL g13038(.A0 (\mem[11] [6]), .A1 (n_636), .B0 (\mem[2] [6]),
       .B1 (n_544), .Y (n_452));
  AOI21X1 g197(.A0 (\mem[15] [4]), .A1 (n_529), .B0 (n_459), .Y
       (n_460));
  NOR3BX1 g198(.AN (\mem[6] [4]), .B (n_376), .C (n_271), .Y (n_459));
  CLKINVX6 g139(.A (n_636), .Y (n_291));
  AOI21XL g132(.A0 (n_466), .A1 (n_85), .B0 (n_376), .Y (n_467));
  AOI22XL g13044(.A0 (\mem[15] [0]), .A1 (n_636), .B0 (\mem[6] [0]),
       .B1 (n_544), .Y (n_466));
  AOI22XL g13045(.A0 (\mem[11] [7]), .A1 (n_636), .B0 (\mem[3] [7]),
       .B1 (n_406), .Y (n_468));
  AOI21X1 g13046(.A0 (\mem[9] [0]), .A1 (n_636), .B0 (n_469), .Y
       (n_470));
  NOR3BXL g137(.AN (\mem[0] [0]), .B (n_349), .C (n_350), .Y (n_469));
  AOI21XL g13047(.A0 (\mem[9] [7]), .A1 (n_636), .B0 (n_471), .Y
       (n_472));
  NOR3BXL g138(.AN (\mem[0] [7]), .B (n_349), .C (n_350), .Y (n_471));
  AOI21XL g61(.A0 (n_475), .A1 (n_68), .B0 (n_136), .Y (n_476));
  AOI22XL g62(.A0 (\mem[11] [1]), .A1 (n_636), .B0 (\mem[2] [1]), .B1
       (n_544), .Y (n_475));
  NOR2XL g159(.A (n_450), .B (n_482), .Y (n_483));
  AOI2BB1XL g160(.A0N (n_479), .A1N (n_481), .B0 (n_747), .Y (n_482));
  OAI2BB1X1 g162(.A0N (\mem[12] [5]), .A1N (n_86), .B0 (n_478), .Y
       (n_479));
  NAND2XL g164(.A (\mem[5] [5]), .B (n_406), .Y (n_478));
  OAI2BB1XL g161(.A0N (\mem[13] [5]), .A1N (n_289), .B0 (n_480), .Y
       (n_481));
  NAND2X1 g165(.A (\mem[4] [5]), .B (n_544), .Y (n_480));
  NOR2XL g13049(.A (n_476), .B (n_489), .Y (n_490));
  AOI2BB1XL g13050(.A0N (n_486), .A1N (n_488), .B0 (n_747), .Y (n_489));
  OAI2BB1X1 g13051(.A0N (\mem[12] [1]), .A1N (n_86), .B0 (n_485), .Y
       (n_486));
  NAND2XL g13052(.A (\mem[5] [1]), .B (n_406), .Y (n_485));
  OAI2BB1XL g13053(.A0N (\mem[13] [1]), .A1N (n_289), .B0 (n_487), .Y
       (n_488));
  NAND2X1 g13054(.A (\mem[4] [1]), .B (n_544), .Y (n_487));
  NOR2XL g13058(.A (n_145), .B (n_121), .Y (n_493));
  AOI21X1 g109(.A0 (n_61), .A1 (n_37), .B0 (n_747), .Y (n_495));
  AOI21XL g108(.A0 (n_364), .A1 (n_58), .B0 (n_136), .Y (n_496));
  NAND3XL g13063(.A (n_506), .B (n_750), .C (n_483), .Y (rdata[5]));
  AOI211XL g120(.A0 (\mem[9] [5]), .A1 (n_503), .B0 (n_504), .C0
       (n_505), .Y (n_506));
  NOR2X1 g13064(.A (n_112), .B (n_291), .Y (n_503));
  NOR3BX1 g123(.AN (\mem[0] [5]), .B (n_112), .C (n_269), .Y (n_504));
  NOR2X1 g126(.A (n_112), .B (n_82), .Y (n_505));
  NOR3X1 g13065(.A (n_508), .B (n_509), .C (n_104), .Y (n_510));
  NOR3BXL g122(.AN (\mem[0] [1]), .B (n_112), .C (n_269), .Y (n_508));
  AND2XL g121(.A (\mem[9] [1]), .B (n_503), .Y (n_509));
  AOI211XL g119(.A0 (\mem[0] [6]), .A1 (n_511), .B0 (n_346), .C0
       (n_111), .Y (n_512));
  NOR2X1 g13066(.A (n_112), .B (n_269), .Y (n_511));
  NAND3XL g75(.A (n_513), .B (n_515), .C (n_516), .Y (rdata[4]));
  AOI21X1 g76(.A0 (\mem[7] [4]), .A1 (n_400), .B0 (n_748), .Y (n_513));
  NOR2BX1 g77(.AN (n_460), .B (n_514), .Y (n_515));
  NOR2XL g79(.A (n_112), .B (n_356), .Y (n_514));
  NOR2XL g78(.A (n_495), .B (n_496), .Y (n_516));
  NAND3XL g80(.A (n_522), .B (n_512), .C (n_493), .Y (rdata[6]));
  AOI211X1 g81(.A0 (\mem[15] [6]), .A1 (n_529), .B0 (n_520), .C0
       (n_521), .Y (n_522));
  NOR3BXL g13069(.AN (\mem[6] [6]), .B (n_376), .C (n_271), .Y (n_520));
  OAI2BB1X1 g13070(.A0N (\mem[7] [6]), .A1N (n_400), .B0 (n_101), .Y
       (n_521));
  AOI21XL g13072(.A0 (n_57), .A1 (n_34), .B0 (n_524), .Y (n_525));
  INVXL g103(.A (n_130), .Y (n_524));
  NOR2X2 g183(.A (n_376), .B (n_291), .Y (n_529));
  NAND3XL g169(.A (n_533), .B (n_510), .C (n_490), .Y (rdata[1]));
  NOR3BX1 g170(.AN (n_530), .B (n_531), .C (n_532), .Y (n_533));
  NAND2X1 g180(.A (\mem[15] [1]), .B (n_529), .Y (n_530));
  NOR3BXL g174(.AN (\mem[6] [1]), .B (n_376), .C (n_271), .Y (n_531));
  OAI2BB1X1 g182(.A0N (\mem[7] [1]), .A1N (n_400), .B0 (n_100), .Y
       (n_532));
  NOR3BXL g179(.AN (\mem[6] [3]), .B (n_376), .C (n_271), .Y (n_536));
  NOR3BXL g175(.AN (\mem[6] [5]), .B (n_376), .C (n_271), .Y (n_539));
  NOR3BXL g177(.AN (\mem[6] [2]), .B (n_376), .C (n_271), .Y (n_542));
  NOR2X6 g35(.A (n_350), .B (n_349), .Y (n_544));
  AOI22X1 g34(.A0 (\mem[0] [2]), .A1 (n_544), .B0 (\mem[9] [2]), .B1
       (n_296), .Y (n_545));
  NOR2XL g104(.A (n_241), .B (n_555), .Y (n_556));
  NAND2X1 g105(.A (n_807), .B (n_554), .Y (n_555));
  NOR2X1 g106(.A (n_552), .B (n_553), .Y (n_554));
  NOR3BXL g13080(.AN (rq2_wptr[2]), .B (n_325), .C (n_650), .Y (n_552));
  AOI2BB1XL g107(.A0N (n_325), .A1N (n_650), .B0 (rq2_wptr[2]), .Y
       (n_553));
  NAND3BXL g13081(.AN (n_525), .B (n_749), .C (n_559), .Y (rdata[3]));
  NOR2XL g13082(.A (n_557), .B (n_558), .Y (n_559));
  AOI21X1 g13083(.A0 (n_56), .A1 (n_35), .B0 (n_747), .Y (n_557));
  AOI21XL g13084(.A0 (n_31), .A1 (n_55), .B0 (n_112), .Y (n_558));
  INVX2 fopt13152(.A (rbin[0]), .Y (n_629));
  INVXL fopt13153(.A (n_629), .Y (n_630));
  INVX1 fopt13155(.A (n_630), .Y (n_631));
  NOR2X1 g13156(.A (rempty), .B (n_631), .Y (n_633));
  BUFX3 fopt13158(.A (n_629), .Y (n_634));
  NOR2X6 g13159(.A (n_664), .B (n_634), .Y (n_636));
  OAI2BB1X1 g12775__13160(.A0N (\mem[0] [4]), .A1N (n_634), .B0
       (n_669), .Y (n_637));
  INVXL fopt13161(.A (n_634), .Y (n_638));
  INVX1 fopt(.A (n_323), .Y (n_650));
  CLKAND2X3 g12(.A (rbin[1]), .B (rbin[2]), .Y (n_651));
  INVX1 g14(.A (rbin[1]), .Y (n_285));
  NOR2X1 g18(.A (n_657), .B (n_743), .Y (n_659));
  NAND2X1 g13171(.A (n_792), .B (rreq), .Y (n_657));
  INVX1 fopt13174(.A (rbin[3]), .Y (n_664));
  NAND2X1 g12768__13175(.A (n_651), .B (n_665), .Y (n_666));
  INVX2 fopt13176(.A (n_664), .Y (n_665));
  CLKXOR2X1 g12660__13177(.A (n_665), .B (n_437), .Y (n_661));
  OAI2BB1X1 g13178(.A0N (\mem[9] [4]), .A1N (n_630), .B0 (n_665), .Y
       (n_668));
  INVXL fopt13179(.A (n_665), .Y (n_669));
  AOI2BB1X1 g13213(.A0N (rbin[4]), .A1N (n_711), .B0 (n_712), .Y
       (n_713));
  NOR2BX1 g13214(.AN (n_793), .B (n_666), .Y (n_711));
  CLKAND2X2 g13215(.A (rbin[4]), .B (n_711), .Y (n_712));
  OAI22XL g13216(.A0 (n_169), .A1 (n_728), .B0 (n_661), .B1 (n_713), .Y
       (n_715));
  INVX1 fopt1(.A (rbin[2]), .Y (n_721));
  INVX2 g13227(.A (n_713), .Y (n_728));
  NOR2XL g13233(.A (rq2_wptr[1]), .B (n_737), .Y (n_735));
  DFFRX1 \rq2_wptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (rq1_wptr[3]),
       .Q (rq2_wptr[3]), .QN (n_230));
  DFFRXL rempty_reg(.RN (rrst_n), .CK (rclk), .D (n_556), .Q (rempty),
       .QN (n_1));
  DFFRX1 \wbin_reg[4] (.RN (wrst_n), .CK (wclk), .D (n_156), .Q
       (wbin[4]), .QN (n_0));
  DFFRX1 \wbin_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_199), .Q
       (wbin[3]), .QN (n_18));
  XNOR2X1 g13249(.A (n_737), .B (n_810), .Y (n_742));
  OR2XL g13250(.A (rempty), .B (n_631), .Y (n_743));
  XOR2XL g13251(.A (n_156), .B (n_199), .Y (n_744));
  XOR2XL g13252(.A (n_114), .B (n_179), .Y (n_745));
  NAND2BX1 g13253(.AN (n_95), .B (wbin[3]), .Y (n_746));
  OR2X1 g13254(.A (n_721), .B (n_792), .Y (n_747));
  OAI2BB1XL g13255(.A0N (\mem[14] [4]), .A1N (n_377), .B0 (n_83), .Y
       (n_748));
  AOI211XL g13256(.A0 (\mem[15] [3]), .A1 (n_529), .B0 (n_536), .C0
       (n_120), .Y (n_749));
  AOI211XL g13257(.A0 (\mem[15] [5]), .A1 (n_529), .B0 (n_539), .C0
       (n_151), .Y (n_750));
  AOI211XL g13258(.A0 (\mem[15] [2]), .A1 (n_529), .B0 (n_542), .C0
       (n_148), .Y (n_751));
  MXI2XL g3(.A (rq2_wptr[3]), .B (n_230), .S0 (n_169), .Y (n_753));
  INVX1 g13299(.A (n_795), .Y (n_737));
  OAI21X1 g13300(.A0 (n_792), .A1 (n_793), .B0 (n_794), .Y (n_795));
  INVX2 fopt13301(.A (n_285), .Y (n_792));
  NOR2XL g13302(.A (n_634), .B (n_428), .Y (n_793));
  NAND2XL g13303(.A (n_633), .B (n_431), .Y (n_794));
  XNOR2X1 g13306(.A (n_795), .B (n_810), .Y (n_799));
  XNOR2X1 g12619__13307(.A (n_71), .B (n_795), .Y (n_800));
  OAI2BB1XL g13309(.A0N (n_728), .A1N (n_753), .B0 (n_806), .Y (n_807));
  OR2XL g20(.A (n_728), .B (n_423), .Y (n_806));
  INVX1 g13312(.A (n_321), .Y (n_810));
  NOR2X1 g13313(.A (n_814), .B (n_819), .Y (n_815));
  NAND2X1 g1(.A (n_811), .B (n_821), .Y (n_814));
  NAND2BXL g13314(.AN (n_810), .B (n_735), .Y (n_811));
  OAI2BB1X1 g13319(.A0N (rq2_wptr[0]), .A1N (n_800), .B0 (n_728), .Y
       (n_819));
  NAND3BXL g2(.AN (rq2_wptr[1]), .B (n_810), .C (n_737), .Y (n_821));


//2 input pads
//8 output pads
//Total ports= 10
// VDD=1 & VSS=1
//Total pads=10/4 = 3 each side(left,top,right,bottom)

//INPUTS
PADDI in1(.PAD(wreq),.Y(wreq));
PADDI in2(.PAD(wclk),.Y(wclk));
PADDI in3(.PAD(wrst_n),.Y(wrst_n));
PADDI in4(.PAD(rreq),.Y(rreq));
PADDI in5(.PAD(rclk),.Y(rclk));
PADDI in6(.PAD(rrst_n),.Y(rrst_n));
PADDI in7(.PAD(wdata[0]),.Y(wdata[0]));
PADDI in8(.PAD(wdata[1]),.Y(wdata[1]));
PADDI in9(.PAD(wdata[2]),.Y(wdata[2]));
PADDI in10(.PAD(wdata[3]),.Y(wdata[3]));
PADDI in11(.PAD(wdata[4]),.Y(wdata[4]));
PADDI in12(.PAD(wdata[5]),.Y(wdata[5]));
PADDI in13(.PAD(wdata[6]),.Y(wdata[6]));
PADDI in14(.PAD(wdata[7]),.Y(wdata[7]));

//OUTPUTS
PADDO out1(.A(count[0]),.PAD(count[0]));
PADDO out2(.A(count[1]),.PAD(count[1]));
PADDO out3(.A(count[2]),.PAD(count[2]));
PADDO out4(.A(count[3]),.PAD(count[3]));
PADDO out5(.A(count[4]),.PAD(count[4]));
PADDO out6(.A(count[5]),.PAD(count[5]));
PADDO out7(.A(count[6]),.PAD(count[6]));
PADDO out8(.A(count[7]),.PAD(count[7]));
PADDO out9(.A(wfull),.PAD(wfull));
PADDO out10(.A(rempty),.PAD(rempty));

endmodule

