
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun  8 2026 11:48:30 IST (Jun  8 2026 06:18:30 UTC)

// Verification Directory fv/count8 
`timescale 1ns/1ns
module count8(clk, rst, u_d, counter);
  input clk, rst, u_d;
  output [7:0] counter;
  wire clk, rst, u_d;
  wire [7:0] counter;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_22, n_24, n_27, n_28, n_29;
  wire n_30, n_32, n_33, n_34, n_35, n_36, n_37, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_47, n_48;
  wire n_49, n_50, n_51, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_70, n_71, n_72, n_77, n_80, n_82;
  DFFRHQX1 \counter_u_d_reg[7] (.RN (n_71), .CK (clk), .D (n_72), .Q
       (counter[7]));
  OAI211X1 g7009__2398(.A0 (n_32), .A1 (n_80), .B0 (n_63), .C0 (n_67),
       .Y (n_72));
  DFFRHQX2 \counter_u_d_reg[6] (.RN (n_71), .CK (clk), .D (n_70), .Q
       (counter[6]));
  DFFRHQX1 \counter_u_d_reg[5] (.RN (n_71), .CK (clk), .D (n_68), .Q
       (counter[5]));
  OAI211X1 g7007__5107(.A0 (u_d), .A1 (n_80), .B0 (n_54), .C0 (n_65),
       .Y (n_70));
  DFFRHQX2 \counter_u_d_reg[4] (.RN (n_71), .CK (clk), .D (n_66), .Q
       (counter[4]));
  DFFRHQX4 \counter_u_d_reg[3] (.RN (n_71), .CK (clk), .D (n_64), .Q
       (counter[3]));
  MXI2X1 g7011__6260(.A (n_61), .B (n_60), .S0 (n_13), .Y (n_68));
  AOI32X1 g7015__4319(.A0 (u_d), .A1 (counter[7]), .A2 (n_57), .B0
       (n_48), .B1 (n_45), .Y (n_67));
  DFFRHQX4 \counter_u_d_reg[2] (.RN (n_71), .CK (clk), .D (n_59), .Q
       (counter[2]));
  DFFRHQX4 \counter_u_d_reg[1] (.RN (n_71), .CK (clk), .D (n_58), .Q
       (counter[1]));
  MXI2XL g7010__8428(.A (counter[4]), .B (n_18), .S0 (n_50), .Y (n_66));
  AOI31X1 g7012__5526(.A0 (counter[6]), .A1 (u_d), .A2 (n_55), .B0
       (n_56), .Y (n_65));
  MXI2X1 g7005__6783(.A (counter[3]), .B (n_47), .S0 (n_77), .Y (n_64));
  NAND3X1 g7018__3680(.A (counter[7]), .B (n_51), .C (n_80), .Y (n_63));
  CLKINVX1 g7020(.A (n_60), .Y (n_61));
  MXI2XL g7004__1617(.A (n_49), .B (counter[2]), .S0 (n_39), .Y (n_59));
  MXI2XL g7016__2802(.A (counter[1]), .B (n_42), .S0 (n_40), .Y (n_58));
  OAI22X1 g7023__1705(.A0 (n_19), .A1 (n_53), .B0 (n_44), .B1 (n_33),
       .Y (n_60));
  NAND2XL g7028__5122(.A (n_43), .B (n_29), .Y (n_57));
  NOR2X1 g7019__8246(.A (n_82), .B (n_55), .Y (n_56));
  OAI211X1 g7021__7098(.A0 (n_15), .A1 (n_53), .B0 (counter[6]), .C0
       (n_51), .Y (n_54));
  AOI31X1 g7022__6131(.A0 (n_49), .A1 (n_20), .A2 (n_22), .B0 (n_35),
       .Y (n_50));
  NOR3X1 g7035__1881(.A (n_47), .B (n_49), .C (n_41), .Y (n_48));
  NOR2XL g7027__7482(.A (n_44), .B (n_30), .Y (n_45));
  NOR2XL g7029__4733(.A (n_42), .B (n_41), .Y (n_43));
  NAND2X1 g7024__6161(.A (n_9), .B (n_27), .Y (n_55));
  AOI21X1 g7034__9315(.A0 (u_d), .A1 (counter[0]), .B0 (n_24), .Y
       (n_40));
  OAI21X1 g7013__9945(.A0 (counter[1]), .A1 (n_37), .B0 (n_36), .Y
       (n_39));
  NOR3X1 g7026__2346(.A (n_42), .B (n_28), .C (n_16), .Y (n_35));
  NOR3X1 g7031__1666(.A (counter[5]), .B (counter[6]), .C (counter[2]),
       .Y (n_34));
  NAND2BX1 g7036__7410(.AN (n_8), .B (n_17), .Y (n_33));
  NAND2XL g7043__6417(.A (n_51), .B (n_6), .Y (n_32));
  NAND3X1 g7037__2398(.A (u_d), .B (counter[4]), .C (n_6), .Y (n_30));
  NOR2XL g7030__5107(.A (n_5), .B (n_28), .Y (n_29));
  NOR2X1 g7038__6260(.A (n_11), .B (n_1), .Y (n_27));
  INVXL g7052(.A (n_37), .Y (n_24));
  NAND2X1 g7049__8428(.A (counter[6]), .B (counter[5]), .Y (n_41));
  NAND2X1 g7040__5526(.A (n_4), .B (n_10), .Y (n_53));
  NOR3X1 g7032__6783(.A (u_d), .B (counter[3]), .C (counter[1]), .Y
       (n_22));
  NAND3X1 g7033__3680(.A (u_d), .B (counter[1]), .C (counter[0]), .Y
       (n_36));
  DFFRHQX4 \counter_u_d_reg[0] (.RN (n_71), .CK (clk), .D (n_20), .Q
       (counter[0]));
  NAND2XL g7055__1617(.A (n_18), .B (n_51), .Y (n_19));
  CLKINVX1 g7051(.A (n_16), .Y (n_17));
  NAND2XL g7044__2802(.A (n_12), .B (n_18), .Y (n_15));
  NAND2XL g7057__1705(.A (n_49), .B (n_42), .Y (n_14));
  NAND2X1 g7062__5122(.A (n_51), .B (n_20), .Y (n_37));
  CLKINVX1 g7063(.A (n_12), .Y (n_13));
  NAND2X1 g7042__8246(.A (counter[5]), .B (counter[4]), .Y (n_11));
  NOR2X1 g7041__7098(.A (counter[2]), .B (counter[3]), .Y (n_10));
  AND2XL g7056__6131(.A (counter[2]), .B (counter[1]), .Y (n_9));
  NAND2XL g7048__1881(.A (counter[2]), .B (counter[4]), .Y (n_8));
  NAND2XL g7060__5115(.A (counter[1]), .B (counter[0]), .Y (n_44));
  NAND2XL g7045__7482(.A (counter[3]), .B (counter[4]), .Y (n_5));
  NOR2X1 g7058__4733(.A (counter[1]), .B (counter[0]), .Y (n_4));
  NOR2XL g7053__6161(.A (counter[1]), .B (counter[3]), .Y (n_3));
  NOR2XL g7047__9315(.A (counter[4]), .B (counter[0]), .Y (n_2));
  NAND2X1 g7046__9945(.A (counter[3]), .B (counter[0]), .Y (n_1));
  NAND2X1 g7059__2883(.A (u_d), .B (counter[3]), .Y (n_16));
  NAND2X1 g7061__2346(.A (counter[2]), .B (counter[0]), .Y (n_28));
  CLKINVX1 g7071(.A (counter[7]), .Y (n_6));
  CLKINVX1 g7066(.A (counter[0]), .Y (n_20));
  CLKINVX1 g7065(.A (counter[4]), .Y (n_18));
  CLKINVX1 g7068(.A (u_d), .Y (n_51));
  INVXL g7077(.A (rst), .Y (n_71));
  CLKINVX1 g7064(.A (counter[5]), .Y (n_12));
  CLKINVX1 g7078(.A (counter[3]), .Y (n_47));
  CLKINVX1 g7079(.A (counter[1]), .Y (n_42));
  CLKINVX1 g7067(.A (counter[2]), .Y (n_49));
  OA22X1 g2(.A0 (n_37), .A1 (n_14), .B0 (n_49), .B1 (n_36), .Y (n_77));
  NAND3X2 g7090(.A (n_34), .B (n_3), .C (n_2), .Y (n_80));
  NAND2BX1 g7092(.AN (counter[6]), .B (u_d), .Y (n_82));
endmodule

