
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun  8 2026 15:21:54 IST (Jun  8 2026 09:51:54 UTC)

// Verification Directory fv/lfsr 
`timescale 1ns/1ns
module lfsr(out, clk, rst);
  input clk, rst;
  output [3:0] out;
  wire clk, rst;
  wire [3:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  DFFQXL \out_reg[0] (.CK (clk), .D (n_5), .Q (out[0]));
  NOR2XL g20__2398(.A (rst), .B (n_4), .Y (n_5));
  AOI21XL g21__5107(.A0 (out[2]), .A1 (out[3]), .B0 (n_3), .Y (n_4));
  NOR2XL g22__6260(.A (out[2]), .B (out[3]), .Y (n_3));
  DFFQX1 \out_reg[3] (.CK (clk), .D (n_2), .Q (out[3]));
  NOR2BX1 g24__4319(.AN (out[2]), .B (rst), .Y (n_2));
  DFFQX1 \out_reg[2] (.CK (clk), .D (n_1), .Q (out[2]));
  NOR2BX1 g26__8428(.AN (out[1]), .B (rst), .Y (n_1));
  DFFQXL \out_reg[1] (.CK (clk), .D (n_0), .Q (out[1]));
  NOR2BX1 g28__5526(.AN (out[0]), .B (rst), .Y (n_0));
endmodule

