
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Jun  9 2026 14:31:05 IST (Jun  9 2026 09:01:05 UTC)

// Verification Directory fv/TrafficLight 
`timescale 1 ns / 1 ns
module TrafficLight(clk, rst, LED_NS, LED_WE);
  input clk, rst;
  output [2:0] LED_NS, LED_WE;
  wire clk, rst;
  wire [2:0] LED_NS, LED_WE;
  wire [3:0] count;
  wire [5:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, n_2, n_7;
  wire n_9, n_14, n_15, n_28, n_37, n_43, n_45, n_56;
  wire n_60, n_71, n_72, n_73, n_74, n_79, n_84, n_87;
  wire n_88, n_90, n_91, n_92, n_95, n_96, n_101, n_119;
  wire n_172, n_180, n_181, n_187, n_192, n_193, n_194, n_197;
  wire n_205, n_206, n_207, n_209, n_212, n_215, n_217, n_221;
  wire n_222, n_223, n_224, n_225, n_228, n_229, n_247, n_249;
  wire n_259, n_260, n_261, n_262, n_266, n_267, n_269, n_270;
  wire n_289, n_304, n_317, n_318, n_348, n_352, n_354, n_355;
  wire n_364, n_365, n_366, n_368, n_369, n_373, n_393, n_394;
  wire n_395, n_396, n_397, n_398, n_399, n_400, n_401, n_402;
  wire n_403, n_404, n_405, n_406, n_408, n_409, n_419, n_420;
  wire n_421, n_422, n_423, n_424, n_426, n_427, n_428, n_429;
  wire n_442;
  DFFRHQX8 \count_reg[2] (.RN (n_101), .CK (clk), .D (n_225), .Q
       (count[2]));
  DFFRHQX2 \count_reg[3] (.RN (n_101), .CK (clk), .D (n_267), .Q
       (count[3]));
  DFFRX2 \count_reg[1] (.RN (n_101), .CK (clk), .D (n_401), .Q (n_304),
       .QN (count[1]));
  SDFFRHQX2 \count_reg[0] (.RN (n_101), .CK (clk), .D (n_96), .SI
       (n_84), .SE (n_317), .Q (count[0]));
  DFFRHQX4 \state_reg[3] (.RN (n_101), .CK (clk), .D (n_87), .Q
       (state[3]));
  DFFRHQX4 \state_reg[5] (.RN (n_101), .CK (clk), .D (n_88), .Q
       (state[5]));
  DFFRHQX4 \state_reg[4] (.RN (n_101), .CK (clk), .D (n_90), .Q
       (state[4]));
  DFFRHQX4 \state_reg[2] (.RN (n_101), .CK (clk), .D (n_92), .Q
       (state[2]));
  DFFRHQX4 \state_reg[1] (.RN (n_101), .CK (clk), .D (n_91), .Q
       (state[1]));
  TLATNXL \LED_NS_reg[0] (.GN (n_96), .D (n_71), .Q (LED_NS[0]), .QN
       (UNCONNECTED));
  AOI21X1 g10757__4319(.A0 (n_422), .A1 (n_56), .B0 (n_369), .Y (n_95));
  OAI21XL g10759__5526(.A0 (n_422), .A1 (n_15), .B0 (n_428), .Y (n_92));
  OAI21XL g10756__6783(.A0 (n_422), .A1 (n_398), .B0 (n_209), .Y
       (n_91));
  TLATNXL \LED_NS_reg[1] (.GN (n_96), .D (n_194), .Q (LED_NS[1]), .QN
       (UNCONNECTED0));
  TLATNXL \LED_WE_reg[2] (.GN (n_96), .D (n_354), .Q (LED_WE[2]), .QN
       (UNCONNECTED1));
  TLATNXL \LED_NS_reg[2] (.GN (n_96), .D (n_197), .Q (LED_NS[2]), .QN
       (UNCONNECTED2));
  OAI21XL g10762__3680(.A0 (n_422), .A1 (n_28), .B0 (n_426), .Y (n_90));
  TLATNXL \LED_WE_reg[1] (.GN (n_96), .D (n_352), .Q (LED_WE[1]), .QN
       (UNCONNECTED3));
  OAI21XL g10761__2802(.A0 (n_422), .A1 (n_9), .B0 (n_355), .Y (n_88));
  TLATNXL \LED_WE_reg[0] (.GN (n_96), .D (n_172), .Q (LED_WE[0]), .QN
       (UNCONNECTED4));
  OAI21XL g10763__1705(.A0 (n_422), .A1 (n_249), .B0 (n_429), .Y
       (n_87));
  CLKINVX2 g10768(.A (n_400), .Y (n_84));
  INVXL g10774(.A (n_422), .Y (n_96));
  AOI22X1 g10781__6161(.A0 (n_72), .A1 (n_74), .B0 (n_212), .B1 (n_71),
       .Y (n_73));
  NAND2X1 g10788__5477(.A (n_259), .B (n_409), .Y (n_60));
  NOR2X1 g10798__6260(.A (count[3]), .B (n_45), .Y (n_56));
  CLKINVX2 g10791(.A (n_79), .Y (n_74));
  CLKINVX1 g10810(.A (n_261), .Y (n_71));
  INVXL g10804(.A (n_409), .Y (n_72));
  INVXL g10817(.A (n_442), .Y (n_45));
  AOI21XL g10823__2802(.A0 (count[0]), .A1 (count[1]), .B0 (n_318), .Y
       (n_43));
  NAND2X4 g10795__7098(.A (n_7), .B (n_318), .Y (n_79));
  NOR2X1 g10827__6260(.A (state[1]), .B (state[4]), .Y (n_14));
  NOR2X1 g10830__5526(.A (count[2]), .B (count[3]), .Y (n_7));
  NOR2X2 g10831__1617(.A (state[3]), .B (state[0]), .Y (n_37));
  INVXL g10860(.A (rst), .Y (n_101));
  CLKINVX1 g10855(.A (state[5]), .Y (n_2));
  CLKINVX1 g10847(.A (state[2]), .Y (n_15));
  CLKINVX1 g10848(.A (state[4]), .Y (n_28));
  DFFSHQX4 \state_reg[0] (.SN (n_101), .CK (clk), .D (n_404), .Q
       (state[0]));
  NOR2X4 g10834__10889(.A (state[4]), .B (state[2]), .Y (n_119));
  CLKINVX1 g181(.A (n_229), .Y (n_172));
  CLKAND2X2 g45(.A (n_119), .B (n_180), .Y (n_181));
  NOR2X2 g46(.A (state[1]), .B (state[5]), .Y (n_180));
  NAND2X2 g60(.A (n_289), .B (n_373), .Y (n_187));
  NOR2X2 g91(.A (n_192), .B (n_60), .Y (n_193));
  NAND2X1 g95(.A (n_394), .B (n_397), .Y (n_192));
  INVXL g97(.A (n_397), .Y (n_194));
  NOR2XL g94(.A (n_71), .B (n_194), .Y (n_197));
  AOI22XL g10929(.A0 (n_79), .A1 (n_194), .B0 (n_71), .B1 (n_207), .Y
       (n_209));
  NOR2X2 g10794__10931(.A (n_205), .B (n_206), .Y (n_207));
  NAND2XL g10840__10932(.A (count[2]), .B (count[3]), .Y (n_205));
  CLKINVX1 g10933(.A (n_318), .Y (n_206));
  CLKINVX1 g10936(.A (n_207), .Y (n_212));
  NOR2X1 g10937(.A (n_399), .B (n_212), .Y (n_215));
  NAND2X1 g10938(.A (count[2]), .B (n_96), .Y (n_217));
  OAI21X1 g10939(.A0 (n_215), .A1 (n_224), .B0 (n_217), .Y (n_225));
  AOI21X1 g63(.A0 (n_222), .A1 (n_422), .B0 (n_223), .Y (n_224));
  NOR2XL g66(.A (count[2]), .B (n_221), .Y (n_222));
  AND2X1 g65(.A (count[2]), .B (n_221), .Y (n_223));
  NAND2X2 g41(.A (n_228), .B (n_181), .Y (n_229));
  BUFX2 g42(.A (n_393), .Y (n_228));
  INVX1 fopt10943(.A (state[3]), .Y (n_247));
  CLKINVX2 fopt2(.A (state[3]), .Y (n_249));
  AOI21X2 g34(.A0 (n_229), .A1 (n_261), .B0 (n_207), .Y (n_262));
  INVX1 fopt37(.A (n_260), .Y (n_261));
  INVXL fopt38(.A (n_259), .Y (n_260));
  NAND3X2 g36(.A (n_119), .B (n_180), .C (n_406), .Y (n_259));
  OAI21X1 g23(.A0 (n_215), .A1 (n_95), .B0 (n_266), .Y (n_267));
  NAND2X1 g24(.A (count[3]), .B (n_96), .Y (n_266));
  NAND2X2 g268(.A (state[2]), .B (n_398), .Y (n_269));
  NAND2X2 g265(.A (n_2), .B (n_247), .Y (n_270));
  CLKAND2X2 g2(.A (n_119), .B (n_37), .Y (n_289));
  NAND2X1 g10832__10960(.A (count[0]), .B (n_304), .Y (n_221));
  CLKAND2X3 g10968(.A (n_304), .B (n_317), .Y (n_318));
  INVX2 g10995(.A (n_424), .Y (n_352));
  NAND2X1 g10838__10998(.A (state[4]), .B (n_15), .Y (n_348));
  NOR2XL g11001(.A (n_352), .B (n_172), .Y (n_354));
  AOI22X1 g11002(.A0 (n_352), .A1 (n_74), .B0 (n_79), .B1 (n_72), .Y
       (n_355));
  NAND2X1 g21(.A (n_364), .B (n_365), .Y (n_366));
  NOR2X1 g11008(.A (state[5]), .B (state[0]), .Y (n_364));
  NOR2X1 g22(.A (state[1]), .B (state[3]), .Y (n_365));
  INVX1 g19(.A (count[0]), .Y (n_317));
  OR2XL g11009(.A (state[5]), .B (n_398), .Y (n_368));
  NOR2BXL g11010(.AN (count[3]), .B (n_442), .Y (n_369));
  OAI2BB1X1 g11014(.A0N (n_398), .A1N (state[5]), .B0 (n_368), .Y
       (n_373));
  NAND3X1 g26(.A (n_119), .B (n_180), .C (n_393), .Y (n_394));
  NOR2X1 g27(.A (state[0]), .B (n_249), .Y (n_393));
  NAND3X1 g11015(.A (n_396), .B (n_119), .C (n_37), .Y (n_397));
  NOR2X1 g35(.A (state[5]), .B (n_395), .Y (n_396));
  CLKINVX1 g11016(.A (state[1]), .Y (n_395));
  CLKINVX2 g37(.A (state[1]), .Y (n_398));
  OAI22X1 g11017(.A0 (n_43), .A1 (n_400), .B0 (n_422), .B1 (count[1]),
       .Y (n_401));
  AOI21X2 g96(.A0 (n_79), .A1 (n_399), .B0 (n_262), .Y (n_400));
  NAND2X2 g11018(.A (n_187), .B (n_423), .Y (n_399));
  OAI21X1 g10760__11019(.A0 (n_403), .A1 (n_422), .B0 (n_73), .Y
       (n_404));
  DLY2X1 g1(.A (n_402), .Y (n_403));
  CLKINVX2 g11020(.A (state[0]), .Y (n_402));
  NAND2X2 g11021(.A (n_28), .B (n_402), .Y (n_405));
  NOR2X2 g10841__11022(.A (state[3]), .B (n_402), .Y (n_406));
  NAND3X1 g10813__11023(.A (n_37), .B (n_14), .C (n_408), .Y (n_409));
  NOR2X1 g11024(.A (n_9), .B (state[2]), .Y (n_408));
  INVX2 g11025(.A (state[5]), .Y (n_9));
  NAND2X4 g178(.A (n_421), .B (n_193), .Y (n_422));
  NOR2X1 g182(.A (n_419), .B (n_420), .Y (n_421));
  NOR2X2 g188(.A (n_348), .B (n_366), .Y (n_419));
  NOR3X4 g185(.A (n_269), .B (n_270), .C (n_405), .Y (n_420));
  NOR2X1 g11029(.A (n_420), .B (n_419), .Y (n_423));
  AOI22XL g183(.A0 (n_79), .A1 (n_352), .B0 (n_172), .B1 (n_207), .Y
       (n_426));
  CLKINVX1 g187(.A (n_419), .Y (n_424));
  MXI2XL g180(.A (n_427), .B (n_194), .S0 (n_74), .Y (n_428));
  BUFX2 g184(.A (n_420), .Y (n_427));
  AOI22XL g179(.A0 (n_74), .A1 (n_427), .B0 (n_212), .B1 (n_172), .Y
       (n_429));
  NOR2BX1 g11033(.AN (count[2]), .B (n_221), .Y (n_442));
endmodule

