
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 24 2026 13:21:04 IST (Jun 24 2026 07:51:04 UTC)

// Verification Directory fv/TrafficLight 

module TrafficLight(clk, rst, LED_NS, LED_WE);
  input clk, rst;
  output [2:0] LED_NS, LED_WE;
  wire clk, rst;
  wire [2:0] LED_NS, LED_WE;
  wire [3:0] count;
  wire [5:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, n_11, n_19;
  wire n_20, n_44, n_45, n_52, n_53, n_57, n_71, n_85;
  wire n_88, n_91, n_113, n_115, n_229, n_231, n_269, n_394;
  wire n_404, n_424, n_425, n_426, n_428, n_429, n_438, n_480;
  wire n_522, n_659, n_715, n_717, n_719, n_820, n_821, n_904;
  wire n_906, n_907, n_909, n_924, n_926, n_927, n_936, n_937;
  wire n_948, n_979, n_980, n_982, n_984, n_985, n_990, n_1263;
  wire n_1264, n_1315, n_1316, n_1318, n_1331, n_1332, n_1333, n_1347;
  wire n_1348, n_1350, n_1351, n_1359, n_1372, n_1373, n_1374, n_1375;
  wire n_1381, n_1404, n_1408, n_1415, n_1417, n_1418, n_1419, n_1420;
  wire n_1421, n_1536, n_1538, n_1562, n_1563, n_1564, n_1565, n_1566;
  wire n_1567, n_1568, n_1569, n_1571, n_1583, n_1584, n_1585, n_1586;
  wire n_1587, n_1591, n_1637, n_1638, n_1640, n_1642, n_1643, n_1644;
  wire n_1646, n_1647, n_1648, n_1650, n_1652, n_1653, n_1824, n_1825;
  wire n_1826, n_1866, n_1867, n_1868, n_1869, n_1872, n_1875, n_1876;
  wire n_1885, n_1886, n_1887, n_1888, n_1889, n_1890;
  DFFRHQX4 \count_reg[2] (.RN (n_91), .CK (clk), .D (n_821), .Q
       (count[2]));
  DFFRHQX4 \count_reg[3] (.RN (n_91), .CK (clk), .D (n_1648), .Q
       (count[3]));
  DFFRHQX4 \count_reg[1] (.RN (n_91), .CK (clk), .D (n_1333), .Q
       (count[1]));
  DFFRHQX4 \count_reg[0] (.RN (n_91), .CK (clk), .D (n_1890), .Q
       (count[0]));
  DFFRHQX4 \state_reg[2] (.RN (n_91), .CK (clk), .D (n_1315), .Q
       (state[2]));
  DFFRHQX4 \state_reg[5] (.RN (n_91), .CK (clk), .D (n_1318), .Q
       (state[5]));
  DFFRHQX4 \state_reg[1] (.RN (n_91), .CK (clk), .D (n_1869), .Q
       (state[1]));
  OAI21X1 g13617__8428(.A0 (n_88), .A1 (n_522), .B0 (n_71), .Y (n_85));
  OAI21X1 g13619__1881(.A0 (n_1653), .A1 (n_88), .B0 (n_980), .Y
       (n_71));
  TLATNXL \LED_NS_reg[2] (.GN (n_88), .D (n_52), .Q (LED_NS[2]), .QN
       (UNCONNECTED));
  TLATNXL \LED_WE_reg[0] (.GN (n_88), .D (n_937), .Q (LED_WE[0]), .QN
       (UNCONNECTED0));
  TLATNXL \LED_NS_reg[0] (.GN (n_88), .D (n_1417), .Q (LED_NS[0]), .QN
       (UNCONNECTED1));
  TLATNXL \LED_NS_reg[1] (.GN (n_88), .D (n_1415), .Q (LED_NS[1]), .QN
       (UNCONNECTED2));
  TLATNXL \LED_WE_reg[2] (.GN (n_88), .D (n_990), .Q (LED_WE[2]), .QN
       (UNCONNECTED3));
  TLATNXL \LED_WE_reg[1] (.GN (n_88), .D (n_1374), .Q (LED_WE[1]), .QN
       (UNCONNECTED4));
  NOR2XL g13641__6161(.A (n_948), .B (n_53), .Y (n_88));
  AOI21X1 g13643__6417(.A0 (n_438), .A1 (n_927), .B0 (n_424), .Y
       (n_53));
  INVXL g13650(.A (n_948), .Y (n_52));
  NOR2XL g13653__4319(.A (count[0]), .B (n_44), .Y (n_45));
  NAND2X1 g13664__5122(.A (n_1653), .B (n_980), .Y (n_44));
  CLKINVX2 g13676(.A (n_1653), .Y (n_57));
  OA21X1 g13674__1666(.A0 (count[0]), .A1 (count[1]), .B0 (n_19), .Y
       (n_20));
  NAND2X1 g13687__8246(.A (count[0]), .B (count[1]), .Y (n_19));
  CLKINVX2 g13702(.A (state[5]), .Y (n_11));
  INVXL g13706(.A (rst), .Y (n_91));
  INVXL fopt13741(.A (state[4]), .Y (n_113));
  CLKBUFX2 fopt13743(.A (state[4]), .Y (n_115));
  DFFRHQX4 \state_reg[4] (.RN (n_91), .CK (clk), .D (n_1351), .Q
       (state[4]));
  XNOR2X1 g13864(.A (count[2]), .B (n_19), .Y (n_229));
  CLKINVX1 g13865(.A (count[2]), .Y (n_231));
  CLKINVX1 g13901(.A (n_1567), .Y (n_269));
  NAND2XL g126(.A (n_44), .B (n_926), .Y (n_394));
  NAND2X1 g43(.A (state[3]), .B (n_113), .Y (n_404));
  CLKINVX2 g166(.A (n_424), .Y (n_425));
  CLKINVX1 g167(.A (n_1564), .Y (n_424));
  NOR2X1 g162(.A (n_985), .B (n_428), .Y (n_429));
  NOR2X2 g165(.A (state[2]), .B (state[5]), .Y (n_426));
  NAND2X1 g169(.A (state[4]), .B (n_979), .Y (n_428));
  OAI2BB1X1 g158(.A0N (n_428), .A1N (n_404), .B0 (n_984), .Y (n_438));
  NAND2XL g30(.A (state[0]), .B (n_88), .Y (n_480));
  NAND2BX1 g14022(.AN (n_924), .B (n_719), .Y (n_522));
  BUFX2 fopt14051(.A (n_1565), .Y (n_659));
  BUFX2 g14069(.A (n_1421), .Y (n_715));
  MX2X1 g14070(.A (n_1875), .B (n_924), .S0 (n_1421), .Y (n_717));
  INVX3 g14073(.A (n_1421), .Y (n_719));
  OAI21X1 g72(.A0 (n_1316), .A1 (n_1264), .B0 (n_820), .Y (n_821));
  NAND2XL g74(.A (count[2]), .B (n_88), .Y (n_820));
  CLKAND2X3 g24(.A (n_1565), .B (n_1563), .Y (n_904));
  CLKINVX3 g10(.A (state[5]), .Y (n_906));
  CLKINVX2 g11(.A (state[2]), .Y (n_907));
  CLKINVX2 g12(.A (state[2]), .Y (n_909));
  BUFX2 g14164(.A (n_1568), .Y (n_924));
  OAI21XL g32(.A0 (n_1569), .A1 (n_115), .B0 (n_1421), .Y (n_926));
  NAND2X1 g33(.A (n_659), .B (n_1569), .Y (n_927));
  NOR3X1 g39(.A (n_424), .B (n_404), .C (n_936), .Y (n_937));
  CLKINVX2 g40(.A (n_1408), .Y (n_936));
  NAND2X1 g14175(.A (n_1875), .B (n_1872), .Y (n_948));
  INVX2 fopt(.A (state[3]), .Y (n_979));
  CLKINVX1 fopt1(.A (n_982), .Y (n_980));
  INVXL fopt3(.A (state[3]), .Y (n_982));
  INVXL fopt14187(.A (n_985), .Y (n_984));
  CLKINVX1 fopt14188(.A (n_426), .Y (n_985));
  NOR2XL g14195(.A (n_937), .B (n_1374), .Y (n_990));
  NOR2XL g14344(.A (n_1591), .B (n_1263), .Y (n_1264));
  NAND2XL g14345(.A (n_1875), .B (n_57), .Y (n_1263));
  OAI21X1 g14367(.A0 (n_1347), .A1 (n_909), .B0 (n_717), .Y (n_1315));
  NAND2X2 g14368(.A (n_229), .B (n_1347), .Y (n_1316));
  OAI21X1 g13622__14370(.A0 (n_1347), .A1 (n_11), .B0 (n_1375), .Y
       (n_1318));
  OAI21X1 g87(.A0 (n_1888), .A1 (n_1331), .B0 (n_1332), .Y (n_1333));
  NOR2XL g88(.A (n_394), .B (n_1876), .Y (n_1331));
  NAND2XL g89(.A (count[1]), .B (n_88), .Y (n_1332));
  CLKINVX20 g13639_dup14385(.A (n_88), .Y (n_1347));
  OAI211XL g14386(.A0 (n_1347), .A1 (n_1348), .B0 (n_1350), .C0
       (n_1373), .Y (n_1351));
  INVXL fopt14387(.A (n_115), .Y (n_1348));
  NAND2XL g14389(.A (n_937), .B (n_57), .Y (n_1350));
  NOR2X1 g14397(.A (state[0]), .B (n_1381), .Y (n_1359));
  NAND2X1 g14402(.A (n_1372), .B (n_715), .Y (n_1373));
  CLKINVX2 g14403(.A (n_1643), .Y (n_1372));
  BUFX2 g1(.A (n_1372), .Y (n_1374));
  MXI2X1 g14404(.A (n_269), .B (n_1372), .S0 (n_719), .Y (n_1375));
  CLKINVX2 g14406(.A (state[1]), .Y (n_1381));
  DFFRHQX4 \state_reg[3] (.RN (n_91), .CK (clk), .D (n_85), .Q
       (state[3]));
  CLKAND2X3 g82(.A (count[1]), .B (count[3]), .Y (n_1404));
  CLKAND2X6 g81(.A (n_906), .B (n_907), .Y (n_1408));
  CLKINVX1 g76(.A (n_1875), .Y (n_1415));
  INVXL g14427(.A (n_1872), .Y (n_1417));
  NAND2X4 g21(.A (n_1418), .B (n_1420), .Y (n_1421));
  NOR2X2 g23(.A (count[0]), .B (count[2]), .Y (n_1418));
  NOR2X2 g22(.A (count[3]), .B (n_1419), .Y (n_1420));
  CLKINVX1 g14428(.A (count[1]), .Y (n_1419));
  CLKINVX1 g14471(.A (n_1536), .Y (n_1538));
  NOR2X1 g14478(.A (state[1]), .B (n_1562), .Y (n_1563));
  NAND2XL g50(.A (n_1564), .B (n_1565), .Y (n_1566));
  NOR2X1 g51(.A (state[1]), .B (state[0]), .Y (n_1564));
  NOR2X4 g52(.A (state[4]), .B (state[3]), .Y (n_1565));
  NAND2X2 g49(.A (n_1567), .B (n_1568), .Y (n_1569));
  NAND2X2 g53(.A (state[5]), .B (n_909), .Y (n_1567));
  NAND2X2 g54(.A (state[2]), .B (n_11), .Y (n_1568));
  CLKAND2X3 g14481(.A (n_1565), .B (n_1359), .Y (n_1571));
  NAND2X1 g34(.A (n_480), .B (n_1585), .Y (n_1586));
  OAI21X2 g35(.A0 (n_1652), .A1 (n_1583), .B0 (n_1584), .Y (n_1585));
  CLKAND2X3 g42(.A (n_269), .B (n_719), .Y (n_1583));
  CLKINVX6 g38(.A (n_88), .Y (n_1584));
  CLKINVX1 g20(.A (n_1566), .Y (n_1587));
  NAND2X1 g14491(.A (n_1643), .B (n_1642), .Y (n_1591));
  AOI22X1 g103(.A0 (n_1653), .A1 (n_1637), .B0 (n_1638), .B1 (n_1644),
       .Y (n_1640));
  NOR2X1 g107(.A (n_1872), .B (n_1538), .Y (n_1637));
  AND2X1 g106(.A (n_1536), .B (n_1421), .Y (n_1638));
  NAND3X1 g69(.A (n_1875), .B (n_1642), .C (n_1643), .Y (n_1644));
  NAND2X2 g71(.A (n_1569), .B (n_1587), .Y (n_1642));
  NAND2X2 g70(.A (n_425), .B (n_429), .Y (n_1643));
  OAI21X1 g14493(.A0 (n_1886), .A1 (n_1646), .B0 (n_1647), .Y (n_1648));
  NOR2XL g90(.A (n_1591), .B (n_1263), .Y (n_1646));
  NAND2XL g91(.A (count[3]), .B (n_88), .Y (n_1647));
  NOR2BX1 g29(.AN (n_1650), .B (n_1872), .Y (n_1652));
  NAND3X1 g31(.A (n_1536), .B (count[2]), .C (n_1404), .Y (n_1650));
  INVX3 g14494(.A (count[0]), .Y (n_1536));
  NAND3X2 g14496(.A (n_1536), .B (count[2]), .C (n_1404), .Y (n_1653));
  MXI2X1 g14607(.A (count[3]), .B (n_1824), .S0 (n_1825), .Y (n_1826));
  INVX1 g14608(.A (count[3]), .Y (n_1824));
  OR2X1 g14609(.A (n_231), .B (n_19), .Y (n_1825));
  NAND3XL g67(.A (n_1866), .B (n_1867), .C (n_1868), .Y (n_1869));
  NAND2XL g14641(.A (state[1]), .B (n_88), .Y (n_1866));
  NAND2XL g68(.A (n_1415), .B (n_715), .Y (n_1867));
  NAND2XL g14642(.A (n_57), .B (n_1417), .Y (n_1868));
  AOI22X1 g14644(.A0 (n_1872), .A1 (n_719), .B0 (n_57), .B1 (n_1875),
       .Y (n_1876));
  NAND2X4 g14645(.A (n_1408), .B (n_904), .Y (n_1872));
  NAND2X4 g14647(.A (n_1408), .B (n_1571), .Y (n_1875));
  NAND2X2 g14654(.A (n_1826), .B (n_1885), .Y (n_1886));
  CLKINVX20 g3_dup14655(.A (n_88), .Y (n_1885));
  NAND2X2 g14656(.A (n_20), .B (n_1887), .Y (n_1888));
  CLKINVX12 g14657(.A (n_88), .Y (n_1887));
  OAI211X1 g14658(.A0 (n_1536), .A1 (n_1885), .B0 (n_1889), .C0
       (n_1640), .Y (n_1890));
  NAND2X1 g13636__14659(.A (n_45), .B (n_1885), .Y (n_1889));
  DFFSX1 \state_reg[0] (.SN (n_91), .CK (clk), .D (n_1586), .Q
       (state[0]), .QN (n_1562));
endmodule

